//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZSI_IMPORTLISTINI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sqlexpress;Initial Catalog=ts_dms;Persist Security Info=True;User I" +
            "D=sa;Password=sash17ne")]
        public string MetodoConnectionString {
            get {
                return ((string)(this["MetodoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingPathFileListino {
            get {
                return ((string)(this["SettingPathFileListino"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>MACROARTICOLO|A</string>
  <string>LISTINO|</string>
  <string>DEF_COL_A|</string>
  <string>VAL_COL_A|I</string>
  <string>DEF_COL_B|</string>
  <string>VAL_COL_B|J</string>
  <string>DEF_COL_C|</string>
  <string>VAL_COL_C|K</string>
  <string>DEF_COL_D|</string>
  <string>VAL_COL_D|L</string>
  <string>DEF_COL_E|</string>
  <string>VAL_COL_E|M</string>
  <string>DEF_COL_F|</string>
  <string>VAL_COL_F|N</string>
  <string>DEF_COL_G|</string>
  <string>VAL_COL_G|O</string>
  <string>DEF_COL_H|</string>
  <string>VAL_COL_H|P</string>
  <string>DEF_COL_I|</string>
  <string>VAL_COL_I|Q</string>
  <string>DEF_COL_L|</string>
  <string>VAL_COL_L|R</string>
  <string>DEF_COL_M|</string>
  <string>VAL_COL_M|S</string>
  <string>DEF_COL_N|</string>
  <string>VAL_COL_N|T</string>
  <string>DEF_COL_O|</string>
  <string>VAL_COL_O|U</string>
  <string>DEF_COL_P|</string>
  <string>VAL_COL_P|V</string>
  <string>DEF_COL_Q|</string>
  <string>VAL_COL_Q|W</string>
  <string>DEF_COL_R|</string>
  <string>VAL_COL_R|X</string>
  <string>DEF_COL_S|</string>
  <string>VAL_COL_S|Y</string>
  <string>DEF_COL_T|</string>
  <string>VAL_COL_T|Z</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColumnFields {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnFields"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ITA_SP_UPDATE_DATIPROVVIGIONI")]
        public string MetodoAggiornaCMD {
            get {
                return ((string)(this["MetodoAggiornaCMD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) FROM ITA_TAB_DEFPROV WHERE MACROARTICOLO =\'{0}\' AND {1} =CAST(REP" +
            "LACE(\'{2}\', \',\', \'.\') AS DECIMAL(19,3))")]
        public string MetodoVerifica {
            get {
                return ((string)(this["MetodoVerifica"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM ITA_VISTA_DEFPROV ORDER BY MACROARTICOLO, DataModifica DESC")]
        public string MetodoStoricoCMD {
            get {
                return ((string)(this["MetodoStoricoCMD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("listino")]
        public string FoglioListino {
            get {
                return ((string)(this["FoglioListino"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT T,NR, CODCLIFOR, DSCCONTO, CODART, DSCARTICOLO, UM, INIZIOVALIDITA, FINEVALIDITA, QTAMINIMA, PREZZO_MAGG, PREZZO_MAGGEURO, NRLISTINO, DSCLISTINO, 
CODARTRIC, CODPADRE, DSCA, COD_IMBALLO, DSCIMBALLO, QTA_COLLI, PROGRESSIVO, IDRIGA, 
('update GESTIONEPREZZIRIGHE set PREZZO_MAGG = #PREZZO_MAGG#, PREZZO_MAGGEURO = #PREZZO_MAGGEURO# where RIFPROGRESSIVO = ' + CAST(PROGRESSIVO AS VARCHAR) + ' and IDRIGA = ' + CAST(IDRIGA AS VARCHAR)) as SQLUPDATE , 
('update GESTIONEPREZZI set INIZIOVALIDITA = @0, FINEVALIDITA =@1 where PROGRESSIVO = ' + CAST(PROGRESSIVO AS VARCHAR)) as SQLUPDATE_TESTATE 
FROM dbo.VISTA_GESTIONEPREZZI")]
        public string MetodoPrezziparticolari {
            get {
                return ((string)(this["MetodoPrezziparticolari"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp")]
        public string pathServerApp {
            get {
                return ((string)(this["pathServerApp"]));
            }
        }
    }
}
