IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXTRARIGHEDOC' AND COLUMN_NAME = 'MAGSTATORIGA')
	ALTER TABLE EXTRARIGHEDOC ADD MAGSTATORIGA SMALLINT DEFAULT 0
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXTRARIGHEDOC' AND COLUMN_NAME = 'MAGSTATOM05')
	ALTER TABLE EXTRARIGHEDOC ADD MAGSTATOM05 SMALLINT DEFAULT 0
GO



IF OBJECT_ID ('dbo.EXCEL_PORTAFOGLIOORDINI') IS NOT NULL
	DROP VIEW dbo.EXCEL_PORTAFOGLIOORDINI
GO

create view EXCEL_PORTAFOGLIOORDINI as 
SELECT 
        R.DATACONSEGNA
        , (CASE WHEN datediff(d, getdate(), R.DATACONSEGNA) < -7 THEN -7 ELSE datediff(d, getdate(), R.DATACONSEGNA) END) AS gg_dataconsegna 
        , (CASE WHEN ACF.STATOBOLLE = 2 THEN '[BLOCCATO] ' ELSE '' END) + AC.DSCCONTO1 AS RAGIONESOCIALE
        , T.TIPODOC + '/' + CAST(T.ESERCIZIO AS VARCHAR) + '/' + CAST(T.NUMERODOC AS VARCHAR) AS DOCUMENTO -- + '/' + CAST(R.POSIZIONE AS VARCHAR) AS DOCUMENTO 
        , T.NUMRIFDOC, ET.RIFCLI 
        , R.CODART AS ARTICOLO
        , R.DESCRIZIONEART AS DESCRIZIONE
 		, I.DESCRIZIONE IMBALLO 
        , CAST(R.QTAGESTRES AS INT) AS QTAGESTRES
        , CAST(R.NRPEZZIIMBALLO AS INT) AS NRPEZZIIMBALLO
        , CAST((CASE WHEN ISNULL(R.NRPEZZIIMBALLO,0) = 0 THEN 0 ELSE ceiling((R.QTAGESTRES/R.NRPEZZIIMBALLO)) END) AS INT) FUSTI 
        , isnull(ER.NRLOTTO, 'NESSUN LOTTO') AS NRLOTTO
        , SD.RAGSOCSPED AS SPEDIZIONIERE
        , (CASE WHEN ISNULL(ER.NOTECLI,'') <> '' THEN ER.NOTECLI ELSE NC.NOTE END) NOTECLI 
        , (CASE WHEN ISNULL(ER.NOTEART,'') <> '' THEN ER.NOTEART ELSE NA.NOTE END) NOTEART 
        , ER.NOTEMAG, '' MAGAZZINO 
        , ER.POSIZIONAMENTO
        , isnull(ER.CONFEZIONATO, 0) AS CONFEZIONATO
        , isnull(ER.DISPONIBILITA, 0) AS DISPONIBILITA 
        , ER.QTASPEDIBILE
        , T.ESERCIZIO, T.TIPODOC, T.NUMERODOC, T.BIS, T.DATADOC 
        , 'ALFREDO.DEANGELO@GMAIL.COM;knosmailservice@gmail.com' AS EMAIL_CLIENTE --s.ferrigato@zschimmer-schwarz.com;m.michieletti@zschimmer-schwarz.com;
        , T.PROGRESSIVO AS IDTESTA, R.IDRIGA 
        , AA.GRUPPO, AA.CATEGORIA, AA.CODCATEGORIASTAT 
        , T.CODCLIFOR
        , T.DATARIFDOC
        , I.CODICE CODIMBALLO
        , isnull(SD.CODSPED, 0) AS CODSPED
        , R.UMGEST
        , ER.DATACARICO
        , ER.MAGSTATORIGA
        , ER.MAGSTATOM05
        , EXTRACLIENTI.CLIENTESPECIALE
FROM TESTEDOCUMENTI T JOIN EXTRATESTEDOC ET ON T.PROGRESSIVO = ET.IDTESTA 
JOIN RIGHEDOCUMENTI R ON T.PROGRESSIVO = R.IDTESTA 
JOIN ANAGRAFICACF AC ON AC.CODCONTO = T.CODCLIFOR 
JOIN EXTRACLIENTI ON EXTRACLIENTI.CODCONTO = AC.CODCONTO
JOIN ANAGRAFICAARTICOLI AA ON AA.CODICE = R.CODART 
JOIN EXTRARIGHEDOC ER ON ER.IDTESTA = R.IDTESTA AND ER.IDRIGA = R.IDRIGA 
JOIN ANAGRAFICARISERVATICF ACF ON ACF.ESERCIZIO = YEAR(GETDATE()) AND ACF.CODCONTO = T.CODCLIFOR 
LEFT OUTER JOIN TABIMBALLI I ON R.CODIMBALLO = I.CODICE 
LEFT OUTER JOIN ZSI_NOTECLI NC ON T.CODCLIFOR = NC.CODCLI AND (T.NUMDESTDIVERSAMERCI = NC.CODDEST OR (T.NUMDESTDIVERSAMERCI = 0 AND NC.CODDEST = -1) OR (T.NUMDESTDIVERSAMERCI <> 0 AND NOT EXISTS(SELECT 1 FROM ZSI_NOTECLI Z WHERE Z.CODCLI = T.CODCLIFOR AND Z.CODDEST = T.NUMDESTDIVERSAMERCI) AND NC.CODDEST = -1) ) 
LEFT OUTER JOIN ZSI_NOTEART NA ON T.CODCLIFOR = NA.CODCLI AND (T.NUMDESTDIVERSAMERCI = NA.CODDEST OR (T.NUMDESTDIVERSAMERCI = 0 AND NC.CODDEST = -1) OR (T.NUMDESTDIVERSAMERCI <> 0 AND NOT EXISTS(SELECT 1 FROM ZSI_NOTECLI Z WHERE Z.CODCLI = T.CODCLIFOR AND Z.CODDEST = T.NUMDESTDIVERSAMERCI) AND NC.CODDEST = -1) ) AND R.CODART = NA.CODART 
LEFT OUTER JOIN SPEDIZDOCUMENTI SD ON SD.IDTESTA = t.PROGRESSIVO
WHERE r.tipodoc IN ('occ', 'oce') and R.TIPORIGA IN ('N','O') AND R.QTAGESTRES > 0 
--AND datediff(d, getdate(), R.DATACONSEGNA)  < 200 
--AND r.codimballo NOT IN (100, 101)
GO

GRANT ALL ON EXCEL_PORTAFOGLIOORDINI TO METODO98
GO

