


DECLARE @CODIMBALLO_D VARCHAR(10)
DECLARE @CODIMBALLO_O VARCHAR(10)
DECLARE @RIFPROGRESSIVO DECIMAL(10)
DECLARE @idriga_O DECIMAL(10)

DECLARE @idriga DECIMAL(10)

DECLARE db_cursor CURSOR FOR  
SELECT T.CODICE, r.COD_IMBALLO, r.RIFPROGRESSIVO, r.IDRIGA -- LEFT(r.COD_IMBALLO, 3) AS c, r.RIFPROGRESSIVO, r.IDRIGA, * 
FROM tabimballi t LEFT OUTER JOIN GESTIONEPREZZIRIGHE r ON LEFT(t.CODICE, 3) = r.COD_IMBALLO
WHERE 
	r.COD_IMBALLO = 208 
	AND len(t.CODICE) > 3
	AND r.RIFPROGRESSIVO IN (SELECT x.progressivo FROM GESTIONEPREZZI x 
		WHERE x.INIZIOVALIDITA = '1990-01-01' AND x.FINEVALIDITA = '1990-01-01')
		AND NOT EXISTS(SELECT 1 FROM GESTIONEPREZZIRIGHE a WHERE a.RIFPROGRESSIVO = r.RIFPROGRESSIVO AND a.COD_IMBALLO = t.CODICE)
	
OPEN db_cursor   
FETCH NEXT FROM db_cursor INTO @CODIMBALLO_D, @CODIMBALLO_O, @RIFPROGRESSIVO, @idriga_O
WHILE @@FETCH_STATUS = 0   
BEGIN  
	PRINT @CODIMBALLO_D
	PRINT @CODIMBALLO_O
	PRINT @RIFPROGRESSIVO
	PRINT @idriga_O

	EXECUTE dbo.NUOVOPROGRESSIVO 'GESTIONEPREZZIRIGHE', 1, @idriga OUT
	
	
	INSERT INTO dbo.GESTIONEPREZZIRIGHE (IDRIGA, RIFPROGRESSIVO, NRLISTINO, UM, QTAMINIMA, PREZZO_MAGG, PREZZO_MAGGEURO, SCONTO_UNICO, SCONTO_AGGIUNTIVO, TIPO, UTENTEMODIFICA, DATAMODIFICA, TP_QTASCONTO, TP_QTACOEFF, COD_IMBALLO, QTA_COLLI)
	--VALUES (@idriga, @rifprogressivo, @nrlistino, @um, @qtaminima, @prezzo_magg, @prezzo_maggeuro, @sconto_unico, @sconto_aggiuntivo, @tipo, @utentemodifica, @datamodifica, @tp_qtasconto, @tp_qtacoeff, @cod_imballo, @qta_colli)
	SELECT @idriga, RIFPROGRESSIVO, NRLISTINO, UM, QTAMINIMA, PREZZO_MAGG, PREZZO_MAGGEURO, SCONTO_UNICO, SCONTO_AGGIUNTIVO, TIPO, UTENTEMODIFICA, DATAMODIFICA, TP_QTASCONTO, TP_QTACOEFF, @CODIMBALLO_D, QTA_COLLI
	FROM GESTIONEPREZZIRIGHE
	WHERE RIFPROGRESSIVO = @RIFPROGRESSIVO AND IDRIGA = @IDRIGA_O

	FETCH NEXT FROM db_cursor INTO @CODIMBALLO_D, @CODIMBALLO_O, @RIFPROGRESSIVO, @idriga_O   
END   

CLOSE db_cursor   
DEALLOCATE db_cursor 


