IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_DOCUMENTI') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_DOCUMENTI
GO

create view EXCEL_EXPORT2CRM_DOCUMENTI as 
SELECT 
	T.CODCLIFOR
		, AC.DSCCONTO1 AS RAGIONESOCIALE
		, (SELECT TOP 1 AA.DSCAGENTE FROM ANAGRAFICAAGENTI AA WHERE AA.CODAGENTE = T.CODAGENTE1) AS AGENTE
        , T.TIPODOC + '/' + CAST(T.ESERCIZIO AS VARCHAR) + '/' + CAST(T.NUMERODOC AS VARCHAR) AS DOCUMENTO -- + '/' + CAST(R.POSIZIONE AS VARCHAR) AS DOCUMENTO 
        , P.DESCRIZIONE AS TIPODOCUMENTO
        , T.NUMRIFDOC
        , T.DATARIFDOC
        , R.CODART AS ARTICOLO
        , R.DESCRIZIONEART AS DESCRIZIONE
 		, I.DESCRIZIONE IMBALLO 
        , CAST(R.QTAGEST AS INT) AS QUANTITA
        , R.UMGEST
        , R.PREZZOUNITLORDOEURO
        , R.SCONTIESTESI
        , (SELECT TOP 1 TRATTAMENTOIVA.DESCRIZIONE FROM TRATTAMENTOIVA WHERE TRATTAMENTOIVA.CODICE =   R.CODIVA) AS IVA
        , R.PREZZOUNITNETTOEURO
        , R.DATACONSEGNA
        , R.TOTLORDORIGAEURO
        , R.TOTNETTORIGAEURO
        , T.ESERCIZIO, T.TIPODOC, T.NUMERODOC, T.BIS, T.DATADOC 
		, R.ANNOTAZIONI
		, (SELECT TOP 1 TABPORTO.DESCRIZIONE FROM TABPORTO WHERE TABPORTO.CODICE = T.PORTO) AS INCOTERM
		, (SELECT TOP 1 TABPAGAMENTI.DESCRIZIONE FROM TABPAGAMENTI WHERE TABPAGAMENTI.CODICE = t.codpagamento) AS DESCRIZIONEPAGAMENTO
		, VS.DATASCADENZA, VS.IMPORTOSCEURO 
        , (CASE WHEN T.RAGSOCDDM IS NULL THEN 
        		AC.DSCCONTO1 + ' ' + AC.INDIRIZZO + ' ' + AC.LOCALITA + ' ' + AC.PROVINCIA 
        	ELSE
        		t.RAGSOCDDM + ' ' + t.INDIRIZZODDM + ' ' + t.LOCALITADDM + ' ' + t.PROVINCIADDM 
        	END) AS DESTINAZIONE
        --, K.IdPubblicazioneKnos AS IDOBJECT
        , T.PROGRESSIVO AS IDTESTA, R.IDRIGA 
        
FROM TESTEDOCUMENTI T WITH (NOLOCK) JOIN EXTRATESTEDOC ET WITH (NOLOCK) ON T.PROGRESSIVO = ET.IDTESTA 
JOIN PARAMETRIDOC P ON P.CODICE = T.TIPODOC
JOIN RIGHEDOCUMENTI R WITH (NOLOCK) ON T.PROGRESSIVO = R.IDTESTA 
JOIN ANAGRAFICACF AC WITH (NOLOCK) ON AC.CODCONTO = T.CODCLIFOR 
--JOIN EXTRACLIENTI WITH (NOLOCK) ON EXTRACLIENTI.CODCONTO = AC.CODCONTO
--JOIN ANAGRAFICAARTICOLI AA WITH (NOLOCK) ON AA.CODICE = R.CODART 
JOIN EXTRARIGHEDOC ER WITH (NOLOCK) ON ER.IDTESTA = R.IDTESTA AND ER.IDRIGA = R.IDRIGA 
LEFT OUTER JOIN VISTASCADENZE VS ON VS.TIPODOC = T.TIPODOC AND VS.ESERCIZIO = T.ESERCIZIO AND VS.NUMDOC = T.NUMERODOC AND VS.BIS = T.BIS
--LEFT OUTER JOIN ZSI_CONFEZSPEDIBILE z WITH (NOLOCK) ON Z.PROGRESSIVO = r.IDTESTA AND z.idriga = r.IDRIGA
LEFT OUTER JOIN TABIMBALLI I WITH (NOLOCK) ON R.CODIMBALLO = I.CODICE 
--LEFT OUTER JOIN ITA_ARCHIVIO_DOCUMENTI K WITH (NOLOCK) ON K.Progressivo = T.PROGRESSIVO
WHERE 
	--t.tipodoc IN ('OCC', 'OCE', 'OCG', 'FTI', 'FTE') AND 
	P.CLIFOR = 'c' AND P.TIPO IN ('f', 'o', 'n') AND
	R.CODART <> '' AND
	R.QTAGESTRES > 0 
	AND t.esercizio >= 2016 
	AND R.CODART IN (SELECT codart FROM EXTRAMAGCRM)
GO

GRANT DELETE ON dbo.EXCEL_EXPORT2CRM_DOCUMENTI TO Metodo98
GO

GRANT INSERT ON dbo.EXCEL_EXPORT2CRM_DOCUMENTI TO Metodo98
GO

GRANT REFERENCES ON dbo.EXCEL_EXPORT2CRM_DOCUMENTI TO Metodo98
GO

GRANT SELECT ON dbo.EXCEL_EXPORT2CRM_DOCUMENTI TO Metodo98
GO

GRANT UPDATE ON dbo.EXCEL_EXPORT2CRM_DOCUMENTI TO Metodo98
GO


SELECT  TOP 10 * FROM EXCEL_EXPORT2CRM_DOCUMENTI

