IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXTRACLIENTI' AND COLUMN_NAME = 'EXPORTCRM')
ALTER TABLE EXTRACLIENTI ADD EXPORTCRM VARCHAR(1)
GO

-- procedure

-- aggiorno il flag sdi esportazione se ci sono documenti da esportare anche se il cliente NO Nè attivo codcategoria = 99
UPDATE EC
SET EC.EXPORTCRM = 'S'
FROM (SELECT DISTINCT CODCLIFOR FROM EXCEL_EXPORT2CRM_DOCUMENTI_CLIENTIORDINI ) E JOIN EXTRACLIENTI EC ON E.CODCLIFOR = EC.CODCONTO
WHERE ISNULL(EC.EXPORTCRM, '') <> 'X'
GO

-------
IF OBJECT_ID ('dbo.ITA_TAB_EXPORTCRM') IS NOT NULL
	DROP TABLE dbo.ITA_TAB_EXPORTCRM
GO

CREATE TABLE dbo.ITA_TAB_EXPORTCRM
	(
	CODICE         VARCHAR (1) NOT NULL,
	DESCRIZIONE    VARCHAR (14) NOT NULL,
	UTENTEMODIFICA VARCHAR (3) NOT NULL,
	DATAMODIFICA   DATETIME NOT NULL,
	PRIMARY KEY (CODICE)
	)
GO

GRANT DELETE ON dbo.ITA_TAB_EXPORTCRM TO Metodo98
GO
GRANT INSERT ON dbo.ITA_TAB_EXPORTCRM TO Metodo98
GO
GRANT REFERENCES ON dbo.ITA_TAB_EXPORTCRM TO Metodo98
GO
GRANT SELECT ON dbo.ITA_TAB_EXPORTCRM TO Metodo98
GO
GRANT UPDATE ON dbo.ITA_TAB_EXPORTCRM TO Metodo98
GO


INSERT INTO dbo.ITA_TAB_EXPORTCRM (CODICE, DESCRIZIONE, UTENTEMODIFICA, DATAMODIFICA)
VALUES ('C', 'DA CONTROLLARE', 'TRM', GETDATE())
GO

INSERT INTO dbo.ITA_TAB_EXPORTCRM (CODICE, DESCRIZIONE, UTENTEMODIFICA, DATAMODIFICA)
VALUES ('N', 'NO', 'TRM', GETDATE())
GO

INSERT INTO dbo.ITA_TAB_EXPORTCRM (CODICE, DESCRIZIONE, UTENTEMODIFICA, DATAMODIFICA)
VALUES ('S', 'SI', 'TRM', GETDATE())
GO

INSERT INTO dbo.ITA_TAB_EXPORTCRM (CODICE, DESCRIZIONE, UTENTEMODIFICA, DATAMODIFICA)
VALUES ('X', 'DA ESCLUDERE', 'TRM',GETDATE())
GO



IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_DOCUMENTI_CLIENTIORDINI') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_DOCUMENTI_CLIENTIORDINI
GO

create view EXCEL_EXPORT2CRM_DOCUMENTI_CLIENTIORDINI as 
SELECT DISTINCT
	T.CODCLIFOR
    , P.DESCRIZIONE AS TIPODOCUMENTO
FROM TESTEDOCUMENTI T WITH (NOLOCK) JOIN PARAMETRIDOC P ON P.CODICE = T.TIPODOC
WHERE 
	P.CLIFOR = 'c' AND P.TIPO =  'o' AND
	t.esercizio >= 2016
GO

GRANT SELECT ON dbo.EXCEL_EXPORT2CRM_DOCUMENTI_CLIENTIORDINI TO Metodo98
GO




IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_CLIENTI') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_CLIENTI
GO

create view EXCEL_EXPORT2CRM_CLIENTI as 

SELECT 
	(CASE WHEN LEFT(DSCCONTO1, 4) = 'ZZZZ' THEN 0 ELSE 1 END) AS STATOANAGRAFICA,
	--a.TIPOCONTO,
	a.CODCONTO AS CODICEAZIENDA,
	a.DSCCONTO1,
	a.DSCCONTO2,
	--a.CODMASTRO,
	a.INDIRIZZO,
	a.CAP,
	a.LOCALITA,
	a.PROVINCIA,
	a.TELEFONO AS TELEFONO_CLI,
	a.FAX AS FAX_CLI,
	a.TELEX AS EMAIL_cliente,
	a.CODFISCALE,
	a.PARTITAIVA,
	--a.CODICEISO,
	replace(replace(a.NOTE, CHAR(13), ''), CHAR(10), '') AS NOTE_CLI,
	a.INDIRIZZOINTERNET
	--a.CODNAZIONE
	, n1.DESCRIZIONE AS DESCR_NAZIONE
	--, r.CODPAG, 
	, p.DESCRIZIONE AS DESCR_PAGAMENTO
	--, R.PORTO, 
	, tp.DESCRIZIONE AS DESCR_PORTO
	, R.CODAGENTE1
	, AA.DSCAGENTE
	--, R.CODSETTORE
	, TS.DESCRIZIONE AS DESCR_SETTORE
	, E.FUNZIONARIO
	, EC.Gruppo, EC.Cosmetica, EC.Household, EC.Industrial_applications
  FROM ANAGRAFICACF a 
JOIN ANAGRAFICARISERVATICF r with (nolock) ON a.CODCONTO = r.CODCONTO 
JOIN EXTRACLIENTI E with (nolock) ON E.CODCONTO = A.CODCONTO
LEFT OUTER JOIN EXTRACLIENTICRM EC with (nolock) ON EC.CODCONTO = A.CODCONTO
LEFT OUTER JOIN TABPORTO tp with (nolock) ON tp.CODICE = r.PORTO
LEFT OUTER JOIN tabnazioni n1 with (nolock) ON n1.CODICE = a.CODNAZIONE
LEFT OUTER JOIN TABPAGAMENTI p with (nolock) ON p.CODICE = r.CODPAG
LEFT OUTER JOIN ANAGRAFICAAGENTI AA with (nolock) ON AA.CODAGENTE = r.CODAGENTE1
LEFT OUTER JOIN TABSETTORI TS with (nolock) ON TS.CODICE = R.CODSETTORE

WHERE a.TIPOCONTO = 'c' AND r.ESERCIZIO = year(getdate())
AND e.EXPORTCRM = 'S'
GO

GRANT SELECT ON dbo.EXCEL_EXPORT2CRM_CLIENTI TO Metodo98
GO






IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_DOCUMENTI_ORDINI') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_DOCUMENTI_ORDINI
GO

create view EXCEL_EXPORT2CRM_DOCUMENTI_ORDINI as 
SELECT 
	T.CODCLIFOR
		, AC.DSCCONTO1 AS RAGIONESOCIALE
		, T.CODAGENTE1
		, (SELECT TOP 1 AA.DSCAGENTE FROM ANAGRAFICAAGENTI AA WHERE AA.CODAGENTE = T.CODAGENTE1) AS AGENTE
        , T.TIPODOC + '/' + CAST(T.ESERCIZIO AS VARCHAR) + '/' + CAST(T.NUMERODOC AS VARCHAR) AS DOCUMENTO -- + '/' + CAST(R.POSIZIONE AS VARCHAR) AS DOCUMENTO 
        , P.DESCRIZIONE AS TIPODOCUMENTO
        , T.NUMRIFDOC
        , T.DATARIFDOC
        , R.CODART AS ARTICOLO
        , R.DESCRIZIONEART AS DESCRIZIONE
 		, I.DESCRIZIONE IMBALLO 
        , CAST(R.QTAGEST AS DECIMAL(10,3)) AS QUANTITA
        , R.UMGEST
        , R.PREZZOUNITLORDOEURO
        , R.SCONTIESTESI
        , (SELECT TOP 1 TRATTAMENTOIVA.DESCRIZIONE FROM TRATTAMENTOIVA WHERE TRATTAMENTOIVA.CODICE =   R.CODIVA) AS IVA
        , R.PREZZOUNITNETTOEURO
        , R.DATACONSEGNA
        , R.TOTLORDORIGAEURO
        , R.TOTNETTORIGAEURO
        , T.ESERCIZIO, T.TIPODOC, T.NUMERODOC, T.BIS, T.DATADOC 
		, R.ANNOTAZIONI
		, (SELECT TOP 1 TABPORTO.DESCRIZIONE FROM TABPORTO WHERE TABPORTO.CODICE = T.PORTO) AS INCOTERM
		, (SELECT TOP 1 TABPAGAMENTI.DESCRIZIONE FROM TABPAGAMENTI WHERE TABPAGAMENTI.CODICE = t.codpagamento) AS DESCRIZIONEPAGAMENTO
		, VS.DATASCADENZA, VS.IMPORTOSCEURO 
        , (CASE WHEN T.RAGSOCDDM IS NULL THEN 
        		AC.DSCCONTO1 + ' ' + AC.INDIRIZZO + ' ' + AC.LOCALITA + ' ' + AC.PROVINCIA 
        	ELSE
        		t.RAGSOCDDM + ' ' + t.INDIRIZZODDM + ' ' + t.LOCALITADDM + ' ' + t.PROVINCIADDM 
        	END) AS DESTINAZIONE
        , K.IdPubblicazioneKnos AS IDOBJECT
        , T.PROGRESSIVO AS IDTESTA, R.IDRIGA 
        , (SELECT TOP 1 1 FROM EXTRAMAGCRM X WHERE X.CODART = R.CODART) AS EXPORTCRM
        , R.IDTESTARP, R.IDRIGARP
        
FROM TESTEDOCUMENTI T WITH (NOLOCK) JOIN EXTRATESTEDOC ET WITH (NOLOCK) ON T.PROGRESSIVO = ET.IDTESTA 
JOIN PARAMETRIDOC P ON P.CODICE = T.TIPODOC
JOIN RIGHEDOCUMENTI R WITH (NOLOCK) ON T.PROGRESSIVO = R.IDTESTA 
JOIN ANAGRAFICACF AC WITH (NOLOCK) ON AC.CODCONTO = T.CODCLIFOR 
--JOIN EXTRACLIENTI WITH (NOLOCK) ON EXTRACLIENTI.CODCONTO = AC.CODCONTO
--JOIN ANAGRAFICAARTICOLI AA WITH (NOLOCK) ON AA.CODICE = R.CODART 
JOIN EXTRARIGHEDOC ER WITH (NOLOCK) ON ER.IDTESTA = R.IDTESTA AND ER.IDRIGA = R.IDRIGA 
LEFT OUTER JOIN VISTASCADENZE VS ON VS.TIPODOC = T.TIPODOC AND VS.ESERCIZIO = T.ESERCIZIO AND VS.NUMDOC = T.NUMERODOC AND VS.BIS = T.BIS
--LEFT OUTER JOIN ZSI_CONFEZSPEDIBILE z WITH (NOLOCK) ON Z.PROGRESSIVO = r.IDTESTA AND z.idriga = r.IDRIGA
LEFT OUTER JOIN TABIMBALLI I WITH (NOLOCK) ON R.CODIMBALLO = I.CODICE 
LEFT OUTER JOIN ITA_ARCHIVIO_DOCUMENTI K ON K.Progressivo = T.PROGRESSIVO
WHERE 
	--t.tipodoc IN ('OCC', 'OCE', 'OCG', 'FTI', 'FTE') AND 
	P.CLIFOR = 'c' AND P.TIPO =  'o' AND
	R.CODART <> '' AND
	--R.QTAGESTRES > 0 	AND 
	t.esercizio >= 2016
	AND t.CODCLIFOR IN (SELECT c.CODICEAZIENDA FROM EXCEL_EXPORT2CRM_CLIENTI c)
GO

GRANT SELECT ON dbo.EXCEL_EXPORT2CRM_DOCUMENTI_ORDINI TO Metodo98
GO


IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_DOCUMENTI_DDT') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_DOCUMENTI_DDT
GO

create view EXCEL_EXPORT2CRM_DOCUMENTI_DDT as 
SELECT 
	T.CODCLIFOR
		, AC.DSCCONTO1 AS RAGIONESOCIALE
		, T.CODAGENTE1
		, (SELECT TOP 1 AA.DSCAGENTE FROM ANAGRAFICAAGENTI AA WHERE AA.CODAGENTE = T.CODAGENTE1) AS AGENTE
        , T.TIPODOC + '/' + CAST(T.ESERCIZIO AS VARCHAR) + '/' + CAST(T.NUMERODOC AS VARCHAR) AS DOCUMENTO -- + '/' + CAST(R.POSIZIONE AS VARCHAR) AS DOCUMENTO 
        , P.DESCRIZIONE AS TIPODOCUMENTO
        , T.NUMRIFDOC
        , T.DATARIFDOC
        , R.CODART AS ARTICOLO
        , R.DESCRIZIONEART AS DESCRIZIONE
 		, I.DESCRIZIONE IMBALLO 
        , CAST(R.QTAGEST AS DECIMAL(10,3))  AS QUANTITA
        , R.UMGEST
        , R.PREZZOUNITLORDOEURO
        , R.SCONTIESTESI
        , (SELECT TOP 1 TRATTAMENTOIVA.DESCRIZIONE FROM TRATTAMENTOIVA WHERE TRATTAMENTOIVA.CODICE =   R.CODIVA) AS IVA
        , R.PREZZOUNITNETTOEURO
        , R.DATACONSEGNA
        , R.TOTLORDORIGAEURO
        , R.TOTNETTORIGAEURO
        , T.ESERCIZIO, T.TIPODOC, T.NUMERODOC, T.BIS, T.DATADOC 
		, R.ANNOTAZIONI
		, (SELECT TOP 1 TABPORTO.DESCRIZIONE FROM TABPORTO WHERE TABPORTO.CODICE = T.PORTO) AS INCOTERM
		, (SELECT TOP 1 TABPAGAMENTI.DESCRIZIONE FROM TABPAGAMENTI WHERE TABPAGAMENTI.CODICE = t.codpagamento) AS DESCRIZIONEPAGAMENTO
		, VS.DATASCADENZA, VS.IMPORTOSCEURO 
        , (CASE WHEN T.RAGSOCDDM IS NULL THEN 
        		AC.DSCCONTO1 + ' ' + AC.INDIRIZZO + ' ' + AC.LOCALITA + ' ' + AC.PROVINCIA 
        	ELSE
        		t.RAGSOCDDM + ' ' + t.INDIRIZZODDM + ' ' + t.LOCALITADDM + ' ' + t.PROVINCIADDM 
        	END) AS DESTINAZIONE
        , K.IdPubblicazioneKnos AS IDOBJECT
        , T.PROGRESSIVO AS IDTESTA, R.IDRIGA 
        , (SELECT TOP 1 1 FROM EXTRAMAGCRM X WHERE X.CODART = R.CODART) AS EXPORTCRM
        , R.IDTESTARP, R.IDRIGARP
        
FROM TESTEDOCUMENTI T WITH (NOLOCK) JOIN EXTRATESTEDOC ET WITH (NOLOCK) ON T.PROGRESSIVO = ET.IDTESTA 
JOIN PARAMETRIDOC P ON P.CODICE = T.TIPODOC
JOIN RIGHEDOCUMENTI R WITH (NOLOCK) ON T.PROGRESSIVO = R.IDTESTA 
JOIN ANAGRAFICACF AC WITH (NOLOCK) ON AC.CODCONTO = T.CODCLIFOR 
--JOIN EXTRACLIENTI WITH (NOLOCK) ON EXTRACLIENTI.CODCONTO = AC.CODCONTO
--JOIN ANAGRAFICAARTICOLI AA WITH (NOLOCK) ON AA.CODICE = R.CODART 
JOIN EXTRARIGHEDOC ER WITH (NOLOCK) ON ER.IDTESTA = R.IDTESTA AND ER.IDRIGA = R.IDRIGA 
LEFT OUTER JOIN VISTASCADENZE VS ON VS.TIPODOC = T.TIPODOC AND VS.ESERCIZIO = T.ESERCIZIO AND VS.NUMDOC = T.NUMERODOC AND VS.BIS = T.BIS
--LEFT OUTER JOIN ZSI_CONFEZSPEDIBILE z WITH (NOLOCK) ON Z.PROGRESSIVO = r.IDTESTA AND z.idriga = r.IDRIGA
LEFT OUTER JOIN TABIMBALLI I WITH (NOLOCK) ON R.CODIMBALLO = I.CODICE 
LEFT OUTER JOIN ITA_ARCHIVIO_DOCUMENTI K ON K.Progressivo = T.PROGRESSIVO
WHERE 
	--t.tipodoc IN ('OCC', 'OCE', 'OCG', 'FTI', 'FTE') AND 
	P.CLIFOR = 'C' AND P.TIPO =  'B' AND
	R.CODART <> '' AND
	--R.QTAGESTRES > 0 	AND 
	t.esercizio >= 2016
	AND t.CODCLIFOR IN (SELECT c.CODICEAZIENDA FROM EXCEL_EXPORT2CRM_CLIENTI c)
GO

GRANT SELECT ON dbo.EXCEL_EXPORT2CRM_DOCUMENTI_DDT TO Metodo98
GO

IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE
GO

create view EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE as 
SELECT 
	T.CODCLIFOR
		, AC.DSCCONTO1 AS RAGIONESOCIALE
		, T.CODAGENTE1
		, (SELECT TOP 1 AA.DSCAGENTE FROM ANAGRAFICAAGENTI AA WHERE AA.CODAGENTE = T.CODAGENTE1) AS AGENTE
        , T.TIPODOC + '/' + CAST(T.ESERCIZIO AS VARCHAR) + '/' + CAST(T.NUMERODOC AS VARCHAR) AS DOCUMENTO -- + '/' + CAST(R.POSIZIONE AS VARCHAR) AS DOCUMENTO 
        , P.DESCRIZIONE AS TIPODOCUMENTO
        , T.NUMRIFDOC
        , T.DATARIFDOC
        , R.CODART AS ARTICOLO
        , R.DESCRIZIONEART AS DESCRIZIONE
 		, I.DESCRIZIONE IMBALLO 
        , CAST(R.QTAGEST AS DECIMAL(10,3))  AS QUANTITA
        , R.UMGEST
        , R.PREZZOUNITLORDOEURO
        , R.SCONTIESTESI
        , (SELECT TOP 1 TRATTAMENTOIVA.DESCRIZIONE FROM TRATTAMENTOIVA WHERE TRATTAMENTOIVA.CODICE =   R.CODIVA) AS IVA
        , R.PREZZOUNITNETTOEURO
        , R.DATACONSEGNA
        , R.TOTLORDORIGAEURO
        , R.TOTNETTORIGAEURO
        , T.ESERCIZIO, T.TIPODOC, T.NUMERODOC, T.BIS, T.DATADOC 
		, R.ANNOTAZIONI
		, (SELECT TOP 1 TABPORTO.DESCRIZIONE FROM TABPORTO WHERE TABPORTO.CODICE = T.PORTO) AS INCOTERM
		, (SELECT TOP 1 TABPAGAMENTI.DESCRIZIONE FROM TABPAGAMENTI WHERE TABPAGAMENTI.CODICE = t.codpagamento) AS DESCRIZIONEPAGAMENTO
		, VS.DATASCADENZA, VS.IMPORTOSCEURO 
        , (CASE WHEN T.RAGSOCDDM IS NULL THEN 
        		AC.DSCCONTO1 + ' ' + AC.INDIRIZZO + ' ' + AC.LOCALITA + ' ' + AC.PROVINCIA 
        	ELSE
        		t.RAGSOCDDM + ' ' + t.INDIRIZZODDM + ' ' + t.LOCALITADDM + ' ' + t.PROVINCIADDM 
        	END) AS DESTINAZIONE
        , K.IdPubblicazioneKnos AS IDOBJECT
        , T.PROGRESSIVO AS IDTESTA, R.IDRIGA 
        , (SELECT TOP 1 1 FROM EXTRAMAGCRM X WHERE X.CODART = R.CODART) AS EXPORTCRM
        , R.IDTESTARP, R.IDRIGARP

FROM TESTEDOCUMENTI T WITH (NOLOCK) JOIN EXTRATESTEDOC ET WITH (NOLOCK) ON T.PROGRESSIVO = ET.IDTESTA 
JOIN PARAMETRIDOC P ON P.CODICE = T.TIPODOC
JOIN RIGHEDOCUMENTI R WITH (NOLOCK) ON T.PROGRESSIVO = R.IDTESTA 
JOIN ANAGRAFICACF AC WITH (NOLOCK) ON AC.CODCONTO = T.CODCLIFOR 
--JOIN EXTRACLIENTI WITH (NOLOCK) ON EXTRACLIENTI.CODCONTO = AC.CODCONTO
--JOIN ANAGRAFICAARTICOLI AA WITH (NOLOCK) ON AA.CODICE = R.CODART 
JOIN EXTRARIGHEDOC ER WITH (NOLOCK) ON ER.IDTESTA = R.IDTESTA AND ER.IDRIGA = R.IDRIGA 
LEFT OUTER JOIN VISTASCADENZE VS ON VS.TIPODOC = T.TIPODOC AND VS.ESERCIZIO = T.ESERCIZIO AND VS.NUMDOC = T.NUMERODOC AND VS.BIS = T.BIS
--LEFT OUTER JOIN ZSI_CONFEZSPEDIBILE z WITH (NOLOCK) ON Z.PROGRESSIVO = r.IDTESTA AND z.idriga = r.IDRIGA
LEFT OUTER JOIN TABIMBALLI I WITH (NOLOCK) ON R.CODIMBALLO = I.CODICE 
LEFT OUTER JOIN ITA_ARCHIVIO_DOCUMENTI K ON K.Progressivo = T.PROGRESSIVO
WHERE 
	--t.tipodoc IN ('OCC', 'OCE', 'OCG', 'FTI', 'FTE') AND 
	P.CLIFOR = 'c' AND P.TIPO IN ('F', 'N') AND
	R.CODART <> '' AND
	R.QTAGESTRES > 0 
	AND t.esercizio >= 2016
	AND isnull(VS.NUMSCAD, 1) = 1
	AND t.CODCLIFOR IN (SELECT c.CODICEAZIENDA FROM EXCEL_EXPORT2CRM_CLIENTI c)
GO

GRANT SELECT ON dbo.EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE TO Metodo98
GO

