

/*
SELECT * FROM TABGRUPPI ORDER BY DATAMODIFICA DESC
SELECT * FROM TABCATEGORIESTAT ORDER BY DATAMODIFICA DESC


IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_ARTICOLI') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_ARTICOLI
GO

create view EXCEL_EXPORT2CRM_ARTICOLI as 
SELECT 
	AA.CODICE
	, AA.DESCRIZIONE
	, AA.NRPEZZIIMBALLO
--	, (SELECT TOP 1 I.DESCRIZIONE FROM TABIMBALLI I WHERE I.CODICE = AA.RIFERIMIMBALLO) AS RIFERIMENTOIMBALLO
	, AA.NOMENCLCOMBINATA1
	, (CASE WHEN AP.PROVENIENZA = 2 THEN 'CONTO LAVORO'
		WHEN AP.PROVENIENZA = 1 THEN 'PRODUZIONE'
		ELSE 'ACQUISTO'
		END) AS PROVENIENZA
	, EMC.GRUPPO
	, EMC.NATURA
	, EMC.CATEGORIASTAT
	, EMC.FAMIGLIA
	, EMC.CONCENTRAZIONE
	, EMC.SPECIALITIES
	, EMC.ECOCERT
	, EMC.COSMOS
	, EMC.SOLUZIONI
	, EMC.SOLUZIONIA
	, EMC.SOLUZIONIB
	, EMC.SOLUZIONIC
	--, 9 AS I
FROM ANAGRAFICAARTICOLI AA WITH (NOLOCK) JOIN ANAGRAFICAARTICOLIPROD AP WITH (NOLOCK) ON AP.CODICEART = AA.CODICE 
JOIN EXTRAMAGCRM EMC WITH (NOLOCK) ON EMC.CODART = AA.CODICE
WHERE AP.ESERCIZIO = YEAR(GETDATE())
GO

*/



IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_ARTICOLI') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_ARTICOLI
GO

create view EXCEL_EXPORT2CRM_ARTICOLI as 
/*
SELECT 
	'CODICE' AS CODICE,
	'DESCRIZIONE' AS DESCRIZIONE,
	'NRPEZZIIMBALLO' AS NRPEZZIIMBALLO,
	'NOMENCLCOMBINATA1' AS NOMENCLCOMBINATA1,
	'PROVENIENZA' AS PROVENIENZA,
	'GRUPPO' AS GRUPPO,
	'NATURA' AS NATURA,
	'CATEGORIASTAT' AS CATEGORIASTAT,
	'FAMIGLIA' AS FAMIGLIA,
	'CONCENTRAZIONE' AS CONCENTRAZIONE,
	'SPECIALITIES' AS SPECIALITIES,
	'ECOCERT' AS ECOCERT,
	'COSMOS' AS COSMOS,
	0 AS I
UNION
*/
SELECT 
	AA.CODICE
	, AA.DESCRIZIONE
	, AA.NRPEZZIIMBALLO
--	, (SELECT TOP 1 I.DESCRIZIONE FROM TABIMBALLI I WHERE I.CODICE = AA.RIFERIMIMBALLO) AS RIFERIMENTOIMBALLO
	, AA.NOMENCLCOMBINATA1
	, (CASE WHEN AP.PROVENIENZA = 2 THEN 'CONTO LAVORO'
		WHEN AP.PROVENIENZA = 1 THEN 'PRODUZIONE'
		ELSE 'ACQUISTO'
		END) AS PROVENIENZA
	, (SELECT TOP 1 TABGRUPPI.DESCRIZIONE FROM TABGRUPPI WHERE TABGRUPPI.CODICE = aa.gruppo) AS GRUPPO
	, EMC.NATURA
	, (SELECT TOP 1 TABCATEGORIESTAT.DESCRIZIONE FROM TABCATEGORIESTAT WHERE TABCATEGORIESTAT.CODICE = aa.CODCATEGORIASTAT) AS CATEGORIASTAT
	, EMC.FAMIGLIA
	, EMC.CONCENTRAZIONE
	, EMC.SPECIALITIES
	, EMC.ECOCERT
	, EMC.COSMOS
	, EMC.SOLUZIONI
	, EMC.SOLUZIONIA
	, EMC.SOLUZIONIB
	, EMC.SOLUZIONIC
	, EMC.GRUPPO AS GRUPPOCRM, VTE.GruppoCRM AS GRUPPOVTE
	, EMC.CATEGORIASTAT AS CATEGORIASTATCRM, VTE.CategoriaIstatCRM AS CATEGORIASTATVTE
	--, 9 AS I
FROM ANAGRAFICAARTICOLI AA WITH (NOLOCK) JOIN ANAGRAFICAARTICOLIPROD AP WITH (NOLOCK) ON AP.CODICEART = AA.CODICE 
JOIN EXTRAMAGCRM EMC WITH (NOLOCK) ON EMC.CODART = AA.CODICE
JOIN VTECRM_EXTRAARTICOLI VTE  ON VTE.CODICE= AA.CODICE
WHERE AP.ESERCIZIO = YEAR(GETDATE())
GO

GRANT SELECT ON dbo.EXCEL_EXPORT2CRM_ARTICOLI TO Metodo98
GO

SELECT CODICE, DESCRIZIONE, NRPEZZIIMBALLO, NOMENCLCOMBINATA1, PROVENIENZA
, GRUPPO, GRUPPOCRM, GRUPPOVTE
, NATURA
, CATEGORIASTAT, CATEGORIASTATCRM, CATEGORIASTATVTE
, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS, SOLUZIONI, SOLUZIONIA, SOLUZIONIB, SOLUZIONIC
FROM dbo.EXCEL_EXPORT2CRM_ARTICOLI
WHERE (GRUPPO <> gruppoVTE  COLLATE Latin1_General_CI_AS OR CATEGORIASTAT <> categoriastatVTE COLLATE Latin1_General_CI_AS)








IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_CLIENTI') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_CLIENTI
GO

create view EXCEL_EXPORT2CRM_CLIENTI as 

SELECT 
	(CASE WHEN LEFT(DSCCONTO1, 4) = 'ZZZZ' THEN 0 ELSE 1 END) AS STATOANAGRAFICA,
	--a.TIPOCONTO,
	a.CODCONTO AS CODICEAZIENDA,
	a.DSCCONTO1,
	a.DSCCONTO2,
	--a.CODMASTRO,
	a.INDIRIZZO,
	a.CAP,
	a.LOCALITA,
	a.PROVINCIA,
	a.TELEFONO AS TELEFONO_CLI,
	a.FAX AS FAX_CLI,
	a.TELEX AS EMAIL_cliente,
	a.CODFISCALE,
	a.PARTITAIVA,
	--a.CODICEISO,
	replace(replace(a.NOTE, CHAR(13), ''), CHAR(10), '') AS NOTE_CLI,
	a.INDIRIZZOINTERNET
	--a.CODNAZIONE
	, n1.DESCRIZIONE AS DESCR_NAZIONE
	--, r.CODPAG, 
	, p.DESCRIZIONE AS DESCR_PAGAMENTO
	--, R.PORTO, 
	, tp.DESCRIZIONE AS DESCR_PORTO
	, R.CODAGENTE1
	, AA.DSCAGENTE
	--, R.CODSETTORE
	, TS.DESCRIZIONE AS DESCR_SETTORE
	, E.FUNZIONARIO
	, EC.Gruppo, EC.Cosmetica, EC.Household, EC.Industrial_applications
	, VTE.FunzionarioCRM
	, VTE.SettoreCRM
  FROM ANAGRAFICACF a 
JOIN ANAGRAFICARISERVATICF r with (nolock) ON a.CODCONTO = r.CODCONTO 
JOIN EXTRACLIENTI E with (nolock) ON E.CODCONTO = A.CODCONTO
LEFT OUTER JOIN VTECRM_EXTRACLIENTI VTE  ON VTE.CODCONTO = A.CODCONTO
LEFT OUTER JOIN EXTRACLIENTICRM EC with (nolock) ON EC.CODCONTO = A.CODCONTO
LEFT OUTER JOIN TABPORTO tp with (nolock) ON tp.CODICE = r.PORTO
LEFT OUTER JOIN tabnazioni n1 with (nolock) ON n1.CODICE = a.CODNAZIONE
LEFT OUTER JOIN TABPAGAMENTI p with (nolock) ON p.CODICE = r.CODPAG
LEFT OUTER JOIN ANAGRAFICAAGENTI AA with (nolock) ON AA.CODAGENTE = r.CODAGENTE1
LEFT OUTER JOIN TABSETTORI TS with (nolock) ON TS.CODICE = R.CODSETTORE

WHERE a.TIPOCONTO = 'c' AND r.ESERCIZIO = year(getdate())
AND e.EXPORTCRM = 'S'
GO

GRANT SELECT ON dbo.EXCEL_EXPORT2CRM_CLIENTI TO Metodo98
GO

SELECT 
	STATOANAGRAFICA,
	CODICEAZIENDA,
	DSCCONTO1,
	CODAGENTE1,
	DSCAGENTE,
	DESCR_SETTORE,
	SettoreCRM,
	FUNZIONARIO,
	FunzionarioCRM,
	Gruppo,
	Cosmetica,
	Household,
	Industrial_applications
FROM dbo.EXCEL_EXPORT2CRM_CLIENTI
WHERE DESCR_SETTORE  <> SettoreCRM  COLLATE Latin1_General_CI_AS
