ALTER TABLE EXTRAMAGCRM ADD SOLUZIONI SMALLINT DEFAULT 0
GO

delete FROM EXTRAMAGCRM WHERE CODART in ('20297#000XXX',
'20226#000XXX',
'20230#000XXX',
'20232#000XXX',
'20523#000XXX',
'25503#000XXX',
'20065#000XXX',
'20207#240XXX',
'11251',
'11272',
'43056',
'20007#000XXX',
'20234#000XXX',
'32125',
'43036',
'43076',
'43160',
'32665',
'20522#071XXX',
'32315',
'43410',
'43412',
'20505#010XXX',
'20300#264XXX',
'20300#243XXX',
'20194#243XXX',
'20259#000XXX',
'25355#015XXX',
'25385#095XXX')


INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20297#000XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'MI MISCELE',  'Compound',  '',  1,  0, 0, 1)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20226#000XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'MI MISCELE',  'Compound',  '',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20230#000XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'MI MISCELE',  'Compound',  '',  1,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20232#000XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'MI MISCELE',  'Compound',  '',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20523#000XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'MI MISCELE',  'Compound',  '',  1,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '25503#000XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'AN ANIONICI',  'Faes',  '0,7',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20065#000XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'AF ANFOTERI',  'Ossido di ammina',  '',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20207#240XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'AN ANIONICI',  'Sarcosinati',  '',  1,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '11251', 'CRM', GETDATE(),  'RIVENDITA',  'RIVENDITA PURA',  'OCCASIONALI',  'Varie',  '',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '11272', 'CRM', GETDATE(),  'RIVENDITA',  'MP MATERIE PRIME',  'NI NON IONICI',  'Alcoli',  '',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '43056', 'CRM', GETDATE(),  'RIVENDITA',  'MP MATERIE PRIME',  'NI NON IONICI',  'Alcoli',  '',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20007#000XXX', 'CRM', GETDATE(),  'RIVENDITA',  'RIVENDITA PURA',  'OCCASIONALI',  'Varie',  '',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20234#000XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'MI MISCELE',  'Compound',  '',  1,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '32125', 'CRM', GETDATE(),  'RIVENDITA',  'INTERCOMPANY',  'MI MISCELE',  'Compound',  '',  1,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '43036', 'CRM', GETDATE(),  'RIVENDITA',  'RIVENDITA PURA',  'OCCASIONALI',  'Varie',  '',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '43076', 'CRM', GETDATE(),  'RIVENDITA',  'RIVENDITA PURA',  'NI NON IONICI',  'Polimero',  '',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '43160', 'CRM', GETDATE(),  'RIVENDITA',  'RIVENDITA PURA',  'OCCASIONALI',  'Varie',  '',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '32665', 'CRM', GETDATE(),  'RIVENDITA',  'INTERCOMPANY',  'AN ANIONICI',  'Faes',  '0,5',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20522#071XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'AN ANIONICI',  'Faes',  '0,27',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '32315', 'CRM', GETDATE(),  'RIVENDITA',  'INTERCOMPANY',  'ES ESTERI',  'Esteri Vari',  '',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '43410', 'CRM', GETDATE(),  'RIVENDITA',  'RIVENDITA PURA',  'AT ATTIVI',  'Attivo',  '',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '43412', 'CRM', GETDATE(),  'RIVENDITA',  'RIVENDITA PURA',  'AT ATTIVI',  'Attivo',  '',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20505#010XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'AN ANIONICI',  'Faes',  '0,27',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20300#264XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'AN ANIONICI',  'Solfosuccinati',  '',  1,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20300#243XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'AN ANIONICI',  'Solfosuccinati',  '',  1,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20194#243XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'AN ANIONICI',  'Saponi',  '',  0,  1, 1, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '20259#000XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'AN ANIONICI',  'Glutammati',  '',  1,  1, 1, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '25355#015XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'AN ANIONICI',  'Fas',  '0,27',  0,  0, 0, 0)
INSERT INTO EXTRAMAGCRM ( CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS,SOLUZIONI) VALUES  ( '25385#095XXX', 'CRM', GETDATE(),  'PP PRODUZIONE PROPRIA',  'PP PRODUZIONE PROPRIA',  'AN ANIONICI',  'Fas',  '0,27',  0,  0, 0, 0)

IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_ARTICOLI') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_ARTICOLI
GO

create view EXCEL_EXPORT2CRM_ARTICOLI as 
/*
SELECT 
	'CODICE' AS CODICE,
	'DESCRIZIONE' AS DESCRIZIONE,
	'NRPEZZIIMBALLO' AS NRPEZZIIMBALLO,
	'NOMENCLCOMBINATA1' AS NOMENCLCOMBINATA1,
	'PROVENIENZA' AS PROVENIENZA,
	'GRUPPO' AS GRUPPO,
	'NATURA' AS NATURA,
	'CATEGORIASTAT' AS CATEGORIASTAT,
	'FAMIGLIA' AS FAMIGLIA,
	'CONCENTRAZIONE' AS CONCENTRAZIONE,
	'SPECIALITIES' AS SPECIALITIES,
	'ECOCERT' AS ECOCERT,
	'COSMOS' AS COSMOS,
	0 AS I
UNION
*/
SELECT 
	AA.CODICE
	, AA.DESCRIZIONE
	, AA.NRPEZZIIMBALLO
--	, (SELECT TOP 1 I.DESCRIZIONE FROM TABIMBALLI I WHERE I.CODICE = AA.RIFERIMIMBALLO) AS RIFERIMENTOIMBALLO
	, AA.NOMENCLCOMBINATA1
	, (CASE WHEN AP.PROVENIENZA = 2 THEN 'CONTO LAVORO'
		WHEN AP.PROVENIENZA = 1 THEN 'PRODUZIONE'
		ELSE 'ACQUISTO'
		END) AS PROVENIENZA
	, EMC.GRUPPO
	, EMC.NATURA
	, EMC.CATEGORIASTAT
	, EMC.FAMIGLIA
	, EMC.CONCENTRAZIONE
	, EMC.SPECIALITIES
	, EMC.ECOCERT
	, EMC.COSMOS
	, EMC.SOLUZIONI
	--, 9 AS I
FROM ANAGRAFICAARTICOLI AA WITH (NOLOCK) JOIN ANAGRAFICAARTICOLIPROD AP WITH (NOLOCK) ON AP.CODICEART = AA.CODICE 
JOIN EXTRAMAGCRM EMC WITH (NOLOCK) ON EMC.CODART = AA.CODICE
WHERE AP.ESERCIZIO = YEAR(GETDATE())
GO



UPDATE dbo.EXCEL_EXPORT2CRM_ARTICOLI
SET SOLUZIONI = 0
WHERE SOLUZIONI IS NULL
GO



SELECT 
	CODICE,
	DESCRIZIONE,
	NRPEZZIIMBALLO,
	NOMENCLCOMBINATA1,
	PROVENIENZA,
	GRUPPO,
	NATURA,
	CATEGORIASTAT,
	FAMIGLIA,
	CONCENTRAZIONE,
	SPECIALITIES,
	ECOCERT,
	COSMOS,
	SOLUZIONI
FROM dbo.EXCEL_EXPORT2CRM_ARTICOLI
WHERE CODICE  in ('20297#000XXX',
'20226#000XXX',
'20230#000XXX',
'20232#000XXX',
'20523#000XXX',
'25503#000XXX',
'20065#000XXX',
'20207#240XXX',
'11251',
'11272',
'43056',
'20007#000XXX',
'20234#000XXX',
'32125',
'43036',
'43076',
'43160',
'32665',
'20522#071XXX',
'32315',
'43410',
'43412',
'20505#010XXX',
'20300#264XXX',
'20300#243XXX',
'20194#243XXX',
'20259#000XXX',
'25355#015XXX',
'25385#095XXX')