IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE_SCADENZE') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE_SCADENZE
GO

create view EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE_SCADENZE as 
SELECT 
	T.CODCLIFOR
        , T.TIPODOC + '/' + CAST(T.ESERCIZIO AS VARCHAR) + '/' + CAST(T.NUMERODOC AS VARCHAR) AS DOCUMENTO -- + '/' + CAST(R.POSIZIONE AS VARCHAR) AS DOCUMENTO 
        , P.DESCRIZIONE AS TIPODOCUMENTO
        , T.ESERCIZIO, T.TIPODOC, T.NUMERODOC, T.BIS, T.DATADOC 
		, VS.DATASCADENZA, VS.IMPORTOSCEURO 
		, vs.ESITO
		, (CASE WHEN vs.ESITO = 0 THEN 'NON EMESSO'
			WHEN VS.ESITO = 1 THEN 'EMESSO'
			WHEN VS.ESITO = 2 THEN 'PAGATO'
			WHEN VS.ESITO = 3 THEN 'INSOLUTO'
			WHEN VS.ESITO = 4 THEN 'INSOLUTO PAGATO'
			ELSE '' END) AS DSCESITO
		, VS.DATAPAGEFF
		, t.PROGRESSIVO AS IDTESTA
FROM TESTEDOCUMENTI T WITH (NOLOCK) 
JOIN PARAMETRIDOC P WITH (NOLOCK) ON P.CODICE = T.TIPODOC
INNER JOIN VISTASCADENZE VS WITH (NOLOCK) ON VS.TIPODOC = T.TIPODOC AND VS.ESERCIZIO = T.ESERCIZIO AND VS.NUMDOC = T.NUMERODOC AND VS.BIS = T.BIS
WHERE 
	--t.tipodoc IN ('OCC', 'OCE', 'OCG', 'FTI', 'FTE') AND 
	P.CLIFOR = 'c' AND P.TIPO IN ('F', 'N') 
	AND t.esercizio >= 2016
GO

GRANT SELECT ON dbo.EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE_SCADENZE TO Metodo98
GO

