IF OBJECT_ID ('dbo.EXPORT2CRM_LOG') IS NOT NULL
	DROP TABLE dbo.EXPORT2CRM_LOG
GO

CREATE TABLE dbo.EXPORT2CRM_LOG
	(
	ID             INT IDENTITY NOT NULL,
	PROCEDURA       VARCHAR (2000) NOT NULL,
	ESITO     VARCHAR (200),
	datamodifica   DATETIME
	)
GO

GRANT ALL ON EXPORT2CRM_LOG TO METODO98
GO





IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_CLIENTI') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_CLIENTI
GO

create view EXCEL_EXPORT2CRM_CLIENTI as 

SELECT 
	(CASE WHEN LEFT(DSCCONTO1, 4) = 'ZZZZ' THEN 0 ELSE 1 END) AS STATOANAGRAFICA,
	--a.TIPOCONTO,
	a.CODCONTO AS CODICEAZIENDA,
	a.DSCCONTO1,
	a.DSCCONTO2,
	--a.CODMASTRO,
	a.INDIRIZZO,
	a.CAP,
	a.LOCALITA,
	a.PROVINCIA,
	a.TELEFONO AS TELEFONO_CLI,
	a.FAX AS FAX_CLI,
	a.TELEX AS EMAIL_cliente,
	a.CODFISCALE,
	a.PARTITAIVA,
	--a.CODICEISO,
	a.NOTE AS NOTE_CLI,
	a.INDIRIZZOINTERNET
	--a.CODNAZIONE
	, n1.DESCRIZIONE AS DESCR_NAZIONE
	--, r.CODPAG, 
	, p.DESCRIZIONE AS DESCR_PAGAMENTO
	--, R.PORTO, 
	, tp.DESCRIZIONE AS DESCR_PORTO
	, R.CODAGENTE1
	, AA.DSCAGENTE
	--, R.CODSETTORE
	, TS.DESCRIZIONE AS DESCR_SETTORE
	, E.FUNZIONARIO
	, EC.Gruppo, EC.Cosmetica, EC.Household, EC.Industrial_applications
	--, a.datamodifica
  FROM ANAGRAFICACF a 
JOIN ANAGRAFICARISERVATICF r with (nolock) ON a.CODCONTO = r.CODCONTO 
JOIN EXTRACLIENTI E with (nolock) ON E.CODCONTO = A.CODCONTO
JOIN EXTRACLIENTICRM EC with (nolock) ON EC.CODCONTO = A.CODCONTO
LEFT OUTER JOIN TABPORTO tp with (nolock) ON tp.CODICE = r.PORTO
LEFT OUTER JOIN tabnazioni n1 with (nolock) ON n1.CODICE = a.CODNAZIONE
LEFT OUTER JOIN TABPAGAMENTI p with (nolock) ON p.CODICE = r.CODPAG
LEFT OUTER JOIN ANAGRAFICAAGENTI AA with (nolock) ON AA.CODAGENTE = r.CODAGENTE1
LEFT OUTER JOIN TABSETTORI TS with (nolock) ON TS.CODICE = R.CODSETTORE

WHERE a.TIPOCONTO = 'c' AND r.ESERCIZIO = year(getdate())
-- AND DATEDIFF(hh, A.DATAMODIFICA, (SELECT TOP 1 DATAMODIFICA FROM EXPORT2CRM_LOG ORDER BY datamodifica DESC)) < 24
GO


GRANT SELECT ON EXCEL_EXPORT2CRM_CLIENTI TO metodo98
GO


IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_CONTATTICLIENTI') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_CONTATTICLIENTI
GO

create view EXCEL_EXPORT2CRM_CONTATTICLIENTI as 

SELECT 
	--a.TIPOCONTO,
	t.RIFCODCONTO AS CODICEAZIENDA
	, T.CODICE
	, T.COGNOME
	, T.TELEFONO
	, T.CELL
	, T.EMAIL
	, tr.DESCRIZIONE AS RUOLOCONTATTO
  FROM ANAGRAFICACF a 
LEFT OUTER JOIN TABELLAPERSONALE t with (nolock) ON a.CODCONTO = t.RIFCODCONTO
LEFT OUTER JOIN TabellaRuoli Tr with (nolock) ON TR.CODICE = t.CODRUOLO

WHERE a.TIPOCONTO = 'c'
-- AND DATEDIFF(hh, t.DATAMODIFICA, (SELECT TOP 1 DATAMODIFICA FROM EXPORT2CRM_LOG ORDER BY datamodifica DESC)) < 24

GO


GRANT SELECT ON EXCEL_EXPORT2CRM_CONTATTICLIENTI TO metodo98
GO


IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_AGENTI') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_AGENTI
GO

CREATE  VIEW EXCEL_EXPORT2CRM_AGENTI AS
SELECT AA.CODagente, AA.DscAgente, AA.PartitaIVA, AA.CodFiscale, AA.TELEX EMAIL, AE.PASSWORD  FROM 
Anagraficaagenti AA LEFT OUTER JOIN AGENTI_ECOM AE ON AA.CODagente = AE.CODagente
WHERE
--	 DATEDIFF(hh, Aa.DATAMODIFICA, (SELECT TOP 1 DATAMODIFICA FROM EXPORT2CRM_LOG ORDER BY datamodifica DESC)) < 24

GO


GRANT SELECT ON EXCEL_EXPORT2CRM_AGENTI TO metodo98
GO



IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE
GO

create view EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE as 
SELECT 
	T.CODCLIFOR
		, AC.DSCCONTO1 AS RAGIONESOCIALE
		, T.CODAGENTE1
		, (SELECT TOP 1 AA.DSCAGENTE FROM ANAGRAFICAAGENTI AA WHERE AA.CODAGENTE = T.CODAGENTE1) AS AGENTE
        , T.TIPODOC + '/' + CAST(T.ESERCIZIO AS VARCHAR) + '/' + CAST(T.NUMERODOC AS VARCHAR) AS DOCUMENTO -- + '/' + CAST(R.POSIZIONE AS VARCHAR) AS DOCUMENTO 
        , P.DESCRIZIONE AS TIPODOCUMENTO
        , T.NUMRIFDOC
        , T.DATARIFDOC
        , R.CODART AS ARTICOLO
        , R.DESCRIZIONEART AS DESCRIZIONE
 		, I.DESCRIZIONE IMBALLO 
        , CAST(R.QTAGEST AS INT) AS QUANTITA
        , R.UMGEST
        , R.PREZZOUNITLORDOEURO
        , R.SCONTIESTESI
        , (SELECT TOP 1 TRATTAMENTOIVA.DESCRIZIONE FROM TRATTAMENTOIVA WHERE TRATTAMENTOIVA.CODICE =   R.CODIVA) AS IVA
        , R.PREZZOUNITNETTOEURO
        , R.DATACONSEGNA
        , R.TOTLORDORIGAEURO
        , R.TOTNETTORIGAEURO
        , T.ESERCIZIO, T.TIPODOC, T.NUMERODOC, T.BIS, T.DATADOC 
		, R.ANNOTAZIONI
		, (SELECT TOP 1 TABPORTO.DESCRIZIONE FROM TABPORTO WHERE TABPORTO.CODICE = T.PORTO) AS INCOTERM
		, (SELECT TOP 1 TABPAGAMENTI.DESCRIZIONE FROM TABPAGAMENTI WHERE TABPAGAMENTI.CODICE = t.codpagamento) AS DESCRIZIONEPAGAMENTO
		, VS.DATASCADENZA, VS.IMPORTOSCEURO 
        , (CASE WHEN T.RAGSOCDDM IS NULL THEN 
        		AC.DSCCONTO1 + ' ' + AC.INDIRIZZO + ' ' + AC.LOCALITA + ' ' + AC.PROVINCIA 
        	ELSE
        		t.RAGSOCDDM + ' ' + t.INDIRIZZODDM + ' ' + t.LOCALITADDM + ' ' + t.PROVINCIADDM 
        	END) AS DESTINAZIONE
        , K.IdPubblicazioneKnos AS IDOBJECT
        , T.PROGRESSIVO AS IDTESTA, R.IDRIGA 
        
FROM TESTEDOCUMENTI T WITH (NOLOCK) JOIN EXTRATESTEDOC ET WITH (NOLOCK) ON T.PROGRESSIVO = ET.IDTESTA 
JOIN PARAMETRIDOC P ON P.CODICE = T.TIPODOC
JOIN RIGHEDOCUMENTI R WITH (NOLOCK) ON T.PROGRESSIVO = R.IDTESTA 
JOIN ANAGRAFICACF AC WITH (NOLOCK) ON AC.CODCONTO = T.CODCLIFOR 
--JOIN EXTRACLIENTI WITH (NOLOCK) ON EXTRACLIENTI.CODCONTO = AC.CODCONTO
--JOIN ANAGRAFICAARTICOLI AA WITH (NOLOCK) ON AA.CODICE = R.CODART 
JOIN EXTRARIGHEDOC ER WITH (NOLOCK) ON ER.IDTESTA = R.IDTESTA AND ER.IDRIGA = R.IDRIGA 
LEFT OUTER JOIN VISTASCADENZE VS ON VS.TIPODOC = T.TIPODOC AND VS.ESERCIZIO = T.ESERCIZIO AND VS.NUMDOC = T.NUMERODOC AND VS.BIS = T.BIS
--LEFT OUTER JOIN ZSI_CONFEZSPEDIBILE z WITH (NOLOCK) ON Z.PROGRESSIVO = r.IDTESTA AND z.idriga = r.IDRIGA
LEFT OUTER JOIN TABIMBALLI I WITH (NOLOCK) ON R.CODIMBALLO = I.CODICE 
LEFT OUTER JOIN ITA_ARCHIVIO_DOCUMENTI K ON K.Progressivo = T.PROGRESSIVO
WHERE 
	--t.tipodoc IN ('OCC', 'OCE', 'OCG', 'FTI', 'FTE') AND 
	P.CLIFOR = 'c' AND P.TIPO IN ('F', 'N') AND
	R.CODART <> '' AND
	R.QTAGESTRES > 0 
	AND t.esercizio >= 2016
 	--AND DATEDIFF(hh, r.DATAMODIFICA, (SELECT TOP 1 DATAMODIFICA FROM EXPORT2CRM_LOG ORDER BY datamodifica DESC)) < 24
GO


GRANT SELECT ON EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE TO metodo98
GO




IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_DOCUMENTI_ORDINI') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_DOCUMENTI_ORDINI
GO

create view EXCEL_EXPORT2CRM_DOCUMENTI_ORDINI as 
SELECT 
	T.CODCLIFOR
		, AC.DSCCONTO1 AS RAGIONESOCIALE
		, T.CODAGENTE1
		, (SELECT TOP 1 AA.DSCAGENTE FROM ANAGRAFICAAGENTI AA WHERE AA.CODAGENTE = T.CODAGENTE1) AS AGENTE
        , T.TIPODOC + '/' + CAST(T.ESERCIZIO AS VARCHAR) + '/' + CAST(T.NUMERODOC AS VARCHAR) AS DOCUMENTO -- + '/' + CAST(R.POSIZIONE AS VARCHAR) AS DOCUMENTO 
        , P.DESCRIZIONE AS TIPODOCUMENTO
        , T.NUMRIFDOC
        , T.DATARIFDOC
        , R.CODART AS ARTICOLO
        , R.DESCRIZIONEART AS DESCRIZIONE
 		, I.DESCRIZIONE IMBALLO 
        , CAST(R.QTAGEST AS INT) AS QUANTITA
        , R.UMGEST
        , R.PREZZOUNITLORDOEURO
        , R.SCONTIESTESI
        , (SELECT TOP 1 TRATTAMENTOIVA.DESCRIZIONE FROM TRATTAMENTOIVA WHERE TRATTAMENTOIVA.CODICE =   R.CODIVA) AS IVA
        , R.PREZZOUNITNETTOEURO
        , R.DATACONSEGNA
        , R.TOTLORDORIGAEURO
        , R.TOTNETTORIGAEURO
        , T.ESERCIZIO, T.TIPODOC, T.NUMERODOC, T.BIS, T.DATADOC 
		, R.ANNOTAZIONI
		, (SELECT TOP 1 TABPORTO.DESCRIZIONE FROM TABPORTO WHERE TABPORTO.CODICE = T.PORTO) AS INCOTERM
		, (SELECT TOP 1 TABPAGAMENTI.DESCRIZIONE FROM TABPAGAMENTI WHERE TABPAGAMENTI.CODICE = t.codpagamento) AS DESCRIZIONEPAGAMENTO
		, VS.DATASCADENZA, VS.IMPORTOSCEURO 
        , (CASE WHEN T.RAGSOCDDM IS NULL THEN 
        		AC.DSCCONTO1 + ' ' + AC.INDIRIZZO + ' ' + AC.LOCALITA + ' ' + AC.PROVINCIA 
        	ELSE
        		t.RAGSOCDDM + ' ' + t.INDIRIZZODDM + ' ' + t.LOCALITADDM + ' ' + t.PROVINCIADDM 
        	END) AS DESTINAZIONE
        , K.IdPubblicazioneKnos AS IDOBJECT
        , T.PROGRESSIVO AS IDTESTA, R.IDRIGA 
        
FROM TESTEDOCUMENTI T WITH (NOLOCK) JOIN EXTRATESTEDOC ET WITH (NOLOCK) ON T.PROGRESSIVO = ET.IDTESTA 
JOIN PARAMETRIDOC P ON P.CODICE = T.TIPODOC
JOIN RIGHEDOCUMENTI R WITH (NOLOCK) ON T.PROGRESSIVO = R.IDTESTA 
JOIN ANAGRAFICACF AC WITH (NOLOCK) ON AC.CODCONTO = T.CODCLIFOR 
--JOIN EXTRACLIENTI WITH (NOLOCK) ON EXTRACLIENTI.CODCONTO = AC.CODCONTO
--JOIN ANAGRAFICAARTICOLI AA WITH (NOLOCK) ON AA.CODICE = R.CODART 
JOIN EXTRARIGHEDOC ER WITH (NOLOCK) ON ER.IDTESTA = R.IDTESTA AND ER.IDRIGA = R.IDRIGA 
LEFT OUTER JOIN VISTASCADENZE VS ON VS.TIPODOC = T.TIPODOC AND VS.ESERCIZIO = T.ESERCIZIO AND VS.NUMDOC = T.NUMERODOC AND VS.BIS = T.BIS
--LEFT OUTER JOIN ZSI_CONFEZSPEDIBILE z WITH (NOLOCK) ON Z.PROGRESSIVO = r.IDTESTA AND z.idriga = r.IDRIGA
LEFT OUTER JOIN TABIMBALLI I WITH (NOLOCK) ON R.CODIMBALLO = I.CODICE 
LEFT OUTER JOIN ITA_ARCHIVIO_DOCUMENTI K ON K.Progressivo = T.PROGRESSIVO
WHERE 
	--t.tipodoc IN ('OCC', 'OCE', 'OCG', 'FTI', 'FTE') AND 
	P.CLIFOR = 'c' AND P.TIPO =  'o' AND
	R.CODART <> '' AND
	R.QTAGESTRES > 0 
	AND t.esercizio >= 2016
	--AND DATEDIFF(hh, r.DATAMODIFICA, (SELECT TOP 1 DATAMODIFICA FROM EXPORT2CRM_LOG ORDER BY datamodifica DESC)) < 24
GO


GRANT SELECT ON EXCEL_EXPORT2CRM_DOCUMENTI_ORDINI TO metodo98
GO






/*
-- To allow advanced options to be changed.
EXEC sp_configure 'show advanced options', 1
GO
-- To update the currently configured value for advanced options.
RECONFIGURE
GO
-- To enable the feature.
EXEC sp_configure 'xp_cmdshell', 1
GO
-- To update the currently configured value for this feature.
RECONFIGURE
GO
*/

/*
DECLARE @procedura AS VARCHAR(2000)
SET @procedura = 'SQLCMD -S . -d ZSI -Q "SELECT * FROM EXCEL_EXPORT2CRM_CLIENTI" -s ";" -o "E:\MET\ITALCOM\CRM\EXPORT\clienti.csv"'
INSERT INTO dbo.EXPORT2CRM_LOG (PROCEDURA, ESITO, datamodifica) VALUES (@procedura,  'START', GETDATE())
EXEC xp_cmdshell @procedura
INSERT INTO dbo.EXPORT2CRM_LOG (PROCEDURA, ESITO, datamodifica) VALUES (@procedura,  'STOP', GETDATE())

EXEC xp_cmdshell 'SQLCMD -S . -d ZSI -Q "SELECT * FROM EXCEL_EXPORT2CRM_CONTATTICLIENTI" -s ";" -o "E:\MET\ITALCOM\CRM\EXPORT\contatticlienti.csv"';
EXEC xp_cmdshell 'SQLCMD -S . -d ZSI -Q "SELECT * FROM EXCEL_EXPORT2CRM_AGENTI" -s ";" -o "E:\MET\ITALCOM\CRM\EXPORT\agenti.csv"';
EXEC xp_cmdshell 'SQLCMD -S . -d ZSI -Q "SELECT * FROM EXCEL_EXPORT2CRM_ARTICOLI" -s ";" -o "E:\MET\ITALCOM\CRM\EXPORT\articoli.csv"';
EXEC xp_cmdshell 'SQLCMD -S . -d ZSI -Q "SELECT * FROM EXCEL_EXPORT2CRM_DOCUMENTI_ORDINI" -s ";" -o "E:\MET\ITALCOM\CRM\EXPORT\ordini.csv"';
EXEC xp_cmdshell 'SQLCMD -S . -d ZSI -Q "SELECT * FROM EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE" -s ";" -o "E:\MET\ITALCOM\CRM\EXPORT\fatture.csv"';
*/