IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.columns WHERE TABLE_NAME = 'EXTRAMAG' AND COLUMN_NAME = 'EXPORTCRM')
ALTER TABLE EXTRAMAG ADD EXPORTCRM VARCHAR(1)
GO

UPDATE E 
SET E.EXPORTCRM = 'S'
--SELECT * 
FROM EXTRAMAG E JOIN EXTRAMAGCRM C ON C.CODART = E.CODART
WHERE CHARINDEX('K', E.CODART) = 0 AND E.CODART NOT IN ('30266', '88079')
GO


IF OBJECT_ID ('dbo.ZS_TU_EXTRAMAG') IS NOT NULL
	DROP TRIGGER dbo.ZS_TU_EXTRAMAG
GO

/*  UPDATE TRIGGER "ZS_TU_EXTRAMAG" FOR TABLE "EXTRAMAG"  */
CREATE TRIGGER ZS_TU_EXTRAMAG ON EXTRAMAG FOR UPDATE AS
BEGIN
   DECLARE
      @MAXCARD  INT,
      @NUMROWS  INT,
      @NUMNULL  INT,
      @ERRNO    INT,
      @ERRMSG   VARCHAR(255)
      SELECT  @NUMROWS = @@ROWCOUNT
      IF @NUMROWS = 0
         RETURN
      
      /*  PARENT "ANAGRAFICAARTICOLI" MUST EXIST WHEN UPDATING A CHILD IN "EXTRAMAG"  */
      IF UPDATE(EXPORTCRM)
      BEGIN
      
      	INSERT INTO dbo.EXTRAMAGCRM (CODART, UTENTEMODIFICA, DATAMODIFICA, GRUPPO, NATURA, CATEGORIASTAT, FAMIGLIA, CONCENTRAZIONE, SPECIALITIES, ECOCERT, COSMOS)
		SELECT CODART, UTENTEMODIFICA, GETDATE(), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
		FROM INSERTED 
		WHERE INSERTED.EXPORTCRM = 'S'
		
		DELETE dbo.EXTRAMAGCRM 
		WHERE CODART IN (
		SELECT CODART
		FROM INSERTED 
		WHERE ISNULL(INSERTED.EXPORTCRM, 'N') = 'N')
		
      END
      RETURN
/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END
GO


SELECT 
	CODICE,
	DESCRIZIONE,
	NRPEZZIIMBALLO,
	NOMENCLCOMBINATA1,
	PROVENIENZA,
	CODART,
	UTENTEMODIFICA,
	DATAMODIFICA,
	GRUPPO,
	NATURA,
	CATEGORIASTAT,
	FAMIGLIA,
	CONCENTRAZIONE,
	SPECIALITIES,
	ECOCERT,
	COSMOS
FROM dbo.EXCEL_EXPORT2CRM_ARTICOLI
WHERE CODICE = '43128'


IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_DOCUMENTI_ORDINI') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_DOCUMENTI_ORDINI
GO

create view EXCEL_EXPORT2CRM_DOCUMENTI_ORDINI as 
SELECT 
	T.CODCLIFOR
		, AC.DSCCONTO1 AS RAGIONESOCIALE
		, T.CODAGENTE1
		, (SELECT TOP 1 AA.DSCAGENTE FROM ANAGRAFICAAGENTI AA WHERE AA.CODAGENTE = T.CODAGENTE1) AS AGENTE
        , T.TIPODOC + '/' + CAST(T.ESERCIZIO AS VARCHAR) + '/' + CAST(T.NUMERODOC AS VARCHAR) AS DOCUMENTO -- + '/' + CAST(R.POSIZIONE AS VARCHAR) AS DOCUMENTO 
        , P.DESCRIZIONE AS TIPODOCUMENTO
        , T.NUMRIFDOC
        , T.DATARIFDOC
        , R.CODART AS ARTICOLO
        , R.DESCRIZIONEART AS DESCRIZIONE
 		, I.DESCRIZIONE IMBALLO 
        , CAST(R.QTAGEST AS INT) AS QUANTITA
        , R.UMGEST
        , R.PREZZOUNITLORDOEURO
        , R.SCONTIESTESI
        , (SELECT TOP 1 TRATTAMENTOIVA.DESCRIZIONE FROM TRATTAMENTOIVA WHERE TRATTAMENTOIVA.CODICE =   R.CODIVA) AS IVA
        , R.PREZZOUNITNETTOEURO
        , R.DATACONSEGNA
        , R.TOTLORDORIGAEURO
        , R.TOTNETTORIGAEURO
        , T.ESERCIZIO, T.TIPODOC, T.NUMERODOC, T.BIS, T.DATADOC 
		, R.ANNOTAZIONI
		, (SELECT TOP 1 TABPORTO.DESCRIZIONE FROM TABPORTO WHERE TABPORTO.CODICE = T.PORTO) AS INCOTERM
		, (SELECT TOP 1 TABPAGAMENTI.DESCRIZIONE FROM TABPAGAMENTI WHERE TABPAGAMENTI.CODICE = t.codpagamento) AS DESCRIZIONEPAGAMENTO
		, VS.DATASCADENZA, VS.IMPORTOSCEURO 
        , (CASE WHEN T.RAGSOCDDM IS NULL THEN 
        		AC.DSCCONTO1 + ' ' + AC.INDIRIZZO + ' ' + AC.LOCALITA + ' ' + AC.PROVINCIA 
        	ELSE
        		t.RAGSOCDDM + ' ' + t.INDIRIZZODDM + ' ' + t.LOCALITADDM + ' ' + t.PROVINCIADDM 
        	END) AS DESTINAZIONE
        , K.IdPubblicazioneKnos AS IDOBJECT
        , T.PROGRESSIVO AS IDTESTA, R.IDRIGA 
        , (SELECT TOP 1 1 FROM EXTRAMAGCRM X WHERE X.CODART = R.CODART) AS EXPORTCRM
        
FROM TESTEDOCUMENTI T WITH (NOLOCK) JOIN EXTRATESTEDOC ET WITH (NOLOCK) ON T.PROGRESSIVO = ET.IDTESTA 
JOIN PARAMETRIDOC P ON P.CODICE = T.TIPODOC
JOIN RIGHEDOCUMENTI R WITH (NOLOCK) ON T.PROGRESSIVO = R.IDTESTA 
JOIN ANAGRAFICACF AC WITH (NOLOCK) ON AC.CODCONTO = T.CODCLIFOR 
--JOIN EXTRACLIENTI WITH (NOLOCK) ON EXTRACLIENTI.CODCONTO = AC.CODCONTO
--JOIN ANAGRAFICAARTICOLI AA WITH (NOLOCK) ON AA.CODICE = R.CODART 
JOIN EXTRARIGHEDOC ER WITH (NOLOCK) ON ER.IDTESTA = R.IDTESTA AND ER.IDRIGA = R.IDRIGA 
LEFT OUTER JOIN VISTASCADENZE VS ON VS.TIPODOC = T.TIPODOC AND VS.ESERCIZIO = T.ESERCIZIO AND VS.NUMDOC = T.NUMERODOC AND VS.BIS = T.BIS
--LEFT OUTER JOIN ZSI_CONFEZSPEDIBILE z WITH (NOLOCK) ON Z.PROGRESSIVO = r.IDTESTA AND z.idriga = r.IDRIGA
LEFT OUTER JOIN TABIMBALLI I WITH (NOLOCK) ON R.CODIMBALLO = I.CODICE 
LEFT OUTER JOIN ITA_ARCHIVIO_DOCUMENTI K ON K.Progressivo = T.PROGRESSIVO
WHERE 
	--t.tipodoc IN ('OCC', 'OCE', 'OCG', 'FTI', 'FTE') AND 
	P.CLIFOR = 'c' AND P.TIPO =  'o' AND
	R.CODART <> '' AND
	R.QTAGESTRES > 0 
	AND t.esercizio >= 2016
GO

GRANT SELECT ON dbo.EXCEL_EXPORT2CRM_DOCUMENTI_ORDINI TO Metodo98
GO


IF OBJECT_ID ('dbo.EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE') IS NOT NULL
	DROP VIEW dbo.EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE
GO

create view EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE as 
SELECT 
	T.CODCLIFOR
		, AC.DSCCONTO1 AS RAGIONESOCIALE
		, T.CODAGENTE1
		, (SELECT TOP 1 AA.DSCAGENTE FROM ANAGRAFICAAGENTI AA WHERE AA.CODAGENTE = T.CODAGENTE1) AS AGENTE
        , T.TIPODOC + '/' + CAST(T.ESERCIZIO AS VARCHAR) + '/' + CAST(T.NUMERODOC AS VARCHAR) AS DOCUMENTO -- + '/' + CAST(R.POSIZIONE AS VARCHAR) AS DOCUMENTO 
        , P.DESCRIZIONE AS TIPODOCUMENTO
        , T.NUMRIFDOC
        , T.DATARIFDOC
        , R.CODART AS ARTICOLO
        , R.DESCRIZIONEART AS DESCRIZIONE
 		, I.DESCRIZIONE IMBALLO 
        , CAST(R.QTAGEST AS INT) AS QUANTITA
        , R.UMGEST
        , R.PREZZOUNITLORDOEURO
        , R.SCONTIESTESI
        , (SELECT TOP 1 TRATTAMENTOIVA.DESCRIZIONE FROM TRATTAMENTOIVA WHERE TRATTAMENTOIVA.CODICE =   R.CODIVA) AS IVA
        , R.PREZZOUNITNETTOEURO
        , R.DATACONSEGNA
        , R.TOTLORDORIGAEURO
        , R.TOTNETTORIGAEURO
        , T.ESERCIZIO, T.TIPODOC, T.NUMERODOC, T.BIS, T.DATADOC 
		, R.ANNOTAZIONI
		, (SELECT TOP 1 TABPORTO.DESCRIZIONE FROM TABPORTO WHERE TABPORTO.CODICE = T.PORTO) AS INCOTERM
		, (SELECT TOP 1 TABPAGAMENTI.DESCRIZIONE FROM TABPAGAMENTI WHERE TABPAGAMENTI.CODICE = t.codpagamento) AS DESCRIZIONEPAGAMENTO
		, VS.DATASCADENZA, VS.IMPORTOSCEURO 
        , (CASE WHEN T.RAGSOCDDM IS NULL THEN 
        		AC.DSCCONTO1 + ' ' + AC.INDIRIZZO + ' ' + AC.LOCALITA + ' ' + AC.PROVINCIA 
        	ELSE
        		t.RAGSOCDDM + ' ' + t.INDIRIZZODDM + ' ' + t.LOCALITADDM + ' ' + t.PROVINCIADDM 
        	END) AS DESTINAZIONE
        , K.IdPubblicazioneKnos AS IDOBJECT
        , T.PROGRESSIVO AS IDTESTA, R.IDRIGA 
        , (SELECT TOP 1 1 FROM EXTRAMAGCRM X WHERE X.CODART = R.CODART) AS EXPORTCRM
        
FROM TESTEDOCUMENTI T WITH (NOLOCK) JOIN EXTRATESTEDOC ET WITH (NOLOCK) ON T.PROGRESSIVO = ET.IDTESTA 
JOIN PARAMETRIDOC P ON P.CODICE = T.TIPODOC
JOIN RIGHEDOCUMENTI R WITH (NOLOCK) ON T.PROGRESSIVO = R.IDTESTA 
JOIN ANAGRAFICACF AC WITH (NOLOCK) ON AC.CODCONTO = T.CODCLIFOR 
--JOIN EXTRACLIENTI WITH (NOLOCK) ON EXTRACLIENTI.CODCONTO = AC.CODCONTO
--JOIN ANAGRAFICAARTICOLI AA WITH (NOLOCK) ON AA.CODICE = R.CODART 
JOIN EXTRARIGHEDOC ER WITH (NOLOCK) ON ER.IDTESTA = R.IDTESTA AND ER.IDRIGA = R.IDRIGA 
LEFT OUTER JOIN VISTASCADENZE VS ON VS.TIPODOC = T.TIPODOC AND VS.ESERCIZIO = T.ESERCIZIO AND VS.NUMDOC = T.NUMERODOC AND VS.BIS = T.BIS
--LEFT OUTER JOIN ZSI_CONFEZSPEDIBILE z WITH (NOLOCK) ON Z.PROGRESSIVO = r.IDTESTA AND z.idriga = r.IDRIGA
LEFT OUTER JOIN TABIMBALLI I WITH (NOLOCK) ON R.CODIMBALLO = I.CODICE 
LEFT OUTER JOIN ITA_ARCHIVIO_DOCUMENTI K ON K.Progressivo = T.PROGRESSIVO
WHERE 
	--t.tipodoc IN ('OCC', 'OCE', 'OCG', 'FTI', 'FTE') AND 
	P.CLIFOR = 'c' AND P.TIPO IN ('F', 'N') AND
	R.CODART <> '' AND
	R.QTAGESTRES > 0 
	AND t.esercizio >= 2016
GO

GRANT SELECT ON dbo.EXCEL_EXPORT2CRM_DOCUMENTI_FATTURE TO Metodo98
GO


IF OBJECT_ID ('dbo.VIS_RIGDOC_BASE_CRM') IS NOT NULL
	DROP VIEW dbo.VIS_RIGDOC_BASE_CRM
GO

create view VIS_RIGDOC_BASE_CRM as 
SELECT 
	T.CODCLIFOR
		, AC.DSCCONTO1 AS RAGIONESOCIALE
        , T.TIPODOC + '/' + CAST(T.ESERCIZIO AS VARCHAR) + '/' + CAST(T.NUMERODOC AS VARCHAR) AS DOCUMENTO -- + '/' + CAST(R.POSIZIONE AS VARCHAR) AS DOCUMENTO 
        , P.DESCRIZIONE AS TIPODOCUMENTO
        , T.NUMRIFDOC
        , T.DATARIFDOC
        , R.CODART AS ARTICOLO
        , R.DESCRIZIONEART AS DESCRIZIONE
        , CAST(R.QTAGEST AS INT) AS QUANTITA
        , R.UMGEST
        , R.PREZZOUNITLORDOEURO
        , R.SCONTIESTESI
        , R.PREZZOUNITNETTOEURO
        , R.DATACONSEGNA
        , R.TOTLORDORIGAEURO
        , R.TOTNETTORIGAEURO
        , T.ESERCIZIO, T.TIPODOC, T.NUMERODOC, T.BIS, T.DATADOC 
		, R.ANNOTAZIONI
		, (SELECT TOP 1 TABPORTO.DESCRIZIONE FROM TABPORTO WHERE TABPORTO.CODICE = T.PORTO) AS INCOTERM
        , T.PROGRESSIVO AS IDTESTA, R.IDRIGA 
        , ISNULL(EM.EXPORTCRM, 'C') AS EXPORTCRM
        
FROM TESTEDOCUMENTI T WITH (NOLOCK) JOIN EXTRATESTEDOC ET WITH (NOLOCK) ON T.PROGRESSIVO = ET.IDTESTA 
JOIN PARAMETRIDOC P ON P.CODICE = T.TIPODOC
JOIN RIGHEDOCUMENTI R WITH (NOLOCK) ON T.PROGRESSIVO = R.IDTESTA 
JOIN ANAGRAFICACF AC WITH (NOLOCK) ON AC.CODCONTO = T.CODCLIFOR 
JOIN EXTRAMAG EM  WITH (NOLOCK) ON EM.CODART = R.CODART
--JOIN EXTRACLIENTI WITH (NOLOCK) ON EXTRACLIENTI.CODCONTO = AC.CODCONTO
--JOIN ANAGRAFICAARTICOLI AA WITH (NOLOCK) ON AA.CODICE = R.CODART 
--JOIN EXTRARIGHEDOC ER WITH (NOLOCK) ON ER.IDTESTA = R.IDTESTA AND ER.IDRIGA = R.IDRIGA 
WHERE 
	--t.tipodoc IN ('OCC', 'OCE', 'OCG', 'FTI', 'FTE') AND 
	P.CLIFOR = 'c' AND P.TIPO IN ('f', 'o', 'n') AND
	R.CODART <> '' AND
	R.QTAGESTRES > 0 
	AND t.esercizio >= 2016
GO

GRANT DELETE ON dbo.VIS_RIGDOC_BASE_CRM TO Metodo98
GO

GRANT INSERT ON dbo.VIS_RIGDOC_BASE_CRM TO Metodo98
GO

GRANT REFERENCES ON dbo.VIS_RIGDOC_BASE_CRM TO Metodo98
GO

GRANT SELECT ON dbo.VIS_RIGDOC_BASE_CRM TO Metodo98
GO

GRANT UPDATE ON dbo.VIS_RIGDOC_BASE_CRM TO Metodo98
GO







IF OBJECT_ID ('dbo.ITA_TAB_EXPORTCRM') IS NOT NULL
	DROP TABLE dbo.ITA_TAB_EXPORTCRM
GO

CREATE TABLE dbo.ITA_TAB_EXPORTCRM
	(
	CODICE         VARCHAR (1) NOT NULL,
	DESCRIZIONE    VARCHAR (14) NOT NULL,
	UTENTEMODIFICA VARCHAR (3) NOT NULL,
	DATAMODIFICA   DATETIME NOT NULL,
	PRIMARY KEY (CODICE)
	
	)
GO


GRANT ALL ON ITA_TAB_EXPORTCRM  TO METODO98
GO


INSERT INTO dbo.ITA_TAB_EXPORTCRM (CODICE, DESCRIZIONE, UTENTEMODIFICA, DATAMODIFICA)
VALUES ('C', 'DA CONTROLLARE', 'TRM', GETDATE())
GO

INSERT INTO dbo.ITA_TAB_EXPORTCRM (CODICE, DESCRIZIONE, UTENTEMODIFICA, DATAMODIFICA)
VALUES ('N', 'NO', 'TRM', GETDATE())
GO

INSERT INTO dbo.ITA_TAB_EXPORTCRM (CODICE, DESCRIZIONE, UTENTEMODIFICA, DATAMODIFICA)
VALUES ('S', 'SI', 'TRM', GETDATE())
GO

