//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoNotificheBSC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM ZS_VISTA_NOTIFICHEBSC")]
        public string MetodoCommand {
            get {
                return ((string)(this["MetodoCommand"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SMTPServerName=172.23.2.95</string>
  <string>SMTPAUTHPassword=ZSI-MSDS</string>
  <string>SMTPAUTHUser=msds.zsi@zschimmer-schwarz.com</string>
  <string>SMTPAUTHUserEmail=msds.zsi@zschimmer-schwarz.com</string>
  <string>SMTPPort=25</string>
  <string>SMTPUseSSL=0</string>
  <string>SMTPAlwaysSendAs=</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CdoConfig {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CdoConfig"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseCdo {
            get {
                return ((bool)(this["UseCdo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string sendMailPopUp {
            get {
                return ((string)(this["sendMailPopUp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<html>
<body>
    <div>
        <p>
            <br />
            Gent.mo Cliente,<br />
            in allegato l'aggiornamento di:<br />
            <b>{0}</b><br />
            <b>{1}</b><br />
            {2}<br /><br />
            Si prega di non rispondere a questo indirizzo email.<br />
            <br />
            Dear Customer,<br />
            please find the attached revised document:<br />
            <b>{0}</b><br />
            <b>{1}</b><br />
            {2}<br /><br />
            Please do not reply to this email address.<br />
        </p>
    </div>
    <div>
        <hr />
        <p>
            <span><b>ZSCHIMMER & SCHWARZ ITALIANA S.p.A.</b></span>
        <br />
        Via A. Ariotto 1/C<br />
        I - 13038 Tricerro, Italia<br />
        <br />
        Tel: +39 0161 808111<br />
        Fax: +39 0161 807335<br />
        Ufficio Commerciale/Sales Office:<br />
        Fax: +39 0161 801002<br />
    </div>
</body>
</html>")]
        public string sendMailSchede {
            get {
                return ((string)(this["sendMailSchede"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EmailImages")]
        public string sendMailEmbeddedImagesPath {
            get {
                return ((string)(this["sendMailEmbeddedImagesPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KnoS_IdObject {
            get {
                return ((int)(this["KnoS_IdObject"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("administrator")]
        public string KnoS_User {
            get {
                return ((string)(this["KnoS_User"]));
            }
            set {
                this["KnoS_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KnoS_PWD {
            get {
                return ((string)(this["KnoS_PWD"]));
            }
            set {
                this["KnoS_PWD"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<html>
<body>
    <div>
        <p>
            <br />
            Gent.mo Cliente,<br />
            in allegato l'aggiornamento di:<br />
            {0}<br />
            {1}<br />
            Si prega di non rispondere a questo indirizzo email.<br />
            <hr />
            Dear Customer,<br />
            please find the attached revised document:<br />
            {0}<br />
            {1}<br />
            Please do not reply to this email address.<br />
        </p>
    </div>
    <div>
        <hr />
        <p>
            <span><b>ZSCHIMMER & SCHWARZ</b></span><br />
        Italiana S.p.A.
        <br />
        Via A. Ariotto 1/C<br />
        I - 13038 Tricerro, Italia<br />
        <br />
        Tel: +39 0161 808111<br />
        Fax: +39 0161 807335<br />
        Ufficio Commerciale:<br />
        Fax: +39 0161 801002
    </div>
</body>
</html>")]
        public string sendMailBollettini {
            get {
                return ((string)(this["sendMailBollettini"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W:\\")]
        public string PathPDF {
            get {
                return ((string)(this["PathPDF"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ZSI-WEBSRV:81")]
        public string KnoS_URL {
            get {
                return ((string)(this["KnoS_URL"]));
            }
            set {
                this["KnoS_URL"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invio DOCUMENTAZIONE - Cliente/Customer: {0}")]
        public string sendMailSchedeTecnicheSubject {
            get {
                return ((string)(this["sendMailSchedeTecnicheSubject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invio BOLLETTINI - Cliente/Customer {0}")]
        public string sendMailBollettiniSubject {
            get {
                return ((string)(this["sendMailBollettiniSubject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("knosmail@gmail.com;m.michieletti@zschimmer-schwarz.com;msds.zsi@zschimmer-schwarz" +
            ".com;")]
        public string sendMailBCC {
            get {
                return ((string)(this["sendMailBCC"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-05-01")]
        public global::System.DateTime DataAggiornamento {
            get {
                return ((global::System.DateTime)(this["DataAggiornamento"]));
            }
            set {
                this["DataAggiornamento"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXECUTE dbo.ITA_SP_UPDATE_REGISTRONOTIFICHEBSC ")]
        public string SqlUpdateBSC {
            get {
                return ((string)(this["SqlUpdateBSC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5018")]
        public int KnoS_IdActionUpdateSchede {
            get {
                return ((int)(this["KnoS_IdActionUpdateSchede"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5016")]
        public int KnoS_IdActionUpdateSchedeRedazione {
            get {
                return ((int)(this["KnoS_IdActionUpdateSchedeRedazione"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H:\\LETTERATURE PRODOTTI FINITI\\SCHEDE DI SICUREZZA")]
        public string PathPDF_H {
            get {
                return ((string)(this["PathPDF_H"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("knosmail@gmail.com;m.michieletti@zschimmer-schwarz.com")]
        public string sendMailBCCSimulazione {
            get {
                return ((string)(this["sendMailBCCSimulazione"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invio COA - Cliente/Customer: {0}")]
        public string sendMailCOASubject {
            get {
                return ((string)(this["sendMailCOASubject"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-01-01")]
        public global::System.DateTime DataInvioSchede {
            get {
                return ((global::System.DateTime)(this["DataInvioSchede"]));
            }
            set {
                this["DataInvioSchede"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<html>
<body>
    <div>
        <p>
            <br />
            Gent.mo Cliente,<br />
            in allegato il certificato di analisi di:<br />
            {0}<br />
            Si prega di non rispondere a questo indirizzo email.<br />
            <hr />
            Dear Customer,<br />
            please find the attached revised document:<br />
            {0}<br />
            Please do not reply to this email address.<br />
        </p>
    </div>
    <div>
        <hr />
        <p>
            <span><b>ZSCHIMMER & SCHWARZ ITALIANA S.p.A.</b></span>
        <br />
        Via A. Ariotto 1/C<br />
        I - 13038 Tricerro, Italia<br />
        <br />
        Tel: +39 0161 808111<br />
        Fax: +39 0161 807335<br />
        Ufficio Commerciale/Sales Office:<br />
        Fax: +39 0161 801002<br />
    </div>
</body>
</html>")]
        public string sendMailCOA {
            get {
                return ((string)(this["sendMailCOA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM ZS_VISTA_ALLEGATISCHEDESICUREZZA")]
        public string MetodoCommandAllegati {
            get {
                return ((string)(this["MetodoCommandAllegati"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RicercaAutomaticaSchede {
            get {
                return ((bool)(this["RicercaAutomaticaSchede"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InvioAutomaticaSchede {
            get {
                return ((bool)(this["InvioAutomaticaSchede"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseVbs {
            get {
                return ((bool)(this["UseVbs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SMTPServerName=smtp.gmail.com</string>
  <string>SMTPAUTHPassword=KnosMailService2015</string>
  <string>SMTPAUTHUser=knosmail@gmail.com</string>
  <string>SMTPAUTHUserEmail=knosmail@gmail.com</string>
  <string>SMTPPort=465</string>
  <string>SMTPUseSSL=1</string>
  <string>SMTPAlwaysSendAs=</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CdoConfigCOA {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CdoConfigCOA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("knosmail@gmail.com;m.michieletti@zschimmer-schwarz.com;coa.zsi@zschimmer-schwarz." +
            "com;")]
        public string sendMailBCCCOA {
            get {
                return ((string)(this["sendMailBCCCOA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("knosmail@gmail.com;m.michieletti@zschimmer-schwarz.com;coa.zsi@zschimmer-schwarz." +
            "com;")]
        public string sendMailBCCSimulazioneCOA {
            get {
                return ((string)(this["sendMailBCCSimulazioneCOA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SMTPServerName=smtp.gmail.com</string>
  <string>SMTPAUTHPassword=KnosMailService2015</string>
  <string>SMTPAUTHUser=knosmail@gmail.com</string>
  <string>SMTPAUTHUserEmail=knosmail@gmail.com</string>
  <string>SMTPPort=465</string>
  <string>SMTPUseSSL=1</string>
  <string>SMTPAlwaysSendAs=</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LotusConfig {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LotusConfig"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"""Gent.mo Cliente,"" & vbcrlf & ""in allegato l'aggiornamento di:"" & vbcrlf & ""{0}"" & vbcrlf & ""{1}"" & vbcrlf & ""Si prega di non rispondere a questo indirizzo email."" & vbcrlf & ""Dear Customer,"" & vbcrlf & ""please find the attached revised document:"" & vbcrlf & ""{0}"" & vbcrlf & ""{1}"" & vbcrlf & ""Please do not reply to this email address."" & vbcrlf & ""ZSCHIMMER & SCHWARZ"" & vbcrlf & ""Italiana S.p.A."" & vbcrlf & ""Via A. Ariotto 1/C"" & vbcrlf & ""I - 13038 Tricerro, Italia"" & vbcrlf & ""Tel: +39 0161 808111"" & vbcrlf & ""Fax: +39 0161 807335"" & vbcrlf & ""Ufficio Commerciale:"" & vbcrlf & ""Fax: +39 0161 801002"" ")]
        public string sendMailBollettiniVbsLotus {
            get {
                return ((string)(this["sendMailBollettiniVbsLotus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"""Gent.mo Cliente,"" & vbcrlf & ""in allegato il certificato di analisi di:"" & vbcrlf & ""{0}"" & vbcrlf & ""Si prega di non rispondere a questo indirizzo email."" & vbcrlf & ""Dear Customer,"" & vbcrlf & ""please find the attached revised document:"" & vbcrlf & ""{0}"" & vbcrlf & ""Please do not reply to this email address."" & vbcrlf & ""ZSCHIMMER & SCHWARZ"" & vbcrlf & ""Italiana S.p.A."" & vbcrlf & ""Via A. Ariotto 1/C"" & vbcrlf & ""I - 13038 Tricerro, Italia"" & vbcrlf & ""Tel: +39 0161 808111"" & vbcrlf & ""Fax: +39 0161 807335"" & vbcrlf & ""Ufficio Commerciale:"" & vbcrlf & ""Fax: +39 0161 801002"" ")]
        public string sendMailCOAVbsLotus {
            get {
                return ((string)(this["sendMailCOAVbsLotus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<html>
<body>
    <div>
<p>notifica da parte del magazzino</p>
        <p>
            {0}
        </p>
    </div>
    <div>
        <hr />
        <p>
            <span><b>ZSCHIMMER & SCHWARZ ITALIANA S.p.A.</b></span>
        <br />
        Via A. Ariotto 1/C<br />
        I - 13038 Tricerro, Italia<br />
        <br />
        Tel: +39 0161 808111<br />
        Fax: +39 0161 807335<br />
        Ufficio Commerciale/Sales Office:<br />
        Fax: +39 0161 801002<br />
    </div>
</body>
</html>")]
        public string sendMailMAG {
            get {
                return ((string)(this["sendMailMAG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'OCC\'")]
        public string MAGTipiDocItalia {
            get {
                return ((string)(this["MAGTipiDocItalia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 101")]
        public string MAGTipiImballiEsclusi {
            get {
                return ((string)(this["MAGTipiImballiEsclusi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM EXCEL_PORTAFOGLIOORDINI")]
        public string MAGMetodoCommand {
            get {
                return ((string)(this["MAGMetodoCommand"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>m.michieletti@zschimmer-schwarz.com</string>
  <string>e.presutto@zschimmer-schwarz.com</string>
  <string>m.pastore@zschimmer-schwarz.com</string>
  <string>g.ogliaro@zschimmer-schwarz.com</string>
  <string>i.sesia@zschimmer-schwarz.com</string>
  <string>m.finassi@zschimmer-schwarz.com</string>
  <string>m.costanzo@zschimmer-schwarz.com</string>
  <string>v.mussio@zschimmer-schwarz.coM</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sendMailMAGBackOffice {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sendMailMAGBackOffice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m.michieletti@zschimmer-schwarz.com")]
        public string sendMailMAGProduzione {
            get {
                return ((string)(this["sendMailMAGProduzione"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>m.finassi@zschimmer-schwarz.com</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sendMailMAGPosizionamento {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sendMailMAGPosizionamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>XLS_DATACARICO</string>
  <string>ARTICOLO</string>
  <string>XLS_DESCRIZIONE</string>
  <string>XLS_QTA</string>
  <string>XLS_TIPOIMBALLO</string>
  <string>XLS_NUMONU</string>
  <string>XLS_CLASSEADR</string>
  <string>XLS_NRLOTTO</string>
  <string>XLS_DESTINAZIONE</string>
  <string>XLS_DATACONSEGNA</string>
  <string>XLS_NOTE</string>
  <string>XLS_COSTO</string>
  <string>XLS_SPEDIZIONIERE</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MAGModuloM12TrasportatoreColonne {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MAGModuloM12TrasportatoreColonne"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>XLS_DATACARICO</string>
  <string>XLS_CLIENTE</string>
  <string>DESCRIZIONE</string>
  <string>XLS_QTA</string>
  <string>XLS_DESTINAZIONE</string>
  <string>XLS_NUMONU</string>
  <string>XLS_CLASSEADR</string>
  <string>XLS_NOTEMAG</string>
  <string>XLS_DATACONSEGNA</string>
  <string>XLS_NOTEART</string>
  <string>XLS_COSTO</string>
  <string>XLS_SPEDIZIONIERE</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MAGModuloM13TrasportatoreColonne {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MAGModuloM13TrasportatoreColonne"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>XLS_DATACARICO</string>
  <string>NOTECONTAINER</string>
  <string>XLS_VUOTO</string>
  <string>RAGIONESOCIALE</string>
  <string>XLS_DESTINAZIONE</string>
  <string>XLS_CLASSEADR</string>
  <string>XLS_SHIPPER</string>
  <string>XLS_NOTECONSIGNEE</string>
  <string>XLS_NOTENOTIFY</string>
  <string>XLS_DOCUMENTI</string>
  <string>XLS_NOTE</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MAGModuloM14TrasportatoreColonne {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MAGModuloM14TrasportatoreColonne"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MAGTipiImballo {
            get {
                return ((int)(this["MAGTipiImballo"]));
            }
            set {
                this["MAGTipiImballo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MAGTStatoM05 {
            get {
                return ((int)(this["MAGTStatoM05"]));
            }
            set {
                this["MAGTStatoM05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MAGTipoOrdini {
            get {
                return ((int)(this["MAGTipoOrdini"]));
            }
            set {
                this["MAGTipoOrdini"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'OCE\'")]
        public string MAGTipiDocEstero {
            get {
                return ((string)(this["MAGTipiDocEstero"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SMTPServerName=smtp.gmail.com</string>
  <string>SMTPAUTHPassword=KnosMailService2015</string>
  <string>SMTPAUTHUser=knosmail@gmail.com</string>
  <string>SMTPAUTHUserEmail=knosmail@gmail.com</string>
  <string>SMTPPort=465</string>
  <string>SMTPUseSSL=1</string>
  <string>SMTPAlwaysSendAs=</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CdoConfigM05 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CdoConfigM05"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<html>\r\n<body style=\"font-family:Tahoma; font-size:10pt;\">\r\n    <div style=\"overf" +
            "low-x:auto;\">\r\n<br>\r\n        <p>\r\n            {0}\r\n        </p>\r\n    </div>\r\n</b" +
            "ody>\r\n</html>\r\n")]
        public string sendMailM05 {
            get {
                return ((string)(this["sendMailM05"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MailSavedLocal {
            get {
                return ((bool)(this["MailSavedLocal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invio mail M05")]
        public string sendMailM05Subject {
            get {
                return ((string)(this["sendMailM05Subject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ARTICOLO</string>
  <string>DESCRIZIONE</string>
  <string>QTASPEDIBILE</string>
  <string>XLS_TIPOIMBALLO</string>
  <string>XLS_NUMONU</string>
  <string>XLS_CLASSEADR</string>
  <string>XLS_NRLOTTO</string>
  <string>XLS_DESTINAZIONE</string>
  <string>XLS_DATACONSEGNA</string>
  <string>XLS_NOTE</string>
  <string>XLS_SPEDIZIONIERE</string>
  <string>XLS_DATACARICO</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MAGModuloM12ITATrasportatoreColonne {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MAGModuloM12ITATrasportatoreColonne"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseLotus {
            get {
                return ((bool)(this["UseLotus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>XLS_M05_ESTERO_CLIENTE</string>
  <string>XLS_M05_ESTERO_DOCUMENTO</string>
  <string>XLS_M05_ESTERO_ARTICOLO</string>
  <string>XLS_M05_ESTERO_DESCRIZIONE</string>
  <string>XLS_M05_ESTERO_QTAGEST</string>
  <string>XLS_M05_ESTERO_NRPEZZIIMBALLO</string>
  <string>XLS_M05_ESTERO_NRCOLLI</string>
  <string>XLS_M05_ESTERO_TIPOIMBALLO</string>
  <string>XLS_M05_ESTERO_NOTE</string>
  <string>XLS_M05_ESTERO_ETICHETTATURA</string>
  <string>XLS_M05_ESTERO_CONSEGNA</string>
  <string>XLS_M05_ESTERO_POSIZIONAMENTO</string>
  <string>XLS_M05_ESTERO_DISPONIBILITA</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MAGModuloM05Export {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MAGModuloM05Export"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\srv2k8\\dati\\Certificati")]
        public string PathCOA {
            get {
                return ((string)(this["PathCOA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MNNDataNomeFile {
            get {
                return ((bool)(this["MNNDataNomeFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public string RowHeaderImageList {
            get {
                return ((string)(this["RowHeaderImageList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I:\\Italcom\\PrototipoMagazzino")]
        public string pathServerApp {
            get {
                return ((string)(this["pathServerApp"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentUser {
            get {
                return ((string)(this["CurrentUser"]));
            }
            set {
                this["CurrentUser"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>XLS_M15_DATALUOGOCONSEGNA</string>
  <string>XLS_M15_QTASPEDIBILE</string>
  <string>XLS_M05_ESTERO_TIPOIMBALLO</string>
  <string>XLS_M15_NUMONU</string>
  <string>XLS_M15_CLASSEADR</string>
  <string>XLS_DESTINAZIONERAGSOC</string>
  <string>XLS_M15_RESA</string>
  <string>XLS_SHIPPER</string>
  <string>XLS_NOTECONSIGNEE</string>
  <string>XLS_NOTENOTIFY</string>
  <string>XLS_DOCUMENTI</string>
  <string>XLS_NOTE</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MAGModuloM15GRTrasportatoreColonne {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MAGModuloM15GRTrasportatoreColonne"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>XLS_M15_DATALUOGOCONSEGNA</string>
  <string>XLS_M15_QTASPEDIBILE</string>
  <string>XLS_M05_ESTERO_TIPOIMBALLO</string>
  <string>XLS_M15_NUMONU</string>
  <string>XLS_M15_CLASSEADR</string>
  <string>XLS_DESTINAZIONERAGSOC</string>
  <string>XLS_M15_RESA</string>
  <string>XLS_SHIPPER</string>
  <string>XLS_NOTECONSIGNEE</string>
  <string>XLS_NOTENOTIFY</string>
  <string>XLS_DOCUMENTI</string>
  <string>XLS_NOTE</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MAGModuloM15TrasportatoreColonne {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MAGModuloM15TrasportatoreColonne"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>\\\\srv2k8\\Dati\\LETTERATURE PRODOTTI FINITI\\RMI</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PathRMI {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PathRMI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5019")]
        public int KnoS_IdActionUpdateRMIRedazione {
            get {
                return ((int)(this["KnoS_IdActionUpdateRMIRedazione"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5021")]
        public int KnoS_IdActionUpdateRMI {
            get {
                return ((int)(this["KnoS_IdActionUpdateRMI"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2018-01-01")]
        public global::System.DateTime DataAggiornamentoRMI {
            get {
                return ((global::System.DateTime)(this["DataAggiornamentoRMI"]));
            }
            set {
                this["DataAggiornamentoRMI"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM ZS_VISTA_FILEEPY_REVISIONLAST WHERE DATAMODIFICA >= \'{0}\'")]
        public string SqlSchede {
            get {
                return ((string)(this["SqlSchede"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.19.1.17;Initial Catalog=ZSI;Persist Security Info=True;User ID=kn" +
            "os;Password=zx1ctp21")]
        public string MetodoConnectionString {
            get {
                return ((string)(this["MetodoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.19.1.17;Initial Catalog=ZSI;Persist Security Info=True;User ID={0" +
            "};Password={1}")]
        public string MetodoConnectionStringUSER {
            get {
                return ((string)(this["MetodoConnectionStringUSER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM EXCEL_PORTAFOGLIOORDINI_M10")]
        public string MAGMetodoCommandM10 {
            get {
                return ((string)(this["MAGMetodoCommandM10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>W:\\</string>\r\n  <string>C:\\temp\\</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection listPathPDF {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["listPathPDF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>H:\LETTERATURE PRODOTTI FINITI\SCHEDE DI SICUREZZA</string>
  <string>C:\Temp</string>
  <string>C:\_condivisa</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection listPathPDF_H {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["listPathPDF_H"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXECUTE dbo.ITA_SP_UPDATE_REGISTRONOTIFICHEBSC _PA")]
        public string SqlUpdateBSC_PA {
            get {
                return ((string)(this["SqlUpdateBSC_PA"]));
            }
        }
    }
}
