



IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.columns WHERE TABLE_NAME = 'EXTRARIGHEDOC' AND COLUMN_NAME = 'DATAINVIOCOA')
	ALTER TABLE EXTRARIGHEDOC ADD DATAINVIOCOA DATETIME
GO


IF OBJECT_ID ('dbo.VISTA_NOTIFICHEBSCCOA') IS NOT NULL
	DROP VIEW dbo.VISTA_NOTIFICHEBSCCOA
GO

create view VISTA_NOTIFICHEBSCCOA as 

SELECT 
	a.codconto AS CODCLIFOR
	, a.dscconto1 AS RAGIONESOCIALE
	, isnull(a.telex, '') AS EMAIL_CLIENTE
	, '' AS EMAIL_AGENTE
	, t.TIPODOC + '/' + CAST(t.ESERCIZIO AS VARCHAR) + '/' + CAST(t.NUMERODOC AS VARCHAR) + '/' + t.BIS AS DOCUMENTO
	, r.CODART AS ARTICOLOBSC
	, r.DESCRIZIONEART AS DESCRIZIONEARTICOLO
	, e.DATAINVIOCOA
	, r.QTAGEST
	, r.QTAGESTRES
	, isnull(e.NRLOTTO, 'NESSUN LOTTO') AS Lotto
	, I.idpubblicazioneknos AS IDOBJECT_DOC
	, '' AS PATHCOA
	, ((CASE WHEN charindex('#', r.codart) > 0 THEN LEFT(r.CODART, len(r.CODART) -3) ELSE r.CODART END) 
	+ '*_' + isnull(e.NRLOTTO, 'NESSUN LOTTO')
	) AS filenamecoacalc1
	, ((CASE WHEN charindex('#', r.codart) > 0 THEN LEFT(r.CODART, len(r.CODART) -3) ELSE r.CODART END) 
	+ ltrim(substring(a.CODCONTO, 2, 6))
	+ '*_' + isnull(e.NRLOTTO, 'NESSUN LOTTO')
	) AS filenamecoacalc2
	, R.IDTESTA, R.IDRIGA
	, t.TIPODOC
	, t.ESERCIZIO
	, t.NUMERODOC
	, t.BIS
	, t.DATADOC
	, r.DATACONSEGNA
	, r.CODART 
FROM RIGHEDOCUMENTI r JOIN EXTRARIGHEDOC e ON e.IDTESTA = r.IDTESTA AND e.IDRIGA = r.IDRIGA
	JOIN TESTEDOCUMENTI t ON t.PROGRESSIVO = r.IDTESTA 
	JOIN ANAGRAFICACF a ON a.CODCONTO = t.CODCFFATT
	JOIN ita_archivio_documenti I ON I.progressivo = t.PROGRESSIVO
WHERE t.TIPODOC IN (SELECT codice FROM PARAMETRIDOC p WHERE p.TIPO = 'b' AND p.CLIFOR = 'c') 
--AND isnull(e.nrLotto, '') <> ''
--AND r.QTAGESTRES > 0
AND r.CODART <> ''
GO



GRANT SELECT ON dbo.VISTA_NOTIFICHEBSCCOA TO Metodo98
GO
