IF OBJECT_ID ('dbo.VISTA_KNOS_INVIOCONFERMAORDINIMAIL') IS NOT NULL
	DROP VIEW dbo.VISTA_KNOS_INVIOCONFERMAORDINIMAIL
GO

CREATE view VISTA_KNOS_INVIOCONFERMAORDINIMAIL as 

SELECT DISTINCT
	a.codconto AS CODCLIFOR
	, a.dscconto1 AS RAGIONESOCIALE
	, isnull(dbo.fn_GetEMAILCONTATTICLIENTECOA(a.codconto), '') + isnull((SELECT TOP 1 d.email FROM DESTINAZIONIDIVERSE d WHERE d.CODCONTO = a.codconto AND d.CODICE = t.NUMDESTDIVERSAMERCI), '') AS EMAIL_CLIENTE
	, '' AS EMAIL_AGENTE
	, t.TIPODOC + '/' + CAST(t.ESERCIZIO AS VARCHAR) + '/' + CAST(t.NUMERODOC AS VARCHAR) + '/' + t.BIS AS DOCUMENTO
	, t.PROGRESSIVO AS IDTESTA
	, t.TIPODOC
	, t.ESERCIZIO
	, t.NUMERODOC
	, t.BIS
	, t.DATADOC
	, t.DATAMODIFICA
	, i.IdPubblicazioneKnos AS IDOBJECT_DOC
	--, ic.IdPubblicazioneKnos AS IDOBJECT_CLI
FROM RIGHEDOCUMENTI r JOIN EXTRARIGHEDOC e ON e.IDTESTA = r.IDTESTA AND e.IDRIGA = r.IDRIGA
	JOIN TESTEDOCUMENTI t ON t.PROGRESSIVO = r.IDTESTA 
	JOIN ANAGRAFICACF a ON a.CODCONTO = t.CODCFFATT
	JOIN ita_archivio_documenti I ON I.progressivo = t.PROGRESSIVO
	--JOIN ita_archivio_clifor IC ON IC.CodConto = t.CODCLIFOR
WHERE t.TIPODOC IN ('OCE', 'OCC', 'OCG') 
AND t.DOCCHIUSO = 0
AND R.CODIMBALLO IN (100, 101)

GO

GRANT DELETE ON dbo.VISTA_KNOS_INVIOCONFERMAORDINIMAIL TO Metodo98
GO
GRANT INSERT ON dbo.VISTA_KNOS_INVIOCONFERMAORDINIMAIL TO Metodo98
GO
GRANT REFERENCES ON dbo.VISTA_KNOS_INVIOCONFERMAORDINIMAIL TO Metodo98
GO
GRANT SELECT ON dbo.VISTA_KNOS_INVIOCONFERMAORDINIMAIL TO Metodo98
GO
GRANT UPDATE ON dbo.VISTA_KNOS_INVIOCONFERMAORDINIMAIL TO Metodo98
GO

SELECT * FROM VISTA_KNOS_INVIOCONFERMAORDINIMAIL