DECLARE @A AS VARCHAR(50)

SET @A = '20553'

SELECT * FROM TIPOLOGIEARTICOLI WHERE CODICEART LIKE @A
SELECT * FROM VARIANTIARTICOLI WHERE CODICEART LIKE @A


UPDATE TIPOLOGIEARTICOLI SET NUMEROTIP = 3 WHERE CODICEART = @A AND NUMEROTIP = 2
AND NOT EXISTS(SELECT 1 FROM TIPOLOGIEARTICOLI X WHERE X.CODICEART = @A AND X.NUMEROTIP = 3)

INSERT INTO dbo.TIPOLOGIEARTICOLI (CODICEART, NUMEROTIP, CODTIPOLOGIA, SELVARIANTI, AGGIUNGIDES, UTENTEMODIFICA, DATAMODIFICA)
SELECT @A, 2, 'SPE', 1, 1, 'NC', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM TIPOLOGIEARTICOLI X WHERE X.CODICEART = @A AND X.NUMEROTIP = 2)



INSERT INTO dbo.VARIANTIARTICOLI (CODICEART, NUMEROTIP, VARIANTE, TIPOLOGIA, SOLOSE, UTENTEMODIFICA, DATAMODIFICA)
SELECT @A, 2, '000', 'SPE', '', 'NC', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM VARIANTIARTICOLI X WHERE X.CODICEART = @A AND X.NUMEROTIP = 2)



UPDATE VARIANTIARTICOLI SET NUMEROTIP = 3 WHERE CODICEART = @A AND NUMEROTIP = 2
AND NOT EXISTS(SELECT 1 FROM VARIANTIARTICOLI X WHERE X.CODICEART = @A AND X.NUMEROTIP = 3 AND X.tipologia = VARIANTIARTICOLI.TIPOLOGIA AND variantiarticoli.VARIANTE = x.VARIANTE)

INSERT INTO dbo.VARIANTIARTICOLI (CODICEART, NUMEROTIP, VARIANTE, TIPOLOGIA, SOLOSE, UTENTEMODIFICA, DATAMODIFICA)
SELECT @A, 2, '000', 'SPE', '', 'NC', GETDATE() WHERE NOT EXISTS(SELECT 1 FROM VARIANTIARTICOLI X WHERE X.CODICEART = @A AND X.NUMEROTIP = 2)


IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI_MOV') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI_MOV
GO

CREATE VIEW ZS_VISTA_GENERAARTICOLI_MOV
AS

SELECT * FROM (
	SELECT DISTINCT 
	(CASE WHEN charindex('#', R.CODART) > 1 THEN LEFT(R.CODART, charindex('#', R.CODART) - 1) ELSE R.CODART END) AS ARTTIPOLOGIA
	, R.CODART, R.CODIMBALLO AS CODICE, I.DESCRIZIONE AS DESCRIMBALLO, I.VARIANTEIMBALLO, V.DESCRIZIONE AS DESCRVARIANTE
	, (CASE WHEN RIGHT(R.CODART, 3) = 'XXX' THEN REPLACE(R.CODART, 'XXX',  '000' + I.VARIANTEIMBALLO)
	ELSE R.CODART + '#000' + '000' + I.VARIANTEIMBALLO
	END) AS NUOVOCODART
FROM RIGHEDOCUMENTI R WITH (NOLOCK) 
JOIN TABIMBALLI I WITH (NOLOCK) ON I.CODICE = R.CODIMBALLO
JOIN TABVARIANTI v WITH (NOLOCK) ON v.VARIANTE = I.varianteimballo
WHERE R.CODART <> '' AND V.TIPOLOGIA = '62'
AND I.VARIANTEIMBALLO <> ''
	) CTE
WHERE ARTTIPOLOGIA BETWEEN '20000' AND '49999'
	AND charindex('#', substring(nuovocodart, charindex('#', nuovocodart) + 1, 10) ) = 0
	--AND NUOVOCODART NOT IN (SELECT CODICE FROM ANAGRAFICAARTICOLI)
	 

GO

GRANT DELETE ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO
GRANT INSERT ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO
GRANT REFERENCES ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO
GRANT SELECT ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO
GRANT UPDATE ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO


IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI_MODELLI') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI_MODELLI
GO

CREATE view ZS_VISTA_GENERAARTICOLI_MODELLI as 


SELECT R.CODART AS ARTTIPOLOGIA
	, R.CODART, '' AS CODICE
	, 'XXX' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO, 'XXX' AS DESCRVARIANTE
	, (R.CODART + '#000000XXX') AS NUOVOCODART 
	, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WITH (NOLOCK) WHERE A.CODICE = R.CODART) AS DESCRIZIONE
	, 'A' AS TIPO
	FROM (
SELECT X.CODART FROM ZS_VISTA_GENERAARTICOLI_MOV X 
WHERE charindex('#', X.CODART) = 0
GROUP BY X.CODART
HAVING count(*) > 1) R


GO

GRANT SELECT ON dbo.ZS_VISTA_GENERAARTICOLI_MODELLI TO Metodo98
GO



IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI
GO

CREATE VIEW ZS_VISTA_GENERAARTICOLI
AS
/*
SELECT *, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WHERE A.CODICE = CTE.CODART OR A.CODICE = CTE.ARTTIPOLOGIA) AS DESCRIZIONE FROM (
	SELECT distinct
	(CASE WHEN charindex('#', g.CODART) > 1 THEN LEFT(g.CODART, charindex('#', g.CODART) - 1) ELSE g.CODART END) AS ARTTIPOLOGIA
	, g.CODART
	, t.CODICE
	, t.varianteimballo
	, (CASE 
		WHEN charindex('#', g.CODART) > 0 AND charindex('?', g.codart) = 0 THEN LEFT(g.CODART, charindex('#', g.CODART) + 3) + T.VARIANTEIMBALLO 
		WHEN charindex('#', g.CODART) > 0 AND charindex('?', g.codart) > 0 THEN LEFT(g.CODART, charindex('#', g.CODART)) + '000' + T.VARIANTEIMBALLO 
		ELSE
			g.CODART + '#000' + T.VARIANTEIMBALLO 
		END) AS NUOVOCODART
		--, g.*
	FROM GESTIONEPREZZI g JOIN GESTIONEPREZZIRIGHE r ON g.PROGRESSIVO = r.RIFPROGRESSIVO
	JOIN tabimballi t ON t.CODICE = r.cod_imballo 
	JOIN TABVARIANTI v ON v.VARIANTE = t.varianteimballo
	WHERE g.INIZIOVALIDITA = g.FINEVALIDITA and t.varianteimballo  <> '' --AND charindex('?', g.codart) = 0
	--AND t.codice NOT IN (100, 101)
	) CTE
WHERE 
	NUOVOCODART NOT IN (SELECT CODICE FROM ANAGRAFICAARTICOLI)
	AND ARTTIPOLOGIA BETWEEN '20000' AND '49999'
	*/


SELECT X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART
	, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WITH (NOLOCK) WHERE A.CODICE = X.CODART OR A.CODICE = X.ARTTIPOLOGIA) AS DESCRIZIONE --, '' AS TIPO
	, (SELECT 'B' FROM ZS_VISTA_GENERAARTICOLI_MOV Z WHERE Z.CODART = X.CODART AND LEFT(Z.CODART, 1) <> '2' GROUP BY Z.CODART HAVING COUNT(Z.CODART) = 1 ) AS TIPO

FROM 
	 ZS_VISTA_GENERAARTICOLI_MOV x -- ON  x.ARTTIPOLOGIA = cte.arttipologia AND x.CODIMBALLO = cte.cod_imballo
UNION
SELECT 
	X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART, X.DESCRIZIONE, X.TIPO 
FROM 
	ZS_VISTA_GENERAARTICOLI_MODELLI X


GO

GRANT DELETE ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT INSERT ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT REFERENCES ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT SELECT ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT UPDATE ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO



IF OBJECT_ID ('dbo.ZS_GENERAARTICOLO_POST') IS NOT NULL
	DROP PROCEDURE dbo.ZS_GENERAARTICOLO_POST
GO

create PROCEDURE ZS_GENERAARTICOLO_POST(@CODART VARCHAR(50), @OLDCODART VARCHAR(50), @CODIMBALLO VARCHAR(50), @REDO SMALLINT = 0) AS
BEGIN
 
	DECLARE @ARTPADRE VARCHAR(50)
	DECLARE @ARTMODELLO VARCHAR(50)
	
	SET @ARTPADRE = LEFT(@CODART, CHARINDEX('#' , @CODART) -1)
	SET @ARTMODELLO = LEFT(@CODART, LEN(@CODART) -3) + 'XXX'
	

	

	
	IF (NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST WHERE CODART = @OLDCODART AND NUOVOCODART = @CODART ) OR @REDO = 1)
	BEGIN
	
		PRINT @ARTPADRE
		PRINT @ARTMODELLO
		PRINT @CODIMBALLO
		
		INSERT INTO dbo.ZS_GENERAARTICOLI_POST (CODART, NUOVOCODART, UtenteModifica, DataModifica, CODICE)
		SELECT @OLDCODART, @CODART, 'TRM', GETDATE(), @CODIMBALLO
		FROM TABDITTE
		WHERE NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST X WHERE X.CODART = @OLDCODART AND X.NUOVOCODART = @CODART)-- AND X.CODICE = CODICE)
		
		--EXEC ZS_GENERAARTICOLI_GESTIONEPREZZI @CODART, @OLDCODART
		
		
		
		DECLARE @NRPEZZIIMBALLO INT
		

		SELECT @NRPEZZIIMBALLO = G1.QTA_COLLI 
		FROM ITA_VIS_PRZPART_IMBLIST  G1
		WHERE G1.PRIORITA > 1 AND
			(G1.CODART = @CODART OR
			G1.CODART = LEFT(@CODART, LEN(@CODART) -3) + '???' OR
			G1.CODART LIKE @ARTPADRE + '%') --'#??????')
		AND G1.COD_IMBALLO = @CODIMBALLO

		-- DATI ANAGRAFICASTANDARD
 		UPDATE a1
		SET 
			a1.DESCRIZIONE = RTRIM(LEFT(a2.descrizione + ' ' + (SELECT TOP 1 TABVARIANTI.DESCRIZIONE FROM TABVARIANTI WHERE TABVARIANTI.VARIANTE = RIGHT(a1.CODICE, 3) AND TIPOLOGIA = '62'), 80))
			, a1.GRUPPO = a2.GRUPPO
			, a1.CATEGORIA = a2.CATEGORIA
			, a1.CODCATEGORIASTAT = a2.CODCATEGORIASTAT
			, a1.PESONETTO = a2.PESONETTO
			, a1.SUPERFICIE = a2.SUPERFICIE
			, a1.CUBATURA = a2.CUBATURA
			, a1.NOMENCLCOMBINATA1 = a2.NOMENCLCOMBINATA1
			, a1.NOMENCLCOMBINATA2 = a2.NOMENCLCOMBINATA2
			, a1.ORIGINEINTRA = a2.ORIGINEINTRA 
			, a1.CODICEARTIMBALLO = a1.CODICEARTIMBALLO
			, a1.NRPEZZIIMBALLO = @NRPEZZIIMBALLO --a2.NRPEZZIIMBALLO
			, a1.RIFERIMIMBALLO = @CODIMBALLO --(SELECT TOP 1 tabimballi.CODICE FROM TABIMBALLI WHERE tabimballi.VARIANTEIMBALLO = RIGHT(a1.CODICE, 3))
			, a1.AGGIORNAMAG = a2.AGGIORNAMAG
			, a1.MOVIMENTAPARTITE = a2.MOVIMENTAPARTITE
			, a1.MOVIMENTAMATRICOLE = a2.MOVIMENTAMATRICOLE
			, a1.CODDEPOSITO = a2.CODDEPOSITO
			, a1.NRTIPRAGGRUPPATE = a2.NRTIPRAGGRUPPATE
			, a1.ARTCONFIGURATO = a2.ARTCONFIGURATO
		--SELECT rtrim(a2.descrizione + substring(a1.descrizione, (SELECT len(a3.DESCRIZIONE) FROM ANAGRAFICAARTICOLI a3 WHERE ARTTIPOLOGIA = 1 AND CODICE = a1.CODICEPRIMARIO)+1, 80)), *
		FROM ANAGRAFICAARTICOLI a1, ANAGRAFICAARTICOLI a2
		WHERE 
			a1.CODICE = @CODART
			AND a2.CODICE = @ARTMODELLO
			AND LEFT(a1.CODICE , 1) = '2'
			
			
		
				
		UPDATE a1
		SET 
			a1.CODIVA = a2.CODIVA
			, SCONTO1 = a2.SCONTO1
			, a1.SCONTO2 = a2.SCONTO2
			, a1.SCONTO3 = a2.SCONTO3
			, a1.GRUPPOPRZPART = a2.GRUPPOPRZPART
			, a1.GRUPPOPRVPART = a2.GRUPPOPRVPART
			, a1.PROVV = a2.PROVV
			, a1.CODICEALT1 = a2.CODICEALT1
			, a1.CODICEALT2 = a2.CODICEALT2
			, a1.SCGENVENDITEITA = a2.SCGENVENDITEITA
			, a1.SCGENVENDITEEST = a2.SCGENVENDITEEST
			, a1.SCGENACQUISTIITA = a2.SCGENACQUISTIITA
			, a1.SCGENACQUISTIEST = a2.SCGENACQUISTIEST
			, a1.INESAURIMENTO = a2.INESAURIMENTO
			, a1.ESAURITO = a2.ESAURITO
			, a1.QTAMINCONS = a2.QTAMINCONS
			, a1.USAPREZZIPART = a2.USAPREZZIPART
			, a1.FlagCauzioni = a2.FlagCauzioni
			, a1.FLGBARCODEGENDAPROCAUTOMSTD = a2.FLGBARCODEGENDAPROCAUTOMSTD
			, a1.EXPORTECOMMERCE = a2.EXPORTECOMMERCE
			, a1.CODIVAINTRA = a2.CODIVAINTRA
		--SELECT *
		FROM ANAGRAFICAARTICOLIcomm a1, ANAGRAFICAARTICOLIcomm a2
		WHERE 
			a1.CODICEART = @CODART
			AND a2.CODICEART = @ARTMODELLO
			AND LEFT(a1.CODICEART , 1) = '2'
			AND a1.ESERCIZIO = a2.esercizio
			AND LEFT(a1.CODICEART , 1) = '2'
		
		
		UPDATE a1
		SET a1.SCORTAMIN = a2.scortamin
			, a1.SCORTAMAX = a2.SCORTAMAX
			, a1.LIVPRODUZIONE = a2.LIVPRODUZIONE
			, a1.RAGGRPRODUZIONE =  a1.RAGGRPRODUZIONE
			, a1.LIVPRODPREC = a2.LIVPRODPREC
			, a1.TIPOGESTIONE = a2.TIPOGESTIONE
			, a1.LIVRIORDINO = a2.LIVRIORDINO
			, a1.PROVENIENZA = A2.PROVENIENZA
			, a1.ARTALTERNATIVO =a1.ARTALTERNATIVO
			, a1.QMINRIORDACQ = a2.QMINRIORDACQ
			, a1.QMAXRIORDACQ = a2.QMAXRIORDACQ
			, a1.QDELTARIORDACQ = a2.QDELTARIORDACQ
			, a1.TAPPRONTACQ = a2.TAPPRONTACQ
			, a1.TAPPROVVACQ = a2.TAPPROVVACQ
			, a1.LOTTORIFACQ = a2.LOTTORIFACQ
			, a1.ARROTLOTTOACQ = a2.ARROTLOTTOACQ
			, a1.FORNPREFACQ = a2.FORNPREFACQ
			, a1.QMINRIORDPROD = a2.QMINRIORDPROD
			, a1.QMAXRIORDPROD = a2.QMAXRIORDPROD
			, a1.QDELTARIORDPROD = a2.QDELTARIORDPROD
			, a1.TAPPRONTPROD = a2.TAPPRONTPROD 
			, a1.TAPPROVVPROD = a2.TAPPROVVPROD
			, a1.LOTTORIFPROD = a2.LOTTORIFPROD
			, a1.ARROTLOTTOPROD = a2.ARROTLOTTOPROD
			, a1.QMINRIORDLAV = a2.QMINRIORDLAV
			, a1.QMAXRIORDLAV = a2.QMAXRIORDLAV
			, a1.QDELTARIORDLAV = a2.QDELTARIORDLAV
			, a1.TAPPRONTLAV = a2.TAPPRONTLAV
			, a1.TAPPROVVLAV = a2.TAPPROVVLAV
			, a1.LOTTORIFLAV = a2.LOTTORIFLAV
			, a1.ARROTLOTTOLAV = a2.ARROTLOTTOLAV 
			, a1.FORNPREFLAV = a2.FORNPREFLAV
			, a1.LOTTORIORDINO = a2.LOTTORIORDINO
			, a1.TIPOPRODUZIONE = a2.TIPOPRODUZIONE
			, a1.FLOORSTOCK = a2.FLOORSTOCK
			, a1.GRUPPOAPPROV = a2.GRUPPOAPPROV
			, a1.COSTOORDINEACQ = a2.COSTOORDINEACQ
			, a1.COSTOORDINELAV = a2.COSTOORDINELAV
			, a1.COSTOORDINEPROD = a2.COSTOORDINEPROD
			, a1.FATTORESCOSTAMENTO = a2.FATTORESCOSTAMENTO
			, a1.TEMPOCOPERTURA = a2.TEMPOCOPERTURA
			, a1.CONSUMOPREVISTO = a2.CONSUMOPREVISTO
			, a1.MADPREVISTO = a2.MADPREVISTO
			, a1.FATTORESICUREZZA = a2.TIPOPRODOTTO
			, a1.TIPOPRODOTTO = a2.TIPOPRODOTTO
			, a1.GESTIONEMATERIALI = a2.GESTIONEMATERIALI
			, a1.FATTORECOMPRESSIONE = a2.FATTORECOMPRESSIONE
			, a1.GRUPPOPREVISIONE = a2.GRUPPOPREVISIONE
			, a1.FORMULAFRONTIERA = a2.FORMULAFRONTIERA
			, a1.LIVELLOSERVIZIO = a2.LIVELLOSERVIZIO
			, a1.FLAGMPS = a2.FLAGMPS
			, a1.FLAGNETTIFICAMPS = a2.FLAGNETTIFICAMPS
			, a1.CODICEMPS = a2.CODICEMPS
			, a1.LOTTOFABBRICAZIONE = a2.LOTTOFABBRICAZIONE
			, a1.UMLOTTOFABBRICAZIONE = a2.UMLOTTOFABBRICAZIONE
			, a1.KS_GGScadenza = a2.KS_GGScadenza
			, a1.INTERVALLOPIANIF = a2.INTERVALLOPIANIF
			, a1.DATAULTANALISI = a2.DATAULTANALISI
			, a1.GGORIZZONTEDISP = a2.GGORIZZONTEDISP
		--SELECT *
		FROM ANAGRAFICAARTICOLIPROD a1, ANAGRAFICAARTICOLIPROD a2
		WHERE 
			a1.CODICEART = @CODART
			AND a2.CODICEART = @ARTMODELLO
			AND LEFT(a1.CODICEART , 1) = '2'
			AND a1.ESERCIZIO = a2.esercizio
			AND LEFT(a1.CODICEART , 1) = '2'

		
		
		
		UPDATE a1
		SET A1.ScontiPremi = A2.ScontiPremi 
			, A1.SpTrasp = a2.SpTrasp
			, a1.Provvi = a2.Provvi
			, a1.Imballi = a2.Imballi
			, a1.Amministrazione = a2.Amministrazione
			, a1.SpVendita = a2.SpVendita
			, a1.SpMagazzino = a2.SpMagazzino
			, a1.SpeseProd = a2.SpeseProd
			, a1.CostoAggiunto = a2.CostoAggiunto
			, a1.Preleva = a2.Preleva
			, a1.TestMateriePrime = a2.TestMateriePrime
			, a1.TOL = a2.TOL
			, a1.FLAG_BOLLETTINO = a2.FLAG_BOLLETTINO
			, a1.SCOSTAMENTO_PRZ = a2.SCOSTAMENTO_PRZ
			, a1.XLS_CHEMDES = a2.XLS_CHEMDES
			, a1.XLS_CASNR = a2.XLS_CASNR
			, a1.XLS_ORGGOODS = a2.XLS_ORGGOODS
			, a1.XLS_ORGFORMULA = a2.XLS_ORGFORMULA
			, a1.XLS_VARORGFORMULA = a2.XLS_VARORGFORMULA 
			, a1.XLS_OPDIVISION = a2.XLS_OPDIVISION
			, a1.XLS_COSTDIRWAGES = a2.XLS_COSTDIRWAGES
			, a1.XLS_COSTPRODOVERHEAD = a2.XLS_COSTPRODOVERHEAD
			, a1.XLS_COSTRAWMAT = a2.XLS_COSTRAWMAT
			, a1.XLS_COSTRAWMAT_VEN = a2.XLS_COSTRAWMAT_VEN
			, a1.FLAG_ADR = a2.FLAG_ADR
			, a1.PATH_SCHEDASICUREZZA_ITA = a2.PATH_SCHEDASICUREZZA_ITA
			, a1.PATH_SCHEDASICUREZZA_EST = a2.PATH_SCHEDASICUREZZA_EST
			, a1.MACRO_ART = a2.MACRO_ART
			, a1.PRV_VAR = a2.PRV_VAR
			, a1.BSCKNOS = a2.BSCKNOS
			, a1.FLAG_RSPO = a2.FLAG_RSPO
			, a1.NRPEZZIIMBALLO = @NRPEZZIIMBALLO
		--SELECT *
		FROM EXTRAMAG a1, EXTRAMAG a2
		WHERE 
			a1.CODART = @CODART
			AND a2.CODART = @ARTMODELLO
			AND LEFT(a1.CODART , 1) = '2'
		
		-- LISTINI
		DELETE A1 
		FROM LISTINIARTICOLI A1 
		WHERE a1.CODART = @CODART 
			AND LEFT(@CODART , 1) = '2'
		
		INSERT INTO dbo.LISTINIARTICOLI (CODART, NRLISTINO, UM, PREZZO, PREZZOEURO, UTENTEMODIFICA, DATAMODIFICA, DeltaIncremento, TP_CodConto, TP_ConsPP, TP_PrezzoPart, TP_PrezzoPartEuro, TP_Scorporo, TP_Sconti, TP_QTASCONTO, TP_QTACOEFF, TP_QTAMO, TP_Abbuono, TP_DataCambio, TP_ValoreCambio, DATAVALIDITA, TP_FormulaSct, PREZZOCALC, TP_ABBUONOEURO)
		SELECT @CODART, T.NRLISTINO, UM, PREZZO, PREZZOEURO, 'TRM', GETDATE(), DeltaIncremento, TP_CodConto, TP_ConsPP, TP_PrezzoPart, TP_PrezzoPartEuro, TP_Scorporo, TP_Sconti, TP_QTASCONTO, TP_QTACOEFF, TP_QTAMO, TP_Abbuono, TP_DataCambio, TP_ValoreCambio, DATAVALIDITA, TP_FormulaSct, PREZZOCALC, TP_ABBUONOEURO
		FROM LISTINIARTICOLI t 
		WHERE T.CODART = @ARTMODELLO
			AND LEFT(@CODART , 1) = '2'
			AND NOT EXISTS (SELECT 1 FROM LISTINIARTICOLI x WHERE @CODART = X.CODART AND x.NRLISTINO = T.NRLISTINO)
		
		
		
		DELETE A1 
		FROM CONTROPARTARTICOLI A1 
		WHERE a1.CODART = @CODART 
		
		INSERT INTO dbo.CONTROPARTARTICOLI (CODART, ESERCIZIO, NUMERO, SCGEN, UTENTEMODIFICA, DATAMODIFICA)
		SELECT @CODART, T.ESERCIZIO, T.NUMERO, T.SCGEN, 'TRM', GETDATE()
		FROM CONTROPARTARTICOLI t 
		WHERE T.CODART = @ARTMODELLO
			AND LEFT(@CODART , 1) = '2'



		IF LEFT(@CODART , 1) IN ('3', '4')
		BEGIN
			EXEC ITA_UPDATECODICISOST  @OLDCODART, @CODIMBALLO, @CODART    
			
			
			UPDATE a1
			SET 
				a1.NRPEZZIIMBALLO = @NRPEZZIIMBALLO --a2.NRPEZZIIMBALLO
				, a1.RIFERIMIMBALLO = @CODIMBALLO --(SELECT TOP 1 tabimballi.CODICE FROM TABIMBALLI WHERE tabimballi.VARIANTEIMBALLO = RIGHT(a1.CODICE, 3))
			FROM ANAGRAFICAARTICOLI a1
			WHERE 
				a1.CODICE = @CODART
				AND LEFT(a1.CODICE , 1) IN ('3', '4')	 
			
			UPDATE EXTRAMAG
			SET NRPEZZIIMBALLO = @NRPEZZIIMBALLO	
				
		END
						
		-- inserimento in tabella articoli adr
		INSERT INTO dbo.TAB_ARTICOLIADR (CODART, CLASSEADR, NUMORD, NUMONU, NUMPER, GI, UTENTEMODIFICA, DATAMODIFICA, DESIGN_TRASP, COD_GALLERIE, ESENZIONE_QTA)
		SELECT @CODART, CLASSEADR, NUMORD, NUMONU, NUMPER, GI, 'trm', getdate(), DESIGN_TRASP, COD_GALLERIE, ESENZIONE_QTA
		FROM TAB_ARTICOLIADR t 
		WHERE (t.CODART = @ARTMODELLO OR t.CODART = @OLDCODART)
		AND @CODART NOT IN (SELECT x.codart FROM TAB_ARTICOLIADR x)	  
		
		-- AGGIORNAMENTO RIGHEDOCUMENTI

		SELECT r.CODART, r.CODIMBALLO, e.NUOVOCODART, t.DESCRIZIONE, a.DESCRIZIONE, r.IDTESTA, r.IDRIGA		
		
		UPDATE r
		SET r.CODART = e.NUOVOCODART
		
		FROM RIGHEDOCUMENTI r 
		JOIN tabimballi t ON t.CODICE = r.CODIMBALLO
		JOIN ZS_GENERAARTICOLI e ON e.CODART = r.CODART AND e.CODICE = R.CODIMBALLO
		JOIN anagraficaarticoli a ON a.CODICE = e.NUOVOCODART
		
		
		-- AGGIORNAMENTO STORICOMAG
		--SELECT S.CODART, S.RIFERIMENTI, t.DESCRIZIONE, a.DESCRIZIONE, r.IDTESTA, r.IDRIGA
		
		UPDATE r SET r.CODART = e.NUOVOCODART
		
		FROM RIGHEDOCUMENTI r JOIN STORICOMAG S ON S.IDTESTA = R.IDTESTA AND S.RIGADOC = R.IDRIGA
		JOIN tabimballi t ON t.CODICE = r.CODIMBALLO
		JOIN ZS_GENERAARTICOLI e ON e.CODART = r.CODART AND e.CODICE = R.CODIMBALLO
		JOIN anagraficaarticoli a ON a.CODICE = e.NUOVOCODART
		
		
		
		
		
		
		
			

	END
END
GO

GRANT EXECUTE ON dbo.ZS_GENERAARTICOLO_POST TO Metodo98
GO


