IF OBJECT_ID ('dbo.ITA_CODICISOST') IS NOT NULL
	DROP TABLE dbo.ITA_CODICISOST
GO

CREATE TABLE dbo.ITA_CODICISOST
	(
	SEL            SMALLINT,
	TABELLA        VARCHAR (80) NOT NULL,
	CAMPO          VARCHAR (80) NOT NULL,
	UtenteModifica VARCHAR (25) NOT NULL,
	DataModifica   DATETIME NOT NULL,
	PRIMARY KEY (TABELLA, CAMPO)
	WITH (FILLFACTOR = 90)
	)
GO

GRANT DELETE ON dbo.ITA_CODICISOST TO Metodo98
GO
GRANT INSERT ON dbo.ITA_CODICISOST TO Metodo98
GO
GRANT REFERENCES ON dbo.ITA_CODICISOST TO Metodo98
GO
GRANT SELECT ON dbo.ITA_CODICISOST TO Metodo98
GO
GRANT UPDATE ON dbo.ITA_CODICISOST TO Metodo98
GO





IF OBJECT_ID ('dbo.ITA_FILLCODICISOST') IS NOT NULL
	DROP PROCEDURE dbo.ITA_FILLCODICISOST
GO

CREATE PROCEDURE ITA_FILLCODICISOST AS
	DECLARE @CSQL AS VARCHAR(5000)
	DECLARE @N AS SMALLINT
	DECLARE @NOMECAMPO AS VARCHAR(80)
	DECLARE @NOMETABELLA AS VARCHAR(80)

	DECLARE rSqlA CURSOR LOCAL KEYSET FOR 
	SELECT C.COLUMN_NAME, C.TABLE_NAME
	FROM INFORMATION_SCHEMA.COLUMNS C JOIN INFORMATION_SCHEMA.TABLES T ON T.TABLE_NAME = C.TABLE_NAME
	WHERE TABLE_TYPE <> 'VIEW' AND DATA_TYPE LIKE '%CHAR%' AND CHARACTER_MAXIMUM_LENGTH >= 50 AND 
	LEFT(C.TABLE_NAME,1) <> 'W' AND  LEFT(C.TABLE_NAME,3) <> 'TMP' AND LEFT(C.TABLE_NAME,4) <> 'TEMP' AND
	C.COLUMN_NAME NOT LIKE '%DESCR%' AND C.COLUMN_NAME NOT LIKE '%NOT%' AND C.COLUMN_NAME NOT LIKE '%DSC%' AND
	C.COLUMN_NAME NOT LIKE '%INDIR%' AND C.COLUMN_NAME NOT LIKE '%LOCAL%' AND C.COLUMN_NAME NOT LIKE '%FORMULA%' AND
	C.COLUMN_NAME NOT LIKE '%RAGS%' AND C.COLUMN_NAME NOT LIKE '%CALCOLO%' AND C.COLUMN_NAME <> 'CODICEPRIMARIO' AND
	C.COLUMN_NAME NOT LIKE '%AGE%' AND C.COLUMN_NAME NOT LIKE '%ATT%' AND C.COLUMN_NAME NOT LIKE '%CAMPO%' AND
	C.COLUMN_NAME NOT LIKE '%CAUS%' AND C.COLUMN_NAME NOT LIKE '%DESP%' AND C.COLUMN_NAME NOT LIKE '%DESUM%' AND
	C.COLUMN_NAME NOT LIKE '%NOME%' AND C.COLUMN_NAME NOT LIKE '%TIPI%' AND C.COLUMN_NAME NOT LIKE '%INTESTA%' 
	ORDER BY C.COLUMN_NAME
	OPEN rSqlA

	FETCH NEXT from rSqlA INTO @NOMECAMPO, @NOMETABELLA
	WHILE (@@FETCH_STATUS <> -1)
		BEGIN
		
			SELECT @N = COUNT(*) FROM ITA_CODICISOST WHERE TABELLA = @NOMETABELLA AND CAMPO = @NOMECAMPO
			
			IF @N = 0
			BEGIN

				IF @NOMETABELLA = 'RELAZIONICFV' AND ( @NOMECAMPO = 'ARTICOLO' OR @NOMECAMPO = 'VARIANTI' )

					BEGIN
				
						INSERT INTO ITA_CODICISOST VALUES (1, @NOMETABELLA, @NOMECAMPO, '', getdate() )

					END
				
				ELSE

					BEGIN
						SET @CSQL = 'SELECT DISTINCT [' + @NOMECAMPO + '] FROM ' + @NOMETABELLA + ' WHERE ISNULL([' + @NOMECAMPO + '],'''') <> '''' '
						--PRINT @CSQL
						EXEC (@CSQL)
						IF @@ROWCOUNT > 0
						BEGIN

							SET @CSQL = 'SELECT TOP 1 ''A'' FROM ' + @NOMETABELLA + ' WHERE [' + @NOMECAMPO + '] IN (SELECT CODICE FROM ANAGRAFICAARTICOLI) AND ISNULL([' + @NOMECAMPO + '],'''') <> '''' ' 
							--PRINT @CSQL
							EXEC (@CSQL)

							IF @@ROWCOUNT <> 0
							BEGIN

								INSERT INTO ITA_CODICISOST VALUES (1, @NOMETABELLA, @NOMECAMPO, '', getdate() )

								--PRINT @NOMETABELLA + ' ' + @NOMECAMPO				

							END

						END
					END				
			
			END
	
			FETCH NEXT from rSqlA INTO @NOMECAMPO, @NOMETABELLA
		END

	CLOSE rSqlA
	DEALLOCATE rSqlA

GO

GRANT EXECUTE ON dbo.ITA_FILLCODICISOST TO Metodo98
GO

EXEC ITA_FILLCODICISOST
GO

SELECT * FROM ITA_CODICISOST




IF OBJECT_ID ('dbo.ZS_GENERAARTICOLI') IS NOT NULL
	DROP TABLE dbo.ZS_GENERAARTICOLI
GO

CREATE TABLE dbo.ZS_GENERAARTICOLI
	(
	ARTTIPOLOGIA    VARCHAR (50),
	CODART          VARCHAR (50),
	CODICE          VARCHAR (10) NOT NULL,
	DESCRIZIONE	VARCHAR(500),
	VARIANTEIMBALLO VARCHAR (25),
	NUOVOCODART          VARCHAR (50) NOT NULL,
	UtenteModifica       VARCHAR (25) NOT NULL,
	DataModifica         DATETIME NOT NULL,
	PRIMARY KEY (NUOVOCODART,CODICE)
	)
GO

GRANT DELETE ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO
GRANT INSERT ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO
GRANT REFERENCES ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO
GRANT SELECT ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO
GRANT UPDATE ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO




IF OBJECT_ID ('dbo.ZS_GENERAARTICOLI_POST') IS NOT NULL
	DROP TABLE dbo.ZS_GENERAARTICOLI_POST
GO

CREATE TABLE dbo.ZS_GENERAARTICOLI_POST
	(
	CODART          VARCHAR (50) NOT NULL,
	NUOVOCODART          VARCHAR (50) NOT NULL,
	UtenteModifica       VARCHAR (25) NOT NULL,
	DataModifica         DATETIME NOT NULL,
	PRIMARY KEY (NUOVOCODART,CODART)
	)
GO

GRANT DELETE ON dbo.ZS_GENERAARTICOLI_POST TO Metodo98
GO
GRANT INSERT ON dbo.ZS_GENERAARTICOLI_POST TO Metodo98
GO
GRANT REFERENCES ON dbo.ZS_GENERAARTICOLI_POST TO Metodo98
GO
GRANT SELECT ON dbo.ZS_GENERAARTICOLI_POST TO Metodo98
GO
GRANT UPDATE ON dbo.ZS_GENERAARTICOLI_POST TO Metodo98
GO



IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI
GO

CREATE VIEW ZS_VISTA_GENERAARTICOLI
AS

SELECT *, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WHERE A.CODICE = CTE.CODART OR A.CODICE = CTE.ARTTIPOLOGIA) AS DESCRIZIONE FROM (
	SELECT distinct
	(CASE WHEN charindex('#', g.CODART) > 1 THEN LEFT(g.CODART, charindex('#', g.CODART) - 1) ELSE g.CODART END) AS ARTTIPOLOGIA
	, g.CODART
	, t.CODICE
	, t.varianteimballo
	, (CASE 
		WHEN charindex('#', g.CODART) > 0 AND charindex('?', g.codart) = 0 THEN LEFT(g.CODART, charindex('#', g.CODART) + 3) + T.VARIANTEIMBALLO 
		WHEN charindex('#', g.CODART) > 0 AND charindex('?', g.codart) > 0 THEN LEFT(g.CODART, charindex('#', g.CODART)) + '000' + T.VARIANTEIMBALLO 
		ELSE
			g.CODART + '#000' + T.VARIANTEIMBALLO 
		END) AS NUOVOCODART
		--, g.*
	FROM GESTIONEPREZZI g JOIN GESTIONEPREZZIRIGHE r ON g.PROGRESSIVO = r.RIFPROGRESSIVO
	JOIN tabimballi t ON t.CODICE = r.cod_imballo 
	JOIN TABVARIANTI v ON v.VARIANTE = t.varianteimballo
	WHERE g.INIZIOVALIDITA = g.FINEVALIDITA and t.varianteimballo  <> '' --AND charindex('?', g.codart) = 0
	AND t.codice NOT IN (100, 101)
	) CTE
WHERE 
	NUOVOCODART NOT IN (SELECT CODICE FROM ANAGRAFICAARTICOLI)
	AND ARTTIPOLOGIA BETWEEN '20000' AND '49999'

GO

GRANT ALL ON ZS_VISTA_GENERAARTICOLI TO metodo98
GO




IF OBJECT_ID ('dbo.ZS_GENERAARTICOLO_PRE') IS NOT NULL
	DROP PROCEDURE dbo.ZS_GENERAARTICOLO_PRE
GO

CREATE PROCEDURE ZS_GENERAARTICOLO_PRE(@CODART VARCHAR(50)) AS
BEGIN
 
	DECLARE @ARTPADRE VARCHAR(50)
	
	SET @ARTPADRE = LEFT(@CODART, CHARINDEX('#' , @CODART) -1)
	
	-- TRASFORMO PUNTUALE IN TIPOLOGIE A VARIANTI
	UPDATE ANAGRAFICAARTICOLI SET ARTTIPOLOGIA = 1 WHERE CODICE = @ARTPADRE AND ARTTIPOLOGIA = 0
	
	INSERT INTO dbo.TIPOLOGIEARTICOLI (CODICEART, NUMEROTIP, CODTIPOLOGIA, SELVARIANTI, AGGIUNGIDES, UTENTEMODIFICA, DATAMODIFICA)
	SELECT @ARTPADRE, 1, 'PE', 1, 0, 'trm1', getdate() FROM TABDITTE WHERE NOT EXISTS(SELECT 1 FROM TIPOLOGIEARTICOLI x WHERE x.CODICEART = @ARTPADRE AND x.CODTIPOLOGIA = 'PE')

	INSERT INTO dbo.TIPOLOGIEARTICOLI (CODICEART, NUMEROTIP, CODTIPOLOGIA, SELVARIANTI, AGGIUNGIDES, UTENTEMODIFICA, DATAMODIFICA)
	SELECT @ARTPADRE, 2, '62', 1, 0, 'trm1', getdate() FROM TABDITTE WHERE NOT EXISTS(SELECT 1 FROM TIPOLOGIEARTICOLI x WHERE x.CODICEART = @ARTPADRE AND x.CODTIPOLOGIA = '62')


	
	INSERT INTO dbo.VARIANTIARTICOLI (CODICEART, NUMEROTIP, VARIANTE, TIPOLOGIA, SOLOSE, UTENTEMODIFICA, DATAMODIFICA)
	SELECT @ARTPADRE, 1, '000', 'PE', '', 'trm1', GETDATE() FROM TABDITTE
	WHERE NOT EXISTS(SELECT 1 FROM VARIANTIARTICOLI x WHERE x.CODICEART = @ARTPADRE AND VARIANTE = '000' AND tipologia = 'PE')

	
	INSERT INTO dbo.VARIANTIARTICOLI (CODICEART, NUMEROTIP, VARIANTE, TIPOLOGIA, SOLOSE, UTENTEMODIFICA, DATAMODIFICA)
	SELECT DISTINCT  ARTTIPOLOGIA, 2, varianteimballo, '62', '', 'trm', getdate() FROM ZS_VISTA_GENERAARTICOLI
	WHERE ARTTIPOLOGIA = @ARTPADRE AND NOT EXISTS(SELECT 1 FROM VARIANTIARTICOLI x WHERE x.CODICEART = ARTTIPOLOGIA AND VARIANTE = varianteimballo AND tipologia = '62')
	
	UPDATE TIPOLOGIEARTICOLI SET AGGIUNGIDES = 1, SELVARIANTI = 1 WHERE CODTIPOLOGIA = '62' AND CODICEART = @ARTPADRE

END

GO

GRANT EXECUTE ON ZS_GENERAARTICOLO_PRE TO METODO98
GO





-- POST






IF OBJECT_ID ('dbo.ZS_GENERAARTICOLI_GESTIONEPREZZI') IS NOT NULL
	DROP PROCEDURE dbo.ZS_GENERAARTICOLI_GESTIONEPREZZI
GO

CREATE PROCEDURE ZS_GENERAARTICOLI_GESTIONEPREZZI(@CODART VARCHAR(50), @OLDCODART VARCHAR(50)) AS
	DECLARE @CSQL AS VARCHAR(5000)
	DECLARE @N AS SMALLINT
	DECLARE @NOMECAMPO AS VARCHAR(80)
	DECLARE @NOMETABELLA AS VARCHAR(80)
	
	DECLARE @PROGRESSIVO AS DECIMAL(10)
	DECLARE @IDRIGA DECIMAL(10)
	DECLARE @PPROG DECIMAL (10)
	DECLARE @PIDRIGA DECIMAL (10)
	DECLARE @IMBALLO AS VARCHAR(10)
	
	DELETE FROM GESTIONEPREZZI WHERE CODART = @CODART AND CODCLIFOR = 'C' AND INIZIOVALIDITA = FINEVALIDITA

	DECLARE rSqlA CURSOR LOCAL KEYSET FOR 
	SELECT G.PROGRESSIVO, R.IDRIGA, r.COD_IMBALLO
	FROM GESTIONEPREZZI g JOIN GESTIONEPREZZIRIGHE r ON g.PROGRESSIVO = r.RIFPROGRESSIVO
	JOIN TABIMBALLI T ON T.CODICE = R.COD_IMBALLO
	WHERE g.INIZIOVALIDITA = g.FINEVALIDITA  --AND charindex('?', g.codart) = 0
	AND g.CODART = @OLDCODART AND T.VARIANTEIMBALLO = RIGHT(@CODART, 3)
	
	
	
	
	OPEN rSqlA

	FETCH NEXT from rSqlA INTO @PROGRESSIVO, @IDRIGA, @IMBALLO
	WHILE (@@FETCH_STATUS <> -1)
		BEGIN
		
			PRINT @PROGRESSIVO
			PRINT @IDRIGA
			PRINT @IMBALLO
			
			SELECT @PPROG = 0

			SELECT TOP 1 @PPROG = X.PROGRESSIVO 
			FROM GESTIONEPREZZI X WHERE X.CODART = @CODART AND X.INIZIOVALIDITA = X.FINEVALIDITA
			
			IF (@PPROG = 0)
			BEGIN

				
				EXECUTE dbo.NUOVOPROGRESSIVO 'GESTIONEPREZZI', 1, @PPROG OUT
				SELECT "@PPROG" = @PPROG
	
				INSERT INTO dbo.GESTIONEPREZZI (PROGRESSIVO, CODGRUPPOPREZZICF, CODCLIFOR, CODART, CODGRUPPOPREZZIMAG, INIZIOVALIDITA, FINEVALIDITA, USANRLISTINO, TIPOARROT, ARROTALIRE, ARROTAEURO, CODARTRIC, UTENTEMODIFICA, DATAMODIFICA, PROGRESSIVOCTR)
				SELECT @PPROG, CODGRUPPOPREZZICF, CODCLIFOR, @CODART, CODGRUPPOPREZZIMAG, INIZIOVALIDITA, FINEVALIDITA, USANRLISTINO, TIPOARROT, ARROTALIRE, ARROTAEURO, @CODART, UTENTEMODIFICA, DATAMODIFICA, PROGRESSIVOCTR
				FROM GESTIONEPREZZI 
				WHERE PROGRESSIVO = @PROGRESSIVO 
				AND NOT EXISTS(SELECT 1 FROM GESTIONEPREZZI X WHERE X.CODART = @CODART AND X.INIZIOVALIDITA = X.FINEVALIDITA) 
	 		
			END
			
	 			   
	 
			EXECUTE dbo.NUOVOPROGRESSIVO 'GESTIONEPREZZIRIGHE', 1, @PIDRIGA OUT
			SELECT "@PIDRIGA" = @PIDRIGA  
					
			INSERT INTO dbo.GESTIONEPREZZIRIGHE (IDRIGA, RIFPROGRESSIVO, NRLISTINO, UM, QTAMINIMA, PREZZO_MAGG, PREZZO_MAGGEURO, SCONTO_UNICO, SCONTO_AGGIUNTIVO, TIPO, UTENTEMODIFICA, DATAMODIFICA, TP_QTASCONTO, TP_QTACOEFF, COD_IMBALLO, QTA_COLLI)
			SELECT @PIDRIGA, @PPROG, NRLISTINO, UM, QTAMINIMA, PREZZO_MAGG, PREZZO_MAGGEURO, SCONTO_UNICO, SCONTO_AGGIUNTIVO, TIPO, UTENTEMODIFICA, DATAMODIFICA, TP_QTASCONTO, TP_QTACOEFF, COD_IMBALLO, QTA_COLLI
			FROM GESTIONEPREZZIRIGHE 
			WHERE RIFPROGRESSIVO = @PROGRESSIVO AND IDRIGA = @IDRIGA 
			--AND NOT EXISTS(SELECT 1 FROM GESTIONEPREZZIRIGHE X WHERE X.CODART = @CODART AND X.COD_IMBALLO = @IMBALLO AND X.INIZIOVALIDITA = X.FINEVALIDITA) 
	  	



			
			
			
			FETCH NEXT from rSqlA INTO @PROGRESSIVO, @IDRIGA, @IMBALLO
		END

	CLOSE rSqlA
	DEALLOCATE rSqlA
GO

GRANT EXECUTE ON dbo.ZS_GENERAARTICOLI_GESTIONEPREZZI TO Metodo98
GO



IF OBJECT_ID ('dbo.ZS_GENERAARTICOLO_POST') IS NOT NULL
	DROP PROCEDURE dbo.ZS_GENERAARTICOLO_POST
GO

CREATE PROCEDURE ZS_GENERAARTICOLO_POST(@CODART VARCHAR(50), @OLDCODART VARCHAR(50)) AS
BEGIN
 
	DECLARE @ARTPADRE VARCHAR(50)
	
	SET @ARTPADRE = LEFT(@CODART, CHARINDEX('#' , @CODART) -1)

	IF (NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST WHERE CODART = @OLDCODART AND NUOVOCODART = @CODART))
	BEGIN
		INSERT INTO dbo.ZS_GENERAARTICOLI_POST (CODART, NUOVOCODART, UtenteModifica, DataModifica)
		VALUES (@OLDCODART, @CODART, 'TRM', GETDATE())
		--SELECT @OLDCODART, @CODART, 'TRM', GETDATE() FROM TABDITTE WHERE NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST WHERE CODART = @OLDCODART AND NUOVOCODART = @CODART)
	
		EXEC ZS_GENERAARTICOLI_GESTIONEPREZZI @CODART, @OLDCODART

	END
END

GO

GRANT EXECUTE ON ZS_GENERAARTICOLO_POST TO METODO98
GO

