SELECT a.CODICE, a.DESCRIZIONE, a.RIFERIMIMBALLO, a.NRPEZZIIMBALLO, t.CODICE, t.QTA_COLLI 
--UPDATE a SET a.NRPEZZIIMBALLO = t.QTA_COLLI 
FROM ANAGRAFICAARTICOLI a JOIN TABIMBALLI t ON t.CODICE = a.RIFERIMIMBALLO 
--WHERE a.CODICE LIKE '20021%'
WHERE 
	charindex('#', a.codice) > 0 and
	isnull(a.NRPEZZIIMBALLO, 0) = 0 AND t.QTA_COLLI > 0
	
SELECT * FROM VISTAGESTIONEPREZZI v WHERE v.CODART like '22068#%'



SELECT * FROM GESTIONEPREZZIRIGHE WHERE RIFPROGRESSIVO = 33788