
UPDATE RELAZIONICFV 
SET VARIANTI = REPLACE(VARIANTI, 'XXX', '???')
WHERE RIGHT(VARIANTI, 3) = 'XXX' AND LEFT(CODCLIFOR, 1) = 'C'
GO

UPDATE EXTRAMAG
SET ESAURITO = 'S'
 WHERE RIGHT(codart, 3) = 'XXX' AND ISNULL(ESAURITO, '') <> 'S'
GO


IF OBJECT_ID ('dbo.fn_GetRelazioneCFVGenerica') IS NOT NULL
	DROP FUNCTION dbo.fn_GetRelazioneCFVGenerica
GO

CREATE FUNCTION dbo.fn_GetRelazioneCFVGenerica
(
	-- Add the parameters for the function here
   @CODCLIFOR VARCHAR(7), @CODART VARCHAR(50)
)
RETURNS TABLE
AS
RETURN 
(
	SELECT * FROM RELAZIONICFV RCFV WHERE CODCLIFOR = @CODCLIFOR AND @CODART = (CASE PATINDEX('%#%', @CODART) 
	  	WHEN 0 THEN RCFV.ARTICOLO 
	  	ELSE (RCFV.ARTICOLO + '#' + RCFV.VARIANTI) 
	  	END) 
	union

	SELECT * FROM RELAZIONICFV RCFV WHERE CODCLIFOR = @CODCLIFOR AND PATINDEX(ARTICOLO + (CASE WHEN VARIANTI <> '' THEN '#' + REPLACE(VARIANTI, '???', '_') ELSE '' END)  + '%', @CODART) > 0
 
 )

GO


GRANT REFERENCES ON dbo.fn_GetRelazioneCFVGenerica TO Metodo98
GO


IF OBJECT_ID ('dbo.ITA_GetDscVariante') IS NOT NULL
	DROP FUNCTION dbo.ITA_GetDscVariante
GO

create FUNCTION ITA_GetDscVariante 
	(@Articolo VARCHAR(50), 
	 @Tipologia VARCHAR(8))
RETURNS VARCHAR(80)
AS
BEGIN
	DECLARE @VARESPLICITE AS VARCHAR(255)
	DECLARE @STARTSEARCH int
	DECLARE @LENSEARCH int
	DECLARE @CodVar as VARCHAR(8)
	DECLARE @DscVar as VARCHAR(80)
	
	SELECT @CodVar ='', @DscVar = ''
	
	IF @Tipologia <> '' and @Articolo <> ''
		BEGIN
			SELECT TOP 1  @VARESPLICITE = VARESPLICITE FROM ANAGRAFICAARTICOLI WITH (nolock) WHERE CODICE = @ARTICOLO AND NOT(VARESPLICITE IS NULL)
			SELECT @STARTSEARCH = CHARINDEX(';' + @TIPOLOGIA, @VARESPLICITE)+LEN(@TIPOLOGIA)+2
			SELECT @LENSEARCH =CHARINDEX(';',SUBSTRING(@VARESPLICITE, @STARTSEARCH,255))-1
			
			IF @LENSEARCH > 1
			BEGIN
				SELECT @CodVar = SUBSTRING(@VARESPLICITE, @STARTSEARCH, @LENSEARCH)
				SELECT TOP 1 @DscVar = DESCRIZIONE FROM TABVARIANTI WITH (nolock) WHERE TIPOLOGIA = @TIPOLOGIA AND VARIANTE = @CODVAR
			END
		END
		RETURN @DscVar	
END
GO

GRANT EXECUTE ON dbo.ITA_GetDscVariante TO Metodo98
GO

GRANT REFERENCES ON dbo.ITA_GetDscVariante TO Metodo98
GO



-- old
IF OBJECT_ID ('dbo.VistaRelazioniCFVdaDocZSI') IS NOT NULL
	DROP VIEW dbo.VistaRelazioniCFVdaDocZSI
GO

CREATE VIEW VistaRelazioniCFVdaDocZSI AS 

SELECT
     TD.PROGRESSIVO,
     RD.IDRIGA,
     RCFV.CODCLIFOR,RCFV.RIFERIMENTO,RCFV.ARTICOLO,RCFV.VARIANTI,RCFV.DESCRIZIONE,RCFV.TIPOREL,RCFV.MOSTRAVARIANTI,RCFV.CAPITOLATO,RCFV.SPECIFICAACQ,
     RCFV.NOTE,RCFV.CODBONUS
     , RD.CODART, RD.DESCRIZIONEART
     , dbo.ITA_GetDscVariante(rd.CODART, 62) AS DSCVARIMB
     , replace(rd.descrizioneart, dbo.ITA_GetDscVariante(rd.CODART, 62), '') AS DESCRIZIONERIGA
     --, (CASE WHEN CHARINDEX('#', RD.CODART) > 0 THEN LEFT(RD.CODART, LEN(RD.CODART) -3) ELSE RD.CODART END) AS CODARTRIGA
     , (CASE WHEN TD.ESERCIZIO < 2018 THEN ISNULL((SELECT TOP 1 Z.CODART FROM ZS_GENERAARTICOLI_POST Z WHERE Z.NUOVOCODART = RD.CODART), RD.CODART)
     	ELSE

--     		(CASE 
--     			WHEN TD.TIPODOC IN ('OCG', 'OCC', 'OCE') AND CHARINDEX('#', RD.CODART) > 0 THEN LEFT(RD.CODART, LEN(RD.CODART) -3) 
--     			WHEN TD.TIPODOC IN ('OCG', 'OCC', 'OCE') AND CHARINDEX('#', RD.CODART) = 0 THEN RD.CODART
--     			WHEN TD.TIPODOC NOT IN ('OCG', 'OCC', 'OCE') THEN RD.CODART
--     		ELSE
--     			RD.CODART 
--     		END)

     		RD.CODART
     	END) AS CODARTRIGA
     , TD.TIPODOC
 FROM
     TESTEDOCUMENTI TD INNER JOIN RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA
     LEFT OUTER JOIN RELAZIONICFV RCFV ON RD.CODART = 
          (CASE PATINDEX('%#%', RD.CODART) 
          	WHEN 0 THEN RCFV.ARTICOLO 
          	ELSE (RCFV.ARTICOLO + '#' + RCFV.VARIANTI) END) 
 AND TD.CODCLIFOR = RCFV.CODCLIFOR
/*
 SELECT
     TD.PROGRESSIVO,
     RD.IDRIGA,
     RCFV.CODCLIFOR,RCFV.RIFERIMENTO,RCFV.ARTICOLO,RCFV.VARIANTI,RCFV.DESCRIZIONE,RCFV.TIPOREL,RCFV.MOSTRAVARIANTI,RCFV.CAPITOLATO,RCFV.SPECIFICAACQ,
     RCFV.NOTE,RCFV.CODBONUS
     , RD.CODART, RD.DESCRIZIONEART
     , dbo.ITA_GetDscVariante(rd.CODART, 62) AS DSCVARIMB
     , replace(rd.descrizioneart, dbo.ITA_GetDscVariante(rd.CODART, 62), '') AS DESCRIZIONERIGA
     --, (CASE WHEN CHARINDEX('#', RD.CODART) > 0 THEN LEFT(RD.CODART, LEN(RD.CODART) -3) ELSE RD.CODART END) AS CODARTRIGA
     , (CASE WHEN TD.ESERCIZIO < 2018 THEN ISNULL((SELECT TOP 1 Z.CODART FROM ZS_GENERAARTICOLI_POST Z WHERE Z.NUOVOCODART = RD.CODART), RD.CODART)
     	ELSE
     		RD.CODART
     	END) AS CODARTRIGA
     , TD.TIPODOC
 FROM
     TESTEDOCUMENTI TD, RIGHEDOCUMENTI RD 
     , RELAZIONICFV RCFV 

WHERE TD.PROGRESSIVO = RD.IDTESTA 
 AND TD.CODCLIFOR = RCFV.CODCLIFOR
 AND (PATINDEX(ARTICOLO + (CASE WHEN RCFV.VARIANTI <> '' THEN '#' + REPLACE(RCFV.VARIANTI, '???', '_') ELSE '' END)  + '%', rd.codart) > 0 
 OR
 ARTICOLO + (CASE WHEN RCFV.VARIANTI <> '' THEN '#' + RCFV.VARIANTI ELSE '' END) = RD.CODART
 )
*/
GO

GRANT SELECT ON dbo.VistaRelazioniCFVdaDocZSI TO Metodo98
GO

--OLD


IF OBJECT_ID ('dbo.VistaRelazioniCFVdaDocZSI') IS NOT NULL
	DROP VIEW dbo.VistaRelazioniCFVdaDocZSI
GO

CREATE VIEW VistaRelazioniCFVdaDocZSI AS 
/*
SELECT
     TD.PROGRESSIVO,
     RD.IDRIGA,
     RCFV.CODCLIFOR,RCFV.RIFERIMENTO,RCFV.ARTICOLO,RCFV.VARIANTI,RCFV.DESCRIZIONE,RCFV.TIPOREL,RCFV.MOSTRAVARIANTI,RCFV.CAPITOLATO,RCFV.SPECIFICAACQ,
     RCFV.NOTE,RCFV.CODBONUS
     , RD.CODART, RD.DESCRIZIONEART
     , dbo.ITA_GetDscVariante(rd.CODART, 62) AS DSCVARIMB
     , replace(rd.descrizioneart, dbo.ITA_GetDscVariante(rd.CODART, 62), '') AS DESCRIZIONERIGA
     --, (CASE WHEN CHARINDEX('#', RD.CODART) > 0 THEN LEFT(RD.CODART, LEN(RD.CODART) -3) ELSE RD.CODART END) AS CODARTRIGA
     , (CASE WHEN TD.ESERCIZIO < 2018 THEN ISNULL((SELECT TOP 1 Z.CODART FROM ZS_GENERAARTICOLI_POST Z WHERE Z.NUOVOCODART = RD.CODART), RD.CODART)
     	ELSE

--     		(CASE 
--     			WHEN TD.TIPODOC IN ('OCG', 'OCC', 'OCE') AND CHARINDEX('#', RD.CODART) > 0 THEN LEFT(RD.CODART, LEN(RD.CODART) -3) 
--     			WHEN TD.TIPODOC IN ('OCG', 'OCC', 'OCE') AND CHARINDEX('#', RD.CODART) = 0 THEN RD.CODART
--     			WHEN TD.TIPODOC NOT IN ('OCG', 'OCC', 'OCE') THEN RD.CODART
--     		ELSE
--     			RD.CODART 
--     		END)

     		RD.CODART
     	END) AS CODARTRIGA
     , TD.TIPODOC
 FROM
     TESTEDOCUMENTI TD INNER JOIN RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA
     LEFT OUTER JOIN RELAZIONICFV RCFV ON RD.CODART = 
          (CASE PATINDEX('%#%', RD.CODART) 
          	WHEN 0 THEN RCFV.ARTICOLO 
          	ELSE (RCFV.ARTICOLO + '#' + RCFV.VARIANTI) END) 
 AND TD.CODCLIFOR = RCFV.CODCLIFOR
 */

SELECT
     TD.PROGRESSIVO,
     RD.IDRIGA,
     RCFV.CODCLIFOR,RCFV.RIFERIMENTO,RCFV.ARTICOLO,RCFV.VARIANTI,RCFV.DESCRIZIONE,RCFV.TIPOREL,RCFV.MOSTRAVARIANTI,RCFV.CAPITOLATO,RCFV.SPECIFICAACQ,
     RCFV.NOTE,RCFV.CODBONUS
     , RD.CODART, RD.DESCRIZIONEART
     , dbo.ITA_GetDscVariante(rd.CODART, 62) AS DSCVARIMB
     , replace(rd.descrizioneart, dbo.ITA_GetDscVariante(rd.CODART, 62), '') AS DESCRIZIONERIGA
     --, (CASE WHEN CHARINDEX('#', RD.CODART) > 0 THEN LEFT(RD.CODART, LEN(RD.CODART) -3) ELSE RD.CODART END) AS CODARTRIGA
     , (CASE WHEN TD.ESERCIZIO < 2018 THEN ISNULL((SELECT TOP 1 Z.CODART FROM ZS_GENERAARTICOLI_POST Z WHERE Z.NUOVOCODART = RD.CODART), RD.CODART)
     	ELSE

--     		(CASE 
--     			WHEN TD.TIPODOC IN ('OCG', 'OCC', 'OCE') AND CHARINDEX('#', RD.CODART) > 0 THEN LEFT(RD.CODART, LEN(RD.CODART) -3) 
--     			WHEN TD.TIPODOC IN ('OCG', 'OCC', 'OCE') AND CHARINDEX('#', RD.CODART) = 0 THEN RD.CODART
--     			WHEN TD.TIPODOC NOT IN ('OCG', 'OCC', 'OCE') THEN RD.CODART
--     		ELSE
--     			RD.CODART 
--     		END)

     		RD.CODART
     	END) AS CODARTRIGA
     , TD.TIPODOC
 FROM
     TESTEDOCUMENTI TD INNER JOIN RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA
     LEFT OUTER JOIN RELAZIONICFV RCFV 
     ON RD.CODART = 
          (CASE PATINDEX('%#%', RD.CODART) 
          	WHEN 0 THEN RCFV.ARTICOLO 
          	ELSE (RCFV.ARTICOLO + '#' + RCFV.VARIANTI) END) AND TD.CODCLIFOR = RCFV.CODCLIFOR
      OR (
      (PATINDEX(ARTICOLO + (CASE WHEN RCFV.VARIANTI <> '' AND CHARINDEX('?', RCFV.VARIANTI) > 0 THEN '#' + REPLACE(RCFV.VARIANTI, '???', '%') ELSE '' END), rd.codart) > 0 
 OR
 ARTICOLO + (CASE WHEN RCFV.VARIANTI <> '' THEN '#' + RCFV.VARIANTI ELSE '' END) = RD.CODART
  )AND TD.CODCLIFOR = RCFV.CODCLIFOR
     
      
      
      )
GO

GRANT SELECT ON dbo.VistaRelazioniCFVdaDocZSI TO Metodo98
GO





IF OBJECT_ID ('dbo.VistaRelazioniCFVdaDocZSIX') IS NOT NULL
	DROP VIEW dbo.VistaRelazioniCFVdaDocZSIX
GO

CREATE VIEW VistaRelazioniCFVdaDocZSIX AS 

 SELECT
     TD.PROGRESSIVO,
     RD.IDRIGA,
     RCFV.CODCLIFOR,RCFV.RIFERIMENTO,RCFV.ARTICOLO,RCFV.VARIANTI,RCFV.DESCRIZIONE,RCFV.TIPOREL,RCFV.MOSTRAVARIANTI,RCFV.CAPITOLATO,RCFV.SPECIFICAACQ,
     RCFV.NOTE,RCFV.CODBONUS
     , RD.CODART, RD.DESCRIZIONEART
     , dbo.ITA_GetDscVariante(rd.CODART, 62) AS DSCVARIMB
     , replace(rd.descrizioneart, dbo.ITA_GetDscVariante(rd.CODART, 62), '') AS DESCRIZIONERIGA
     --, (CASE WHEN CHARINDEX('#', RD.CODART) > 0 THEN LEFT(RD.CODART, LEN(RD.CODART) -3) ELSE RD.CODART END) AS CODARTRIGA
     , (CASE WHEN TD.ESERCIZIO < 2018 THEN ISNULL((SELECT TOP 1 Z.CODART FROM ZS_GENERAARTICOLI_POST Z WITH (NOLOCK) WHERE Z.NUOVOCODART = RD.CODART), RD.CODART)
     	ELSE
     		RD.CODART
     	END) AS CODARTRIGA
     , TD.TIPODOC
 FROM
     TESTEDOCUMENTI TD WITH (NOLOCK), RIGHEDOCUMENTI RD  WITH (NOLOCK)
     , RELAZIONICFV RCFV  WITH (NOLOCK) 

WHERE TD.PROGRESSIVO = RD.IDTESTA 
 AND TD.CODCLIFOR = RCFV.CODCLIFOR
 AND (PATINDEX(ARTICOLO + (CASE WHEN RCFV.VARIANTI <> '' AND CHARINDEX('?', RCFV.VARIANTI) > 0 THEN '#' + REPLACE(RCFV.VARIANTI, '???', '%') ELSE '' END), rd.codart) > 0 
 OR
 ARTICOLO + (CASE WHEN RCFV.VARIANTI <> '' THEN '#' + RCFV.VARIANTI ELSE '' END) = RD.CODART
  )
  AND RCFV.VARIANTI <> ''
	--AND TD.ESERCIZIO >= 2018
GO

GRANT SELECT ON dbo.VistaRelazioniCFVdaDocZSIX TO Metodo98
GO





SELECT * FROM RELAZIONiCFV 
WHERE ARTICOLO = RIFERIMENTO
AND LEFT(ARTICOLO, 1) IN ('2', '3', '4')

UPDATE RELAZIONiCFV 
SET RIFERIMENTO = RIFERIMENTO + '.'
WHERE ARTICOLO = RIFERIMENTO
AND LEFT(ARTICOLO, 1) IN ('2', '3', '4')



