ALTER TABLE ANAGRAFICAARTICOLI ALTER COLUMN DESCRIZIONE VARCHAR(500)
GO

ALTER TABLE RIGHEDOCUMENTI ALTER COLUMN DESCRIZIONEART VARCHAR(500)
GO

ALTER TABLE RIGHEORDPROD ALTER COLUMN DESCRIZIONEART VARCHAR(500)
GO

ALTER TABLE IMPEGNIORDPROD ALTER COLUMN DESCRIZIONEART VARCHAR(500)
GO

ALTER TABLE DISTINTABASE ALTER COLUMN DESCRIZIONE VARCHAR(500)
GO

ALTER TABLE RELAZIONICFV ALTER COLUMN DESCRIZIONE VARCHAR(500)
GO

-- distinta del 20021
INSERT INTO dbo.DISTINTABASE (RIFPROGRESSIVO, NRRIGA, POSIZIONE, CODARTCOMPONENTE, DESCRIZIONE, SOLOSE, UM, QTA1, OPERATORE, QTA2, CALCOLO, QTACOSTO, VERSIONECOMPONENTE, SVILUPPACOMPONENTE)
VALUES (520, 1, 1, '20021K#${1}', 'AMPHOTENSID B4/C SFUSO', '${3}=XXX', 'KG', '1', '', '', '', '1', '', '1')
GO

INSERT INTO dbo.DISTINTABASE (RIFPROGRESSIVO, NRRIGA, POSIZIONE, CODARTCOMPONENTE, DESCRIZIONE, SOLOSE, UM, QTA1, OPERATORE, QTA2, CALCOLO, QTACOSTO, VERSIONECOMPONENTE, SVILUPPACOMPONENTE)
VALUES (520, 2, 2, '${3CB}', '*** Articolo variabile ***', '', 'NR', '1', '/', '=${EP27}', '=INT(${QT}+0,99)', '', '', '')
GO

INSERT INTO dbo.DISTINTABASE (RIFPROGRESSIVO, NRRIGA, POSIZIONE, CODARTCOMPONENTE, DESCRIZIONE, SOLOSE, UM, QTA1, OPERATORE, QTA2, CALCOLO, QTACOSTO, VERSIONECOMPONENTE, SVILUPPACOMPONENTE)
VALUES (520, 3, 3, '20021#${1}${2}XXX', 'AMPHOTENSID B4/C - NON CONFEZIONATO !!', '${3}<>XXX', 'KG', '1', '', '', '', '', '', '')
GO



INSERT INTO dbo.TABIMBALLI (CODICE, DESCRIZIONE, LUNGHEZZA, LARGHEZZA, ALTEZZA, PESOIMBALLO, DESCRIZIONELINGUA1, DESCRIZIONELINGUA2, DESCRIZIONELINGUA3, DESCRIZIONELINGUA4, DESCRIZIONELINGUA5, DESCRIZIONELINGUA6, DESCRIZIONELINGUA7, DESCRIZIONELINGUA8, DESCRIZIONELINGUA9, UTENTEMODIFICA, DATAMODIFICA, CodTipologia, CODNOTE, XLS_PACKING, STAMPA_SCHEDASICUREZZA, MERCE, QTA_COLLI, LISTINO, VARIANTEIMBALLO, VARIANTEIMBALLOF)
VALUES ('XXX', '', 0, 0, 0, 0, '', '', '', '', '', '', '', '', '', 'trm1', '2017-12-07 22:12:06.77', '', 0, '', 'S', 'D', 0, 0, 'XXX', 'XXX')
GO

INSERT INTO dbo.TABTIPOLOGIE (TIPOLOGIA, DESCRIZIONE, CTRLESISTENZA, LUNGVARIANTE, UTENTEMODIFICA, DATAMODIFICA)
VALUES ('SPE', 'SPECIFICA CLIENTE', 1, 3, 'trm1', '2017-12-08 00:27:10.46')
GO

INSERT INTO dbo.TABVARIANTI (TIPOLOGIA, VARIANTE, POSIZIONE, DESCRIZIONE, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, DESCRIZIONE1, DESCRIZIONE2, DESCRIZIONE3, DESCRIZIONE4, DESCRIZIONE5, DESCRIZIONE6, DESCRIZIONE7, DESCRIZIONE8, DESCRIZIONE9, UTENTEMODIFICA, DATAMODIFICA)
VALUES ('SPE', '000', 1, 'STD', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'trm1', '2017-12-08 00:27:10.49')
GO





INSERT INTO dbo.TABVARIANTI (TIPOLOGIA, VARIANTE, POSIZIONE, DESCRIZIONE, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, DESCRIZIONE1, DESCRIZIONE2, DESCRIZIONE3, DESCRIZIONE4, DESCRIZIONE5, DESCRIZIONE6, DESCRIZIONE7, DESCRIZIONE8, DESCRIZIONE9, UTENTEMODIFICA, DATAMODIFICA)
VALUES ('62', 'A00', 79, '-- NON UTILIZZARE', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'trm1', GETDATE())
GO

INSERT INTO dbo.TABVARIANTI (TIPOLOGIA, VARIANTE, POSIZIONE, DESCRIZIONE, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, DESCRIZIONE1, DESCRIZIONE2, DESCRIZIONE3, DESCRIZIONE4, DESCRIZIONE5, DESCRIZIONE6, DESCRIZIONE7, DESCRIZIONE8, DESCRIZIONE9, UTENTEMODIFICA, DATAMODIFICA)
VALUES ('62', 'B00', 80, '-- NON UTILIZZARE', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'trm1', GETDATE())
GO

INSERT INTO dbo.TABVARIANTI (TIPOLOGIA, VARIANTE, POSIZIONE, DESCRIZIONE, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, DESCRIZIONE1, DESCRIZIONE2, DESCRIZIONE3, DESCRIZIONE4, DESCRIZIONE5, DESCRIZIONE6, DESCRIZIONE7, DESCRIZIONE8, DESCRIZIONE9, UTENTEMODIFICA, DATAMODIFICA)
VALUES ('62', 'C00', 81, '-- NON UTILIZZARE', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'trm1', GETDATE())
GO

INSERT INTO dbo.TABVARIANTI (TIPOLOGIA, VARIANTE, POSIZIONE, DESCRIZIONE, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, DESCRIZIONE1, DESCRIZIONE2, DESCRIZIONE3, DESCRIZIONE4, DESCRIZIONE5, DESCRIZIONE6, DESCRIZIONE7, DESCRIZIONE8, DESCRIZIONE9, UTENTEMODIFICA, DATAMODIFICA)
VALUES ('62', 'CR0', 82, '-- NON UTILIZZARE', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'trm1', GETDATE())
GO

INSERT INTO dbo.TABVARIANTI (TIPOLOGIA, VARIANTE, POSIZIONE, DESCRIZIONE, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, DESCRIZIONE1, DESCRIZIONE2, DESCRIZIONE3, DESCRIZIONE4, DESCRIZIONE5, DESCRIZIONE6, DESCRIZIONE7, DESCRIZIONE8, DESCRIZIONE9, UTENTEMODIFICA, DATAMODIFICA)
VALUES ('62', '900', 83, '-- NON UTILIZZARE', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'trm1', GETDATE())
GO



TRUNCATE TABLE ITA_CODICISOST
GO



INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, '__RELAZIONIARTICOLIBSC', 'CODICE', '', '2017-12-05 23:07:41.803')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, '_aaprecrmgec', 'CODICE', '', '2017-12-05 23:07:41.843')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, '_corprovvigioni', 'CODART', '', '2017-12-05 23:07:27.967')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, '_correggiprovvigioni', 'CODART', '', '2017-12-05 23:07:28.03')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, '_EXCEL_RELAZIONIARTICOLIBSC', 'CODICE', '', '2017-12-05 23:07:41.63')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, '_ITA_TAB_DEFPROV', 'MACROARTICOLO', '', '2017-12-05 23:07:57.073')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, '_RCFV_20170222', 'ARTICOLO', '', '2017-12-05 22:11:53.773')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, '_RCFV_20170222', 'ARTICOLOBSC', '', '2017-12-05 22:11:54.56')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, '_RCFV_20170222', 'RIFERIMENTO', '', '2017-12-05 23:08:05.01')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, '_XXX_', 'CODART', '', '2017-12-05 23:07:26.54')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, '_zzz_', 'CODART', '', '2017-12-05 23:07:34.423')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, '_ZZZZ', 'MACROARTICOLO', '', '2017-12-05 23:07:57.1')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'ANAGRAFICAARTICOLI', 'CODICE', '', '2017-12-05 23:07:41.597')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'ANAGRAFICAARTICOLI', 'VARESPLICITE', '', '2017-12-05 23:08:14.97')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'ANAGRAFICAARTICOLICOMM', 'BARCODE', '', '2017-12-05 23:07:20.133')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'ANAGRAFICAARTICOLICOMM', 'CODICEART', '', '2017-12-05 23:07:42.323')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'ANAGRAFICAARTICOLIPROD', 'CODICEART', '', '2017-12-05 23:07:42.393')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'AnagraficaCespiti', 'Ubicazione', '', '2017-12-05 23:08:14.53')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'ANAGRAFICALOTTI', 'CODARTICOLO', '', '2017-12-05 23:07:41.06')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'ARTICOLIFATTORICONVERSIONE', 'CODART', '', '2017-12-05 23:07:22.153')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'ARTICOLIUMPREFERITE', 'CODART', '', '2017-12-05 23:07:22.09')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'ARTICOLIUNITAMISURA', 'CODART', '', '2017-12-05 23:07:28.19')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'BRIO_PREZZIARTICOLIMP', 'CODART', '', '2017-12-05 23:07:21.753')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'CONSEGNEAGENTE', 'CODART', '', '2017-12-05 23:07:28.007')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'CONSEGNEGIAC', 'CODART', '', '2017-12-05 23:07:22.213')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'CONTROPARTARTICOLI', 'CODART', '', '2017-12-05 23:07:28.103')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'DESCRARTICOLI', 'CODICEART', '', '2017-12-05 23:07:42.493')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'DISTINTAARTCOMPOSTI', 'ARTCOMPOSTO', '', '2017-12-05 22:11:53.523')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'DISTINTAARTCOMPOSTI', 'RIFARTICOLO', '', '2017-12-05 23:08:03.347')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'DISTINTABASE', 'CODARTCOMPONENTE', '', '2017-12-05 23:07:40.29')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'ECCEZIONIPROGPROD', 'CODART', '', '2017-12-05 23:07:27.48')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'EXCEL_RELAZIONIARTICOLIBSC', 'CODICE', '', '2017-12-05 23:07:41.753')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'EXTRAMAG', 'CODART', '', '2017-12-05 23:07:28.313')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'EXTRAMAG', 'MACRO_ART', '', '2017-12-05 23:07:57.003')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'EXTRAMAGCRM', 'CODART', '', '2017-12-05 23:07:27.403')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'EXTRAMAGCRM', 'FAMIGLIA', '', '2017-12-05 23:07:48.147')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'EXTRARIGHEDOC', 'NRLOTTO', '', '2017-12-05 23:07:59.68')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'GESTIONEPREZZI', 'CODART', '', '2017-12-05 23:07:23.877')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'GESTIONEPREZZI', 'CODARTRIC', '', '2017-12-05 23:07:41.323')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'IMPEGNIORDPROD', 'CODART', '', '2017-12-05 23:07:23.75')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'IMPOSTAZIONISTAMPA', 'AVALORE', '', '2017-12-05 23:07:19.857')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'IMPOSTAZIONISTAMPA', 'DAVALORE', '', '2017-12-05 23:07:44.18')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'ITA_ARCHIVIO_ARTICOLI', 'CODICE', '', '2017-12-05 23:07:41.923')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'ITA_TAB_DEFPROV', 'MACROARTICOLO', '', '2017-12-05 23:07:57.047')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'ITA_TAB_DEFPROV_LOG', 'MACROARTICOLO', '', '2017-12-05 23:07:57.12')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'ITA_TAB_REPORT_XLS_MARKETING', 'CODART', '', '2017-12-05 23:07:33.22')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'ITA_TAB_REPORT_XLS_MARKETING', 'RIFERIMENTO', '', '2017-12-05 23:08:06.703')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'ITA_TAB_REPORT_XLS_PRODUCTION', 'CODART', '', '2017-12-05 23:07:22.553')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'ITA_TAB_REPORT_XLS_PURCHASE', 'CODART', '', '2017-12-05 23:07:25.31')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'ITA_TABREGISTRONOTIFICHEBSC', 'ARTICOLOBSC', '', '2017-12-05 22:11:54.577')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'ITA_TABREGISTRONOTIFICHEBSC', 'CODART', '', '2017-12-05 23:07:25.4')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'ITA_WPUBBLICA_ARTICOLI', 'Codice', '', '2017-12-05 23:07:42.083')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'LIFOARTICOLI', 'CODICEART', '', '2017-12-05 23:07:42.763')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'LISTAARTICOLICTRLINV', 'ARTICOLO', '', '2017-12-05 22:11:53.577')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'LISTAMOVIMENTICTRLINV', 'ARTICOLO', '', '2017-12-05 22:11:53.607')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'LISTINIARTICOLI', 'CODART', '', '2017-12-05 23:07:27.333')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'PROGPRODUZIONE', 'CODART', '', '2017-12-05 23:07:28.127')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'PROGPRODUZIONE', 'RAGGRUPPA', '', '2017-12-05 23:08:02.907')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'PROGPRODUZIONE', 'RIFERIMENTI', '', '2017-12-05 23:08:04.883')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'RELAZIONICFV', 'ARTICOLO', '', '2017-12-05 22:11:53.987')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'RELAZIONICFV', 'ARTICOLOBSC', '', '2017-12-05 22:11:54.78')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'RELAZIONICFV', 'RIFERIMENTO', '', '2017-12-05 23:08:04.95')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'RELAZIONICFV', 'VARIANTI', '', '2017-12-05 23:08:16.023')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'RIGHEDOCUMENTI', 'CODART', '', '2017-12-05 23:07:30.057')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'RIGHEDOCUMENTI', 'RifRelazioneCF', '', '2017-12-05 23:08:11.773')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'RIGHEORDPROD', 'CODART', '', '2017-12-05 23:07:27.933')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'STAMPALISTINIPARTICOLARI', 'CODART', '', '2017-12-05 23:07:24.03')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'STORICOCONSEGNE', 'CODARTICOLO', '', '2017-12-05 23:07:40.357')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'STORICOMAG', 'CODART', '', '2017-12-05 23:07:34.31')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'STORICOMOVIMPPROD', 'CODART', '', '2017-12-05 23:07:26.41')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'STORICOMOVORDPROD', 'CODART', '', '2017-12-05 23:07:27.15')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'STORICOPREZZIARTICOLO', 'CODARTICOLO', '', '2017-12-05 23:07:40.98')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'TAB_ARTICOLIADR', 'CODART', '', '2017-12-05 23:07:23.97')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'TABLOTTIRIORDINO', 'CODART', '', '2017-12-05 23:07:21.96')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'TABPROVVIGIONI', 'CODARTICOLO', '', '2017-12-05 23:07:40.43')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'TABPROVVIGIONI', 'CODARTRIC', '', '2017-12-05 23:07:41.253')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'TIPOLOGIEARTICOLI', 'CODICEART', '', '2017-12-05 23:07:42.527')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'TP_ExtraMag', 'CodArt', '', '2017-12-05 23:07:34.497')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'TP_GOI', 'CodArt', '', '2017-12-05 23:07:27.29')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'TP_PREZZIVENDITA', 'CodArticolo', '', '2017-12-05 23:07:40.543')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'TP_SINONIMI', 'Cod_Sino', '', '2017-12-05 23:07:21.19')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'TP_SINONIMI', 'Codice', '', '2017-12-05 23:07:42.15')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'TP_SINONIMI', 'Desc_Sino', '', '2017-12-05 23:07:44.31')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'VARIANTIARTICOLI', 'CODICEART', '', '2017-12-05 23:07:42.433')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'ZS_GENERAARTICOLI', 'ARTTIPOLOGIA', '', '2017-12-05 22:11:54.807')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'ZS_GENERAARTICOLI_POST', 'CODART', '', '2017-12-05 23:07:21.993')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (0, 'ZS_GENERAARTICOLI_POST', 'NUOVOCODART', '', '2017-12-05 23:07:59.82')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'ZSI_CONFEZIONAMENTO', 'CODART', '', '2017-12-05 23:07:30.153')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'ZSI_DISPONIBILITAM05', 'CODART', '', '2017-12-05 23:07:27.217')
GO

INSERT INTO dbo.ITA_CODICISOST (SEL, TABELLA, CAMPO, UtenteModifica, DataModifica)
VALUES (1, 'ZSI_NOTEART', 'CODART', '', '2017-12-05 23:07:21.83')
GO





IF OBJECT_ID ('dbo.ZS_GENERAARTICOLI') IS NOT NULL
	DROP TABLE dbo.ZS_GENERAARTICOLI
GO

CREATE TABLE dbo.ZS_GENERAARTICOLI
	(
	ARTTIPOLOGIA    VARCHAR (50),
	CODART          VARCHAR (50),
	CODICE          VARCHAR (10) NOT NULL,
	DESCRIZIONE     VARCHAR (500),
	VARIANTEIMBALLO VARCHAR (25),
	NUOVOCODART     VARCHAR (50) NOT NULL,
	UtenteModifica  VARCHAR (25) NOT NULL,
	DataModifica    DATETIME NOT NULL,
	ORDINAMENTO INT
	CONSTRAINT PK__ZS_GENER__74CEDBB85D859AAB PRIMARY KEY (NUOVOCODART, CODICE)
	)
GO

GRANT DELETE ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO
GRANT INSERT ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO
GRANT REFERENCES ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO
GRANT SELECT ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO
GRANT UPDATE ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO




IF OBJECT_ID ('dbo.ITA_FILLCODICISOST') IS NOT NULL
	DROP PROCEDURE dbo.ITA_FILLCODICISOST
GO

CREATE  PROCEDURE ITA_FILLCODICISOST AS
	DECLARE @CSQL AS VARCHAR(5000)
	DECLARE @N AS SMALLINT
	DECLARE @NOMECAMPO AS VARCHAR(80)
	DECLARE @NOMETABELLA AS VARCHAR(80)

	DELETE FROM ITA_CODICISOST

	DECLARE rSqlA CURSOR LOCAL KEYSET FOR 
	SELECT C.COLUMN_NAME, C.TABLE_NAME
	FROM INFORMATION_SCHEMA.COLUMNS C JOIN INFORMATION_SCHEMA.TABLES T ON T.TABLE_NAME = C.TABLE_NAME
	WHERE TABLE_TYPE <> 'VIEW' AND DATA_TYPE LIKE '%CHAR%' AND CHARACTER_MAXIMUM_LENGTH >= 50 AND 
	LEFT(C.TABLE_NAME,1) <> 'W' AND  LEFT(C.TABLE_NAME,3) <> 'TMP' AND LEFT(C.TABLE_NAME,4) <> 'TEMP' AND
	C.COLUMN_NAME NOT LIKE '%DESCR%' AND C.COLUMN_NAME NOT LIKE '%NOT%' AND C.COLUMN_NAME NOT LIKE '%DSC%' AND
	C.COLUMN_NAME NOT LIKE '%INDIR%' AND C.COLUMN_NAME NOT LIKE '%LOCAL%' AND C.COLUMN_NAME NOT LIKE '%FORMULA%' AND
	C.COLUMN_NAME NOT LIKE '%RAGS%' AND C.COLUMN_NAME NOT LIKE '%CALCOLO%' AND C.COLUMN_NAME <> 'CODICEPRIMARIO' AND
	C.COLUMN_NAME NOT LIKE '%AGE%' AND C.COLUMN_NAME NOT LIKE '%ATT%' AND C.COLUMN_NAME NOT LIKE '%CAMPO%' AND
	C.COLUMN_NAME NOT LIKE '%CAUS%' AND C.COLUMN_NAME NOT LIKE '%DESP%' AND C.COLUMN_NAME NOT LIKE '%DESUM%' AND
	C.COLUMN_NAME NOT LIKE '%NOME%' AND C.COLUMN_NAME NOT LIKE '%TIPI%' AND C.COLUMN_NAME NOT LIKE '%INTESTA%' 
	ORDER BY C.COLUMN_NAME
	OPEN rSqlA

	FETCH NEXT from rSqlA INTO @NOMECAMPO, @NOMETABELLA
	WHILE (@@FETCH_STATUS <> -1)
		BEGIN
			PRINT @NOMETABELLA + ' ' + @NOMECAMPO	
			
			SELECT @N = COUNT(*) FROM ITA_CODICISOST WHERE TABELLA = @NOMETABELLA AND CAMPO = @NOMECAMPO
			
			IF @N = 0
			BEGIN

				IF @NOMETABELLA = 'RELAZIONICFV' AND ( @NOMECAMPO = 'ARTICOLO' OR @NOMECAMPO = 'VARIANTI' )

					BEGIN
				
						INSERT INTO ITA_CODICISOST VALUES (1, @NOMETABELLA, @NOMECAMPO, '', getdate() )

					END
				
				ELSE

					BEGIN
					

						SET @CSQL = 'SELECT TOP 1 [' + @NOMECAMPO + '] FROM ' + @NOMETABELLA + ' WHERE ISNULL([' + @NOMECAMPO + '],'''') <> '''' '
						--PRINT @CSQL
						EXEC (@CSQL)
						IF @@ROWCOUNT > 0
						BEGIN


							SET @CSQL = 'SELECT TOP 1 ''A'' FROM ' + @NOMETABELLA + ' WHERE [' + @NOMECAMPO + '] IN (SELECT CODICE FROM ANAGRAFICAARTICOLI) AND ISNULL([' + @NOMECAMPO + '],'''') <> '''' ' 
							PRINT @CSQL
							EXEC (@CSQL)

							IF @@ROWCOUNT <> 0
							BEGIN

								INSERT INTO ITA_CODICISOST VALUES (1, @NOMETABELLA, @NOMECAMPO, '', getdate() )

								PRINT @NOMETABELLA + ' ' + @NOMECAMPO				

							END
							

						END
					END				
			
			END
	
			FETCH NEXT from rSqlA INTO @NOMECAMPO, @NOMETABELLA
		END

	CLOSE rSqlA
	DEALLOCATE rSqlA
GO

GRANT EXECUTE ON dbo.ITA_FILLCODICISOST TO Metodo98
GO





IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI_MOV') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI_MOV
GO

CREATE VIEW ZS_VISTA_GENERAARTICOLI_MOV
AS

SELECT * FROM (
	SELECT DISTINCT 
	(CASE WHEN charindex('#', R.CODART) > 1 THEN LEFT(R.CODART, charindex('#', R.CODART) - 1) ELSE R.CODART END) AS ARTTIPOLOGIA
	, R.CODART, R.CODIMBALLO AS CODICE, I.DESCRIZIONE AS DESCRIMBALLO, I.VARIANTEIMBALLO, V.DESCRIZIONE AS DESCRVARIANTE
	, (CASE WHEN LEFT(R.CODART, 1) IN ('3', '4') THEN
		 (CASE 
		WHEN RIGHT(R.CODART, 3) = 'XXX' THEN REPLACE(R.CODART, 'XXX',  '000' + I.VARIANTEIMBALLO)
		--WHEN RIGHT(R.CODART, 3) <> 'XXX' AND I.VARIANTEIMBALLO = 'XXX' THEN REPLACE(R.CODART, RIGHT(R.CODART, 3),  '000' + RIGHT(R.CODART, 3))
		ELSE R.CODART + '#000' + '000' + I.VARIANTEIMBALLO
		END) 
	ELSE	
	 (CASE WHEN RIGHT(R.CODART, 3) = 'XXX' THEN LEFT(R.CODART, LEN(R.CODART) - 3) +  '000' + RIGHT(R.CODART, 3)
		ELSE LEFT(R.CODART, LEN(R.CODART) - 3) +  '000' + I.VARIANTEIMBALLO
		END) 
	END) AS NUOVOCODART
	
FROM RIGHEDOCUMENTI R WITH (NOLOCK) 
JOIN TABIMBALLI I WITH (NOLOCK) ON I.CODICE = R.CODIMBALLO
JOIN TABVARIANTI v WITH (NOLOCK) ON v.VARIANTE = I.varianteimballo
WHERE R.CODART <> ''  AND r.TIPODOC IN ('oce', 'occ', 'ocg') AND V.TIPOLOGIA = '62' --AND r.RIGACHIUSA = 0 AND r.QTAGESTRES > 0
AND I.VARIANTEIMBALLO <> ''
AND len(r.CODART) <= 12
	) CTE
WHERE LEN(ARTTIPOLOGIA) = 5
	AND ARTTIPOLOGIA BETWEEN '20000' AND '49999' 
	
	AND charindex('#', substring(nuovocodart, charindex('#', nuovocodart) + 1, 10) ) = 0
	--AND NUOVOCODART NOT IN (SELECT CODICE FROM ANAGRAFICAARTICOLI)
	
	
UNION
	
SELECT 
	LEFT(A.CODICE, 5) AS ARTTIPOLOGIA
	, a.CODICE AS CODART
	, 'XXX' AS CODICE
	, '' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO
	, '' AS DESCRVARIANTE
	, (CASE WHEN RIGHT(A.CODICE, 3) <> 'XXX' THEN LEFT(A.CODICE, LEN(A.CODICE) - 3) +  '000' + RIGHT(A.CODICE, 3)
	ELSE 	REPLACE(A.CODICE, 'XXX',  '000XXX')
	END) AS NUOVOCODART 
FROM 
	ANAGRAFICAARTICOLI a 
WHERE 
	a.CODICEPRIMARIO in
	(SELECT CODICE FROM ANAGRAFICAARTICOLI 
	WHERE ARTTIPOLOGIA = 1
	AND isnumeric(codice) = 1
	AND CODICE BETWEEN '20000' AND '49999')
	AND len(A.CODICE) <= 12
	AND patindex('%#k%', CODICE) = 0
GO

GRANT DELETE ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO
GRANT INSERT ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO
GRANT REFERENCES ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO
GRANT SELECT ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO
GRANT UPDATE ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO



IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI_MODELLI') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI_MODELLI
GO

CREATE view ZS_VISTA_GENERAARTICOLI_MODELLI as 


SELECT R.CODART AS ARTTIPOLOGIA
	, R.CODART, '' AS CODICE
	, 'XXX' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO, 'XXX' AS DESCRVARIANTE
	, (R.CODART + '#000000XXX') AS NUOVOCODART 
	, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WITH (NOLOCK) WHERE A.CODICE = R.CODART) AS DESCRIZIONE
	, 'A' AS TIPO
	FROM (
SELECT X.CODART FROM ZS_VISTA_GENERAARTICOLI_MOV X 
WHERE charindex('#', X.CODART) = 0
GROUP BY X.CODART
HAVING count(*) > 1) R
GO

GRANT SELECT ON dbo.ZS_VISTA_GENERAARTICOLI_MODELLI TO Metodo98
GO





IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI
GO

CREATE VIEW ZS_VISTA_GENERAARTICOLI
AS
/*
SELECT *, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WHERE A.CODICE = CTE.CODART OR A.CODICE = CTE.ARTTIPOLOGIA) AS DESCRIZIONE FROM (
	SELECT distinct
	(CASE WHEN charindex('#', g.CODART) > 1 THEN LEFT(g.CODART, charindex('#', g.CODART) - 1) ELSE g.CODART END) AS ARTTIPOLOGIA
	, g.CODART
	, t.CODICE
	, t.varianteimballo
	, (CASE 
		WHEN charindex('#', g.CODART) > 0 AND charindex('?', g.codart) = 0 THEN LEFT(g.CODART, charindex('#', g.CODART) + 3) + T.VARIANTEIMBALLO 
		WHEN charindex('#', g.CODART) > 0 AND charindex('?', g.codart) > 0 THEN LEFT(g.CODART, charindex('#', g.CODART)) + '000' + T.VARIANTEIMBALLO 
		ELSE
			g.CODART + '#000' + T.VARIANTEIMBALLO 
		END) AS NUOVOCODART
		--, g.*
	FROM GESTIONEPREZZI g JOIN GESTIONEPREZZIRIGHE r ON g.PROGRESSIVO = r.RIFPROGRESSIVO
	JOIN tabimballi t ON t.CODICE = r.cod_imballo 
	JOIN TABVARIANTI v ON v.VARIANTE = t.varianteimballo
	WHERE g.INIZIOVALIDITA = g.FINEVALIDITA and t.varianteimballo  <> '' --AND charindex('?', g.codart) = 0
	--AND t.codice NOT IN (100, 101)
	) CTE
WHERE 
	NUOVOCODART NOT IN (SELECT CODICE FROM ANAGRAFICAARTICOLI)
	AND ARTTIPOLOGIA BETWEEN '20000' AND '49999'
	*/


SELECT X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART
	, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WITH (NOLOCK) WHERE A.CODICE = X.CODART OR A.CODICE = X.ARTTIPOLOGIA) AS DESCRIZIONE --, '' AS TIPO
	, (SELECT 'B' FROM ZS_VISTA_GENERAARTICOLI_MOV Z WHERE Z.CODART = X.CODART AND LEFT(Z.CODART, 1) <> '2' GROUP BY Z.CODART HAVING COUNT(Z.CODART) = 1 ) AS TIPO
	, (CASE WHEN X.CODICE <> 'XXX' THEN 0 ELSE 9999 END) AS ORDINAMENTO

FROM 
	 ZS_VISTA_GENERAARTICOLI_MOV x -- ON  x.ARTTIPOLOGIA = cte.arttipologia AND x.CODIMBALLO = cte.cod_imballo
UNION
SELECT 
	X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART, X.DESCRIZIONE, X.TIPO 
	, (CASE WHEN X.CODICE <> 'XXX' THEN 0 ELSE 9999 END) AS ORDINAMENTO
FROM 
	ZS_VISTA_GENERAARTICOLI_MODELLI X
GO

GRANT DELETE ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT INSERT ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT REFERENCES ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT SELECT ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT UPDATE ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO




IF OBJECT_ID ('dbo.ZS_GENERAARTICOLO_PRE') IS NOT NULL
	DROP PROCEDURE dbo.ZS_GENERAARTICOLO_PRE
GO

CREATE PROCEDURE ZS_GENERAARTICOLO_PRE(@CODART VARCHAR(50)) AS
BEGIN
 
	DECLARE @ARTPADRE VARCHAR(50)
	
	SET @ARTPADRE = LEFT(@CODART, CHARINDEX('#' , @CODART) -1)
	
	-- TRASFORMO PUNTUALE IN TIPOLOGIE A VARIANTI
	UPDATE ANAGRAFICAARTICOLI SET ARTTIPOLOGIA = 1 WHERE CODICE = @ARTPADRE AND ARTTIPOLOGIA = 0
	
	INSERT INTO dbo.TIPOLOGIEARTICOLI (CODICEART, NUMEROTIP, CODTIPOLOGIA, SELVARIANTI, AGGIUNGIDES, UTENTEMODIFICA, DATAMODIFICA)
	SELECT @ARTPADRE, 1, 'PE', 1, 0, 'trm1', getdate() FROM TABDITTE WHERE NOT EXISTS(SELECT 1 FROM TIPOLOGIEARTICOLI x WHERE x.CODICEART = @ARTPADRE AND x.CODTIPOLOGIA = 'PE')

	INSERT INTO dbo.TIPOLOGIEARTICOLI (CODICEART, NUMEROTIP, CODTIPOLOGIA, SELVARIANTI, AGGIUNGIDES, UTENTEMODIFICA, DATAMODIFICA)
	SELECT @ARTPADRE, 2, '62', 1, 0, 'trm1', getdate() FROM TABDITTE WHERE NOT EXISTS(SELECT 1 FROM TIPOLOGIEARTICOLI x WHERE x.CODICEART = @ARTPADRE AND x.CODTIPOLOGIA = '62')


	
	INSERT INTO dbo.VARIANTIARTICOLI (CODICEART, NUMEROTIP, VARIANTE, TIPOLOGIA, SOLOSE, UTENTEMODIFICA, DATAMODIFICA)
	SELECT @ARTPADRE, 1, '000', 'PE', '', 'trm1', GETDATE() FROM TABDITTE
	WHERE NOT EXISTS(SELECT 1 FROM VARIANTIARTICOLI x WHERE x.CODICEART = @ARTPADRE AND VARIANTE = '000' AND tipologia = 'PE')

	
	INSERT INTO dbo.VARIANTIARTICOLI (CODICEART, NUMEROTIP, VARIANTE, TIPOLOGIA, SOLOSE, UTENTEMODIFICA, DATAMODIFICA)
	SELECT DISTINCT  ARTTIPOLOGIA, 2, varianteimballo, '62', '', 'trm', getdate() FROM ZS_VISTA_GENERAARTICOLI
	WHERE ARTTIPOLOGIA = @ARTPADRE AND NOT EXISTS(SELECT 1 FROM VARIANTIARTICOLI x WHERE x.CODICEART = ARTTIPOLOGIA AND VARIANTE = varianteimballo AND tipologia = '62')
	

	--- gestione tipologia SPECIFICA CLIENTE
	UPDATE TIPOLOGIEARTICOLI SET NUMEROTIP = 3 WHERE CODICEART = @ARTPADRE AND NUMEROTIP = 2
	AND NOT EXISTS(SELECT 1 FROM TIPOLOGIEARTICOLI X WHERE X.CODICEART = @ARTPADRE AND X.NUMEROTIP = 3 AND X.CODTIPOLOGIA <> 'SPE')
	
	INSERT INTO dbo.TIPOLOGIEARTICOLI (CODICEART, NUMEROTIP, CODTIPOLOGIA, SELVARIANTI, AGGIUNGIDES, UTENTEMODIFICA, DATAMODIFICA)
	SELECT @ARTPADRE,  2, 'SPE', 1, 1, 'NC', GETDATE() FROM TABDITTE 
	WHERE NOT EXISTS(SELECT 1 FROM TIPOLOGIEARTICOLI X WHERE X.CODICEART = @ARTPADRE AND X.CODTIPOLOGIA = 'SPE' AND X.NUMEROTIP = 2)

	UPDATE VARIANTIARTICOLI SET NUMEROTIP = 3 WHERE CODICEART = @ARTPADRE AND NUMEROTIP = 2 AND TIPOLOGIA <> 'SPE'
	AND NOT EXISTS(SELECT 1 FROM VARIANTIARTICOLI X 
	WHERE X.CODICEART = @ARTPADRE AND X.NUMEROTIP = 3 AND X.tipologia = VARIANTIARTICOLI.TIPOLOGIA AND variantiarticoli.VARIANTE = x.VARIANTE)
	
	INSERT INTO dbo.VARIANTIARTICOLI (CODICEART, NUMEROTIP, VARIANTE, TIPOLOGIA, SOLOSE, UTENTEMODIFICA, DATAMODIFICA)
	SELECT @ARTPADRE,  2, '000', 'SPE', '', 'NC', GETDATE() 
	WHERE NOT EXISTS(SELECT 1 FROM VARIANTIARTICOLI X WHERE X.CODICEART = @ARTPADRE AND X.TIPOLOGIA = 'SPE'  AND X.NUMEROTIP = 2 AND X.VARIANTE = '000')
	

	
	UPDATE TIPOLOGIEARTICOLI SET AGGIUNGIDES = 1, SELVARIANTI = 1 WHERE CODTIPOLOGIA = '62' AND CODICEART = @ARTPADRE

END
GO

GRANT EXECUTE ON dbo.ZS_GENERAARTICOLO_PRE TO Metodo98
GO






IF OBJECT_ID ('dbo.ZS_GENERAARTICOLO_POST') IS NOT NULL
	DROP PROCEDURE dbo.ZS_GENERAARTICOLO_POST
GO

create PROCEDURE ZS_GENERAARTICOLO_POST(@CODART VARCHAR(50), @OLDCODART VARCHAR(50), @CODIMBALLO VARCHAR(50), @REDO SMALLINT = 0) AS
BEGIN
 
	DECLARE @ARTPADRE VARCHAR(50)
	DECLARE @ARTMODELLO VARCHAR(50)
	
	SET @ARTPADRE = LEFT(@CODART, CHARINDEX('#' , @CODART) -1)
	SET @ARTMODELLO = LEFT(@CODART, LEN(@CODART) -3) + 'XXX'
	

	

	
	IF (NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST WHERE CODART = @OLDCODART AND NUOVOCODART = @CODART AND CODICE = @CODIMBALLO ) OR @REDO = 1)
	BEGIN
	
		--PRINT @ARTPADRE
		--PRINT @ARTMODELLO
		--PRINT @CODIMBALLO
		
		INSERT INTO dbo.ZS_GENERAARTICOLI_POST (CODART, NUOVOCODART, UtenteModifica, DataModifica, CODICE)
		SELECT @OLDCODART, @CODART, 'TRM', GETDATE(), @CODIMBALLO
		FROM TABDITTE
		WHERE NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST X WHERE X.CODART = @OLDCODART AND X.NUOVOCODART = @CODART AND X.CODICE = @CODIMBALLO)
		
		--EXEC ZS_GENERAARTICOLI_GESTIONEPREZZI @CODART, @OLDCODART
		
		
		
		DECLARE @NRPEZZIIMBALLO INT
		

		SELECT @NRPEZZIIMBALLO = G1.QTA_COLLI 
		FROM ITA_VIS_PRZPART_IMBLIST  G1
		WHERE G1.PRIORITA > 1 AND
			(G1.CODART = @CODART OR
			G1.CODART = LEFT(@CODART, LEN(@CODART) -3) + '???' OR
			G1.CODART LIKE @ARTPADRE + '%') --'#??????')
		AND G1.COD_IMBALLO = @CODIMBALLO

		-- DATI ANAGRAFICASTANDARD
 		UPDATE a1
		SET 
			a1.DESCRIZIONE = RTRIM(LEFT(a2.descrizione + ' ' + (SELECT TOP 1 TABVARIANTI.DESCRIZIONE FROM TABVARIANTI WHERE TABVARIANTI.VARIANTE = RIGHT(a1.CODICE, 3) AND TIPOLOGIA = '62'), 80))
			, a1.GRUPPO = a2.GRUPPO
			, a1.CATEGORIA = a2.CATEGORIA
			, a1.CODCATEGORIASTAT = a2.CODCATEGORIASTAT
			, a1.PESONETTO = a2.PESONETTO
			, a1.SUPERFICIE = a2.SUPERFICIE
			, a1.CUBATURA = a2.CUBATURA
			, a1.NOMENCLCOMBINATA1 = a2.NOMENCLCOMBINATA1
			, a1.NOMENCLCOMBINATA2 = a2.NOMENCLCOMBINATA2
			, a1.ORIGINEINTRA = a2.ORIGINEINTRA 
			, a1.CODICEARTIMBALLO = a1.CODICEARTIMBALLO
			, a1.NRPEZZIIMBALLO = @NRPEZZIIMBALLO --a2.NRPEZZIIMBALLO
			, a1.RIFERIMIMBALLO = @CODIMBALLO --(SELECT TOP 1 tabimballi.CODICE FROM TABIMBALLI WHERE tabimballi.VARIANTEIMBALLO = RIGHT(a1.CODICE, 3))
			, a1.AGGIORNAMAG = a2.AGGIORNAMAG
			, a1.MOVIMENTAPARTITE = a2.MOVIMENTAPARTITE
			, a1.MOVIMENTAMATRICOLE = a2.MOVIMENTAMATRICOLE
			, a1.CODDEPOSITO = a2.CODDEPOSITO
			, a1.NRTIPRAGGRUPPATE = a2.NRTIPRAGGRUPPATE
			, a1.ARTCONFIGURATO = a2.ARTCONFIGURATO
		--SELECT rtrim(a2.descrizione + substring(a1.descrizione, (SELECT len(a3.DESCRIZIONE) FROM ANAGRAFICAARTICOLI a3 WHERE ARTTIPOLOGIA = 1 AND CODICE = a1.CODICEPRIMARIO)+1, 80)), *
		FROM ANAGRAFICAARTICOLI a1, ANAGRAFICAARTICOLI a2
		WHERE 
			a1.CODICE = @CODART
			AND a2.CODICE = @ARTMODELLO
			AND LEFT(a1.CODICE , 1) = '2'
			
			
		
				
		UPDATE a1
		SET 
			a1.CODIVA = a2.CODIVA
			, SCONTO1 = a2.SCONTO1
			, a1.SCONTO2 = a2.SCONTO2
			, a1.SCONTO3 = a2.SCONTO3
			, a1.GRUPPOPRZPART = a2.GRUPPOPRZPART
			, a1.GRUPPOPRVPART = a2.GRUPPOPRVPART
			, a1.PROVV = a2.PROVV
			, a1.CODICEALT1 = a2.CODICEALT1
			, a1.CODICEALT2 = a2.CODICEALT2
			, a1.SCGENVENDITEITA = a2.SCGENVENDITEITA
			, a1.SCGENVENDITEEST = a2.SCGENVENDITEEST
			, a1.SCGENACQUISTIITA = a2.SCGENACQUISTIITA
			, a1.SCGENACQUISTIEST = a2.SCGENACQUISTIEST
			, a1.INESAURIMENTO = a2.INESAURIMENTO
			, a1.ESAURITO = a2.ESAURITO
			, a1.QTAMINCONS = a2.QTAMINCONS
			, a1.USAPREZZIPART = a2.USAPREZZIPART
			, a1.FlagCauzioni = a2.FlagCauzioni
			, a1.FLGBARCODEGENDAPROCAUTOMSTD = a2.FLGBARCODEGENDAPROCAUTOMSTD
			, a1.EXPORTECOMMERCE = a2.EXPORTECOMMERCE
			, a1.CODIVAINTRA = a2.CODIVAINTRA
		--SELECT *
		FROM ANAGRAFICAARTICOLIcomm a1, ANAGRAFICAARTICOLIcomm a2
		WHERE 
			a1.CODICEART = @CODART
			AND a2.CODICEART = @ARTMODELLO
			AND LEFT(a1.CODICEART , 1) = '2'
			AND a1.ESERCIZIO = a2.esercizio
			AND LEFT(a1.CODICEART , 1) = '2'
		
		
		UPDATE a1
		SET a1.SCORTAMIN = a2.scortamin
			, a1.SCORTAMAX = a2.SCORTAMAX
			, a1.LIVPRODUZIONE = a2.LIVPRODUZIONE
			, a1.RAGGRPRODUZIONE =  a1.RAGGRPRODUZIONE
			, a1.LIVPRODPREC = a2.LIVPRODPREC
			, a1.TIPOGESTIONE = a2.TIPOGESTIONE
			, a1.LIVRIORDINO = a2.LIVRIORDINO
			, a1.PROVENIENZA = A2.PROVENIENZA
			, a1.ARTALTERNATIVO =a1.ARTALTERNATIVO
			, a1.QMINRIORDACQ = a2.QMINRIORDACQ
			, a1.QMAXRIORDACQ = a2.QMAXRIORDACQ
			, a1.QDELTARIORDACQ = a2.QDELTARIORDACQ
			, a1.TAPPRONTACQ = a2.TAPPRONTACQ
			, a1.TAPPROVVACQ = a2.TAPPROVVACQ
			, a1.LOTTORIFACQ = a2.LOTTORIFACQ
			, a1.ARROTLOTTOACQ = a2.ARROTLOTTOACQ
			, a1.FORNPREFACQ = a2.FORNPREFACQ
			, a1.QMINRIORDPROD = a2.QMINRIORDPROD
			, a1.QMAXRIORDPROD = a2.QMAXRIORDPROD
			, a1.QDELTARIORDPROD = a2.QDELTARIORDPROD
			, a1.TAPPRONTPROD = a2.TAPPRONTPROD 
			, a1.TAPPROVVPROD = a2.TAPPROVVPROD
			, a1.LOTTORIFPROD = a2.LOTTORIFPROD
			, a1.ARROTLOTTOPROD = a2.ARROTLOTTOPROD
			, a1.QMINRIORDLAV = a2.QMINRIORDLAV
			, a1.QMAXRIORDLAV = a2.QMAXRIORDLAV
			, a1.QDELTARIORDLAV = a2.QDELTARIORDLAV
			, a1.TAPPRONTLAV = a2.TAPPRONTLAV
			, a1.TAPPROVVLAV = a2.TAPPROVVLAV
			, a1.LOTTORIFLAV = a2.LOTTORIFLAV
			, a1.ARROTLOTTOLAV = a2.ARROTLOTTOLAV 
			, a1.FORNPREFLAV = a2.FORNPREFLAV
			, a1.LOTTORIORDINO = a2.LOTTORIORDINO
			, a1.TIPOPRODUZIONE = a2.TIPOPRODUZIONE
			, a1.FLOORSTOCK = a2.FLOORSTOCK
			, a1.GRUPPOAPPROV = a2.GRUPPOAPPROV
			, a1.COSTOORDINEACQ = a2.COSTOORDINEACQ
			, a1.COSTOORDINELAV = a2.COSTOORDINELAV
			, a1.COSTOORDINEPROD = a2.COSTOORDINEPROD
			, a1.FATTORESCOSTAMENTO = a2.FATTORESCOSTAMENTO
			, a1.TEMPOCOPERTURA = a2.TEMPOCOPERTURA
			, a1.CONSUMOPREVISTO = a2.CONSUMOPREVISTO
			, a1.MADPREVISTO = a2.MADPREVISTO
			, a1.FATTORESICUREZZA = a2.TIPOPRODOTTO
			, a1.TIPOPRODOTTO = a2.TIPOPRODOTTO
			, a1.GESTIONEMATERIALI = a2.GESTIONEMATERIALI
			, a1.FATTORECOMPRESSIONE = a2.FATTORECOMPRESSIONE
			, a1.GRUPPOPREVISIONE = a2.GRUPPOPREVISIONE
			, a1.FORMULAFRONTIERA = a2.FORMULAFRONTIERA
			, a1.LIVELLOSERVIZIO = a2.LIVELLOSERVIZIO
			, a1.FLAGMPS = a2.FLAGMPS
			, a1.FLAGNETTIFICAMPS = a2.FLAGNETTIFICAMPS
			, a1.CODICEMPS = a2.CODICEMPS
			, a1.LOTTOFABBRICAZIONE = a2.LOTTOFABBRICAZIONE
			, a1.UMLOTTOFABBRICAZIONE = a2.UMLOTTOFABBRICAZIONE
			, a1.KS_GGScadenza = a2.KS_GGScadenza
			, a1.INTERVALLOPIANIF = a2.INTERVALLOPIANIF
			, a1.DATAULTANALISI = a2.DATAULTANALISI
			, a1.GGORIZZONTEDISP = a2.GGORIZZONTEDISP
		--SELECT *
		FROM ANAGRAFICAARTICOLIPROD a1, ANAGRAFICAARTICOLIPROD a2
		WHERE 
			a1.CODICEART = @CODART
			AND a2.CODICEART = @ARTMODELLO
			AND LEFT(a1.CODICEART , 1) = '2'
			AND a1.ESERCIZIO = a2.esercizio
			AND LEFT(a1.CODICEART , 1) = '2'

		
		
		
		UPDATE a1
		SET A1.ScontiPremi = A2.ScontiPremi 
			, A1.SpTrasp = a2.SpTrasp
			, a1.Provvi = a2.Provvi
			, a1.Imballi = a2.Imballi
			, a1.Amministrazione = a2.Amministrazione
			, a1.SpVendita = a2.SpVendita
			, a1.SpMagazzino = a2.SpMagazzino
			, a1.SpeseProd = a2.SpeseProd
			, a1.CostoAggiunto = a2.CostoAggiunto
			, a1.Preleva = a2.Preleva
			, a1.TestMateriePrime = a2.TestMateriePrime
			, a1.TOL = a2.TOL
			, a1.FLAG_BOLLETTINO = a2.FLAG_BOLLETTINO
			, a1.SCOSTAMENTO_PRZ = a2.SCOSTAMENTO_PRZ
			, a1.XLS_CHEMDES = a2.XLS_CHEMDES
			, a1.XLS_CASNR = a2.XLS_CASNR
			, a1.XLS_ORGGOODS = a2.XLS_ORGGOODS
			, a1.XLS_ORGFORMULA = a2.XLS_ORGFORMULA
			, a1.XLS_VARORGFORMULA = a2.XLS_VARORGFORMULA 
			, a1.XLS_OPDIVISION = a2.XLS_OPDIVISION
			, a1.XLS_COSTDIRWAGES = a2.XLS_COSTDIRWAGES
			, a1.XLS_COSTPRODOVERHEAD = a2.XLS_COSTPRODOVERHEAD
			, a1.XLS_COSTRAWMAT = a2.XLS_COSTRAWMAT
			, a1.XLS_COSTRAWMAT_VEN = a2.XLS_COSTRAWMAT_VEN
			, a1.FLAG_ADR = a2.FLAG_ADR
			, a1.PATH_SCHEDASICUREZZA_ITA = a2.PATH_SCHEDASICUREZZA_ITA
			, a1.PATH_SCHEDASICUREZZA_EST = a2.PATH_SCHEDASICUREZZA_EST
			, a1.MACRO_ART = a2.MACRO_ART
			, a1.PRV_VAR = a2.PRV_VAR
			, a1.BSCKNOS = a2.BSCKNOS
			, a1.FLAG_RSPO = a2.FLAG_RSPO
			, a1.NRPEZZIIMBALLO = @NRPEZZIIMBALLO
		--SELECT *
		FROM EXTRAMAG a1, EXTRAMAG a2
		WHERE 
			a1.CODART = @CODART
			AND a2.CODART = @ARTMODELLO
			AND LEFT(a1.CODART , 1) = '2'
		
		-- LISTINI
		DELETE A1 
		FROM LISTINIARTICOLI A1 
		WHERE a1.CODART = @CODART 
			AND LEFT(@CODART , 1) = '2'
			
		
		-- articoli originali con imballo qualificato
		IF (LEFT(@CODART , 1) = '2' AND RIGHT(@OLDCODART, 3) <> 'XXX')
		BEGIN
			INSERT INTO dbo.LISTINIARTICOLI (CODART, NRLISTINO, UM, PREZZO, PREZZOEURO, UTENTEMODIFICA, DATAMODIFICA, DeltaIncremento, TP_CodConto, TP_ConsPP, TP_PrezzoPart, TP_PrezzoPartEuro, TP_Scorporo, TP_Sconti, TP_QTASCONTO, TP_QTACOEFF, TP_QTAMO, TP_Abbuono, TP_DataCambio, TP_ValoreCambio, DATAVALIDITA, TP_FormulaSct, PREZZOCALC, TP_ABBUONOEURO)
			SELECT @CODART, T.NRLISTINO, UM, PREZZO, PREZZOEURO, 'TRM', GETDATE(), DeltaIncremento, TP_CodConto, TP_ConsPP, TP_PrezzoPart, TP_PrezzoPartEuro, TP_Scorporo, TP_Sconti, TP_QTASCONTO, TP_QTACOEFF, TP_QTAMO, TP_Abbuono, TP_DataCambio, TP_ValoreCambio, DATAVALIDITA, TP_FormulaSct, PREZZOCALC, TP_ABBUONOEURO
			FROM LISTINIARTICOLI t 
			WHERE T.CODART = @OLDCODART
				AND LEFT(@CODART , 1) = '2'
				AND NOT EXISTS (SELECT 1 FROM LISTINIARTICOLI x WHERE @CODART = X.CODART AND x.NRLISTINO = T.NRLISTINO)
		END
		ELSE
		BEGIN		
			INSERT INTO dbo.LISTINIARTICOLI (CODART, NRLISTINO, UM, PREZZO, PREZZOEURO, UTENTEMODIFICA, DATAMODIFICA, DeltaIncremento, TP_CodConto, TP_ConsPP, TP_PrezzoPart, TP_PrezzoPartEuro, TP_Scorporo, TP_Sconti, TP_QTASCONTO, TP_QTACOEFF, TP_QTAMO, TP_Abbuono, TP_DataCambio, TP_ValoreCambio, DATAVALIDITA, TP_FormulaSct, PREZZOCALC, TP_ABBUONOEURO)
			SELECT @CODART, T.NRLISTINO, UM, PREZZO, PREZZOEURO, 'TRM', GETDATE(), DeltaIncremento, TP_CodConto, TP_ConsPP, TP_PrezzoPart, TP_PrezzoPartEuro, TP_Scorporo, TP_Sconti, TP_QTASCONTO, TP_QTACOEFF, TP_QTAMO, TP_Abbuono, TP_DataCambio, TP_ValoreCambio, DATAVALIDITA, TP_FormulaSct, PREZZOCALC, TP_ABBUONOEURO
			FROM LISTINIARTICOLI t 
			WHERE T.CODART = @ARTMODELLO
				AND LEFT(@CODART , 1) = '2'
				AND NOT EXISTS (SELECT 1 FROM LISTINIARTICOLI x WHERE @CODART = X.CODART AND x.NRLISTINO = T.NRLISTINO)
		END	
			
		
		DELETE A1 
		FROM CONTROPARTARTICOLI A1 
		WHERE a1.CODART = @CODART 
		
		INSERT INTO dbo.CONTROPARTARTICOLI (CODART, ESERCIZIO, NUMERO, SCGEN, UTENTEMODIFICA, DATAMODIFICA)
		SELECT @CODART, T.ESERCIZIO, T.NUMERO, T.SCGEN, 'TRM', GETDATE()
		FROM CONTROPARTARTICOLI t 
		WHERE T.CODART = @ARTMODELLO
			AND LEFT(@CODART , 1) = '2'



		IF LEFT(@CODART , 1) IN ('2', '3', '4') AND RIGHT(@CODART, 3) = 'XXX'
		BEGIN
			
			--PRINT '-- AGGIORNO CODICI STANDARD ' + @CODART
		
			EXEC ITA_UPDATECODICISOST  @OLDCODART, @CODIMBALLO, @CODART    
			
			
			UPDATE a1
			SET 
				a1.NRPEZZIIMBALLO = @NRPEZZIIMBALLO --a2.NRPEZZIIMBALLO
				, a1.RIFERIMIMBALLO = LEFT(@CODIMBALLO, 3) --(SELECT TOP 1 tabimballi.CODICE FROM TABIMBALLI WHERE tabimballi.VARIANTEIMBALLO = RIGHT(a1.CODICE, 3))
			FROM ANAGRAFICAARTICOLI a1
			WHERE 
				a1.CODICE = @CODART
				AND LEFT(a1.CODICE , 1) IN ('2', '3', '4')	 
			
			UPDATE EXTRAMAG
			SET NRPEZZIIMBALLO = @NRPEZZIIMBALLO	
			WHERE CODART = @CODART
				
		END
						
		-- inserimento in tabella articoli adr
		INSERT INTO dbo.TAB_ARTICOLIADR (CODART, CLASSEADR, NUMORD, NUMONU, NUMPER, GI, UTENTEMODIFICA, DATAMODIFICA, DESIGN_TRASP, COD_GALLERIE, ESENZIONE_QTA)
		SELECT @CODART, CLASSEADR, NUMORD, NUMONU, NUMPER, GI, 'trm', getdate(), DESIGN_TRASP, COD_GALLERIE, ESENZIONE_QTA
		FROM TAB_ARTICOLIADR t 
		WHERE (t.CODART = @ARTMODELLO OR t.CODART = @OLDCODART)
		AND @CODART NOT IN (SELECT x.codart FROM TAB_ARTICOLIADR x)	  
		

		-- AGGIORNAMENTO STORICOMAG
		--SELECT S.CODART, S.RIFERIMENTI, t.DESCRIZIONE, a.DESCRIZIONE, r.IDTESTA, r.IDRIGA
		
		UPDATE s SET s.CODART = @CODART
		
		FROM RIGHEDOCUMENTI r JOIN STORICOMAG S ON S.IDTESTA = R.IDTESTA AND S.RIGADOC = R.IDRIGA
		JOIN tabimballi t ON t.CODICE = r.CODIMBALLO
		WHERE r.RIGACHIUSA = 0 AND r.QTAGESTRES > 0 AND r.TIPODOC IN ('OCG', 'OCC', 'OCE')
		AND r.CODART = @OLDCODART AND r.CODIMBALLO = @CODIMBALLO

		-- AGGIORNAMENTO RIGHEDOCUMENTI
		--SELECT r.CODART, r.CODIMBALLO, e.NUOVOCODART, t.DESCRIZIONE, a.DESCRIZIONE, r.IDTESTA, r.IDRIGA		
		
		UPDATE r
		SET r.CODART = @CODART
		FROM RIGHEDOCUMENTI r 
		JOIN tabimballi t ON t.CODICE = r.CODIMBALLO
		WHERE r.RIGACHIUSA = 0 AND r.QTAGESTRES > 0 AND r.TIPODOC IN ('OCG', 'OCC', 'OCE')
		AND r.CODART = @OLDCODART AND r.CODIMBALLO = @CODIMBALLO
		
		
		
		
	END
END
GO

GRANT EXECUTE ON dbo.ZS_GENERAARTICOLO_POST TO Metodo98
GO







IF OBJECT_ID ('dbo.ZS_GENERAARTICOLI_GESTIONEPREZZI') IS NOT NULL
	DROP PROCEDURE dbo.ZS_GENERAARTICOLI_GESTIONEPREZZI
GO

CREATE PROCEDURE ZS_GENERAARTICOLI_GESTIONEPREZZI(@CODART VARCHAR(50), @OLDCODART VARCHAR(50)) AS

--	DECLARE @CODART VARCHAR(50)
--	DECLARE @OLDCODART VARCHAR(50)
	
--	SELECT @OLDCODART = '20505#013XXX'
--	SELECT @CODART = '20505#013000004'
	DECLARE @CSQL AS VARCHAR(5000)
	DECLARE @N AS SMALLINT
	DECLARE @NOMECAMPO AS VARCHAR(80)
	DECLARE @NOMETABELLA AS VARCHAR(80)
	
	DECLARE @PROGRESSIVO AS DECIMAL(10)
	DECLARE @IDRIGA DECIMAL(10)
	DECLARE @PPROG DECIMAL (10)
	DECLARE @PIDRIGA DECIMAL (10)
	DECLARE @IMBALLO AS VARCHAR(10)
	
--	DELETE FROM GESTIONEPREZZI WHERE CODART = @CODART AND CODCLIFOR = 'C' AND INIZIOVALIDITA = FINEVALIDITA

	PRINT @CODART
	PRINT @OLDCODART
	PRINT RIGHT(@CODART, 3)


	DECLARE rSqlA CURSOR LOCAL KEYSET FOR 
	SELECT G.PROGRESSIVO, R.IDRIGA, r.COD_IMBALLO
	FROM GESTIONEPREZZI g JOIN GESTIONEPREZZIRIGHE r ON g.PROGRESSIVO = r.RIFPROGRESSIVO
	JOIN TABIMBALLI T ON T.CODICE = R.COD_IMBALLO
	WHERE g.CODART = @OLDCODART AND T.VARIANTEIMBALLO = RIGHT(@CODART, 3)
	--AND charindex('?', g.codart) = 0
	--AND g.INIZIOVALIDITA = g.FINEVALIDITA  
	
	OPEN rSqlA

	FETCH NEXT from rSqlA INTO @PROGRESSIVO, @IDRIGA, @IMBALLO
	WHILE (@@FETCH_STATUS <> -1)
		BEGIN
		
			PRINT @PROGRESSIVO
			PRINT @IDRIGA
			PRINT @IMBALLO
			
			SELECT @PPROG = 0

			SELECT TOP 1 @PPROG = X.PROGRESSIVO 
			FROM GESTIONEPREZZI X WHERE X.CODART = @CODART  --AND X.INIZIOVALIDITA = X.FINEVALIDITA
			
			PRINT @PPROG
			
			IF (@PPROG = 0)
			BEGIN

				PRINT ' CREO LA CONDIZIONE DI PREZZO ' +  @CODART
				EXECUTE dbo.NUOVOPROGRESSIVO 'GESTIONEPREZZI', 1, @PPROG OUT
				SELECT "@PPROG" = @PPROG
	
				INSERT INTO dbo.GESTIONEPREZZI (PROGRESSIVO, CODGRUPPOPREZZICF, CODCLIFOR, CODART, CODGRUPPOPREZZIMAG, INIZIOVALIDITA, FINEVALIDITA, USANRLISTINO, TIPOARROT, ARROTALIRE, ARROTAEURO, CODARTRIC, UTENTEMODIFICA, DATAMODIFICA, PROGRESSIVOCTR)
				SELECT @PPROG, CODGRUPPOPREZZICF, CODCLIFOR, @CODART, CODGRUPPOPREZZIMAG, INIZIOVALIDITA, FINEVALIDITA, USANRLISTINO, TIPOARROT, ARROTALIRE, ARROTAEURO, @CODART, UTENTEMODIFICA, DATAMODIFICA, PROGRESSIVOCTR
				FROM GESTIONEPREZZI 
				WHERE PROGRESSIVO = @PROGRESSIVO 
				AND NOT EXISTS(SELECT 1 FROM GESTIONEPREZZI X WHERE X.CODART = @CODART) 
	 		
			END
			
	 			   
	 		IF NOT EXISTS(SELECT 1 FROM GESTIONEPREZZIRIGHE X JOIN GESTIONEPREZZI XT ON XT.PROGRESSIVO = X.RIFPROGRESSIVO 
			WHERE XT.CODART = @CODART AND X.COD_IMBALLO = @IMBALLO AND XT.PROGRESSIVO = @PPROG)
			
			BEGIN
				
				PRINT ' CREO LA CONDIZIONE '
				
				EXECUTE dbo.NUOVOPROGRESSIVO 'GESTIONEPREZZIRIGHE', 1, @PIDRIGA OUT
				SELECT "@PIDRIGA" = @PIDRIGA  
						
				INSERT INTO dbo.GESTIONEPREZZIRIGHE (IDRIGA, RIFPROGRESSIVO, NRLISTINO, UM, QTAMINIMA, PREZZO_MAGG, PREZZO_MAGGEURO, SCONTO_UNICO, SCONTO_AGGIUNTIVO, TIPO, UTENTEMODIFICA, DATAMODIFICA, TP_QTASCONTO, TP_QTACOEFF, COD_IMBALLO, QTA_COLLI)
				SELECT @PIDRIGA, @PPROG, NRLISTINO, UM, QTAMINIMA, PREZZO_MAGG, PREZZO_MAGGEURO, SCONTO_UNICO, SCONTO_AGGIUNTIVO, TIPO, UTENTEMODIFICA, DATAMODIFICA, TP_QTASCONTO, TP_QTACOEFF, COD_IMBALLO, QTA_COLLI
				FROM GESTIONEPREZZIRIGHE 
				WHERE RIFPROGRESSIVO = @PROGRESSIVO AND IDRIGA = @IDRIGA 
				
			END		  	
			
			FETCH NEXT from rSqlA INTO @PROGRESSIVO, @IDRIGA, @IMBALLO
		END

	CLOSE rSqlA
	DEALLOCATE rSqlA



GO

GRANT EXECUTE ON dbo.ZS_GENERAARTICOLI_GESTIONEPREZZI TO Metodo98
GO







IF OBJECT_ID ('dbo.ITA_UPDATECODICISOST') IS NOT NULL
	DROP PROCEDURE dbo.ITA_UPDATECODICISOST
GO

CREATE PROCEDURE ITA_UPDATECODICISOST  (@OLDCODART VARCHAR(50), @CODIMBALLO VARCHAR(10), @NEWCODART VARCHAR(50) ) AS
	DECLARE @CSQL_S AS VARCHAR(5000)
	DECLARE @CSQL_U AS VARCHAR(5000)
	DECLARE @CSQL_U0 AS VARCHAR(5000)
	DECLARE @CSQL_U1 AS VARCHAR(5000)
	DECLARE @CSQL_U2 AS VARCHAR(5000)
	DECLARE @TABELLA AS VARCHAR(500)

	SET @CSQL_U0 = 'UPDATE R SET R.CODART = ''' + @NEWCODART + ''' ' +
	' FROM RIGHEDOCUMENTI R ' +  
	' WHERE R.TIPODOC IN (''OCC'', ''OCE'', ''OCG'') AND R.CODART = ''' + @OLDCODART + ''' AND ((R.RIGACHIUSA = 1 AND R.QTAGESTRES = 0) OR (R.CODIMBALLO  NOT IN (SELECT X.CODICE FROM ZS_GENERAARTICOLI_POST X WHERE X.CODART =  ''' + @OLDCODART + ''')))'
	
	SET @CSQL_U1 = 'UPDATE S SET S.CODART = ''' + @NEWCODART + '''  ' +
	' FROM RIGHEDOCUMENTI R JOIN STORICOMAG S ON S.IDTESTA = R.IDTESTA AND S.RIGADOC = R.IDRIGA' +  
	' WHERE R.TIPODOC IN (''OCC'', ''OCE'', ''OCG'') AND R.CODART = ''' + @OLDCODART + ''' AND ((R.RIGACHIUSA = 1 AND R.QTAGESTRES = 0) OR (R.CODIMBALLO  NOT IN (SELECT X.CODICE FROM ZS_GENERAARTICOLI_POST X WHERE X.CODART =  ''' + @OLDCODART + ''')))'

	
	SET @CSQL_U2 = 'UPDATE P SET P.CODARTICOLO = ''' + @NEWCODART + '''  ' + 
	' FROM RIGHEDOCUMENTI R JOIN STORICOMAG S ON S.IDTESTA = R.IDTESTA AND S.RIGADOC = R.IDRIGA ' +
	' JOIN STORICOPREZZIARTICOLO P ON P.RIFSTORICOMAG = S.PROGRESSIVO' +
	' WHERE R.TIPODOC IN (''OCC'', ''OCE'', ''OCG'') AND R.CODART = ''' + @OLDCODART + ''' AND ((R.RIGACHIUSA = 1 AND R.QTAGESTRES = 0) OR (R.CODIMBALLO  NOT IN (SELECT X.CODICE FROM ZS_GENERAARTICOLI_POST X WHERE X.CODART =  ''' + @OLDCODART + ''')))'
	

	IF LEFT(@oldcodart, 1) IN ('3', '4') AND 
		(
			SELECT count(*) FROM ZS_VISTA_GENERAARTICOLI X WHERE X.NUOVOCODART = @NEWCODART -- AND TIPO IN ('A', 'B')
		) = 1
	BEGIN
	
		--PRINT 'SERIE 30000, 40000aaaaa'
	
		DECLARE rSqlA CURSOR LOCAL KEYSET FOR 
	
		SELECT TABELLA
		, 'SELECT ' + '*' + ' FROM ' + TABELLA + ' WHERE '+ CAMPO + ' = ''' + @OLDCODART + ''''  AS STRSQL_S
		, 'UPDATE ' + TABELLA + ' SET ' + CAMPO + ' = ''' + @NEWCODART + ''' WHERE '+ CAMPO + ' = ''' + @OLDCODART + '''' AS STRSQL
		--, * 
		--, 'UPDATE ITA_CODICISOST SET SEL = 0 WHERE TABELLA = ''' + TABELLA + ''' AND (SELECT COUNT(*) FROM ' + TABELLA + ' WHERE ' + CAMPO + ' IN (SELECT Z.CODART FROM ZS_GENERAARTICOLI z)) = 0' AS STRSQL
		FROM ITA_CODICISOST i 
		WHERE i.SEL = 1
		
	
	--	ORDER BY C.COLUMN_NAME
		OPEN rSqlA
	
		FETCH NEXT from rSqlA INTO @TABELLA,  @CSQL_S, @CSQL_U
		WHILE (@@FETCH_STATUS <> -1)
			BEGIN
				
				--PRINT @TABELLA
				
				IF @TABELLA = 'TABLOTTIRIORDINO'
				BEGIN
					DELETE FROM TABLOTTIRIORDINO WHERE CODART = @NEWCODART AND EXISTS(SELECT TOP 1 1 FROM TABLOTTIRIORDINO X WHERE X.CODART = @OLDCODART)
				END
				
				PRINT @CSQL_U
				--EXEC (@CSQL_U)
	
	
				
	
			
				--PRINT @@ROWCOUNT
		
				FETCH NEXT from rSqlA INTO @TABELLA, @CSQL_S, @CSQL_U
			END
	
		CLOSE rSqlA
		DEALLOCATE rSqlA
			
	END



	IF LEFT(@oldcodart, 1) = '2'
	BEGIN
	

		DECLARE rSqlA CURSOR LOCAL KEYSET FOR 
	
		SELECT TABELLA
		, 'SELECT ' + '*' + ' FROM ' + TABELLA + ' WHERE '+ CAMPO + ' = ''' + @OLDCODART + ''''  AS STRSQL_S
		, (CASE 
			--WHEN TABELLA = 'GESTIONEPREZZI' THEN
			--	'UPDATE ' + TABELLA + ' SET CODART = ''' + @OLDCODART + '#??????'', CODARTRIC = ''' + @OLDCODART + '#___%'' WHERE INIZIOVALIDITA = FINEVALIDITA AND '+ CAMPO + ' = ''' + @OLDCODART + ''''
			WHEN TABELLA = 'RELAZIONICFV' AND CAMPO = 'VARIANTI' THEN
				'UPDATE ' + TABELLA + ' SET VARIANTI = ''' + SUBSTRING(@NEWCODART, CHARINDEX('#', @NEWCODART) + 1, LEN(@NEWCODART) - CHARINDEX('#', @NEWCODART)) + ''' WHERE ARTICOLO  + ''#'' + ' + CAMPO + ' = ''' + @OLDCODART + ''''
			ELSE
				'UPDATE ' + TABELLA + ' SET ' + CAMPO + ' = ''' + @NEWCODART + ''' WHERE '+ CAMPO + ' = ''' + @OLDCODART + ''''
			END)  
			AS STRSQL
		--, * 
		--, 'UPDATE ITA_CODICISOST SET SEL = 0 WHERE TABELLA = ''' + TABELLA + ''' AND (SELECT COUNT(*) FROM ' + TABELLA + ' WHERE ' + CAMPO + ' IN (SELECT Z.CODART FROM ZS_GENERAARTICOLI z)) = 0' AS STRSQL
		FROM ITA_CODICISOST i 
		WHERE I.SEL = 1
	
	--	ORDER BY C.COLUMN_NAME
		OPEN rSqlA
	
		FETCH NEXT from rSqlA INTO @TABELLA,  @CSQL_S, @CSQL_U
		WHILE (@@FETCH_STATUS <> -1)
			BEGIN
				
				--PRINT @TABELLA
				
				/*
				IF @TABELLA = 'RIGHEDOCUMENTI'
				BEGIN
	
	
	
					PRINT @CSQL_U2
					EXEC (@CSQL_U2)
		
					PRINT @CSQL_U1

					EXEC (@CSQL_U1)
					
					PRINT @CSQL_U0
					EXEC (@CSQL_U0)					
					
				END
				*/
				
				--PRINT @CSQL_U
				EXEC (@CSQL_U)
	
	
				
	
				
				--PRINT @@ROWCOUNT
		
				FETCH NEXT from rSqlA INTO @TABELLA, @CSQL_S, @CSQL_U
			END
	
		CLOSE rSqlA
		DEALLOCATE rSqlA
		
		RETURN
		
	END
GO

GRANT EXECUTE ON dbo.ITA_UPDATECODICISOST TO Metodo98
GO



IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI_MOV') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI_MOV
GO

CREATE VIEW ZS_VISTA_GENERAARTICOLI_MOV
AS

SELECT * FROM (
	SELECT DISTINCT 
	(CASE WHEN charindex('#', R.CODART) > 1 THEN LEFT(R.CODART, charindex('#', R.CODART) - 1) ELSE R.CODART END) AS ARTTIPOLOGIA
	, R.CODART, R.CODIMBALLO AS CODICE, I.DESCRIZIONE AS DESCRIMBALLO, I.VARIANTEIMBALLO, V.DESCRIZIONE AS DESCRVARIANTE
	, (CASE WHEN LEFT(R.CODART, 1) IN ('3', '4') THEN
		 (CASE 
		WHEN RIGHT(R.CODART, 3) = 'XXX' THEN REPLACE(R.CODART, 'XXX',  '000' + I.VARIANTEIMBALLO)
		--WHEN RIGHT(R.CODART, 3) <> 'XXX' AND I.VARIANTEIMBALLO = 'XXX' THEN REPLACE(R.CODART, RIGHT(R.CODART, 3),  '000' + RIGHT(R.CODART, 3))
		ELSE R.CODART + '#000' + '000' + I.VARIANTEIMBALLO
		END) 
	ELSE	
	 --(CASE WHEN RIGHT(R.CODART, 3) = 'XXX' THEN LEFT(R.CODART, LEN(R.CODART) - 3) +  '000' + RIGHT(R.CODART, 3)
		--ELSE 
		LEFT(R.CODART, LEN(R.CODART) - 3) +  '000' + I.VARIANTEIMBALLO
		--END) 
	END) AS NUOVOCODART
	
FROM RIGHEDOCUMENTI R WITH (NOLOCK) 
JOIN TABIMBALLI I WITH (NOLOCK) ON I.CODICE = R.CODIMBALLO
JOIN TABVARIANTI v WITH (NOLOCK) ON v.VARIANTE = I.varianteimballo
WHERE R.CODART <> ''  AND r.TIPODOC IN ('oce', 'occ', 'ocg') AND V.TIPOLOGIA = '62' --AND r.RIGACHIUSA = 0 AND r.QTAGESTRES > 0
AND I.VARIANTEIMBALLO <> ''
AND len(r.CODART) <= 12
	) CTE
WHERE LEN(ARTTIPOLOGIA) = 5
	AND ARTTIPOLOGIA BETWEEN '20000' AND '49999' 
	
	AND charindex('#', substring(nuovocodart, charindex('#', nuovocodart) + 1, 10) ) = 0
	--AND NUOVOCODART NOT IN (SELECT CODICE FROM ANAGRAFICAARTICOLI)
	
	
UNION
	
SELECT 
	LEFT(A.CODICE, 5) AS ARTTIPOLOGIA
	, a.CODICE AS CODART
	, 'XXX' AS CODICE
	, '' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO
	, '' AS DESCRVARIANTE
	, (CASE WHEN RIGHT(A.CODICE, 3) <> 'XXX' THEN LEFT(A.CODICE, LEN(A.CODICE) - 3) +  '000' + RIGHT(A.CODICE, 3)
	ELSE 	REPLACE(A.CODICE, 'XXX',  '000XXX')
	END) AS NUOVOCODART 
FROM 
	ANAGRAFICAARTICOLI a 
WHERE 
	a.CODICEPRIMARIO in
	(SELECT CODICE FROM ANAGRAFICAARTICOLI 
	WHERE ARTTIPOLOGIA = 1
	AND isnumeric(codice) = 1
	AND CODICE BETWEEN '20000' AND '49999')
	AND len(A.CODICE) <= 12
	AND patindex('%#k%', CODICE) = 0
GO

GRANT DELETE ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO

GRANT INSERT ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO

GRANT REFERENCES ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO

GRANT SELECT ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO

GRANT UPDATE ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO


IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI
GO

CREATE VIEW ZS_VISTA_GENERAARTICOLI
AS
/*
SELECT *, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WHERE A.CODICE = CTE.CODART OR A.CODICE = CTE.ARTTIPOLOGIA) AS DESCRIZIONE FROM (
	SELECT distinct
	(CASE WHEN charindex('#', g.CODART) > 1 THEN LEFT(g.CODART, charindex('#', g.CODART) - 1) ELSE g.CODART END) AS ARTTIPOLOGIA
	, g.CODART
	, t.CODICE
	, t.varianteimballo
	, (CASE 
		WHEN charindex('#', g.CODART) > 0 AND charindex('?', g.codart) = 0 THEN LEFT(g.CODART, charindex('#', g.CODART) + 3) + T.VARIANTEIMBALLO 
		WHEN charindex('#', g.CODART) > 0 AND charindex('?', g.codart) > 0 THEN LEFT(g.CODART, charindex('#', g.CODART)) + '000' + T.VARIANTEIMBALLO 
		ELSE
			g.CODART + '#000' + T.VARIANTEIMBALLO 
		END) AS NUOVOCODART
		--, g.*
	FROM GESTIONEPREZZI g JOIN GESTIONEPREZZIRIGHE r ON g.PROGRESSIVO = r.RIFPROGRESSIVO
	JOIN tabimballi t ON t.CODICE = r.cod_imballo 
	JOIN TABVARIANTI v ON v.VARIANTE = t.varianteimballo
	WHERE g.INIZIOVALIDITA = g.FINEVALIDITA and t.varianteimballo  <> '' --AND charindex('?', g.codart) = 0
	--AND t.codice NOT IN (100, 101)
	) CTE
WHERE 
	NUOVOCODART NOT IN (SELECT CODICE FROM ANAGRAFICAARTICOLI)
	AND ARTTIPOLOGIA BETWEEN '20000' AND '49999'
	*/


SELECT X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART
	, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WITH (NOLOCK) WHERE A.CODICE = X.CODART OR A.CODICE = X.ARTTIPOLOGIA) AS DESCRIZIONE --, '' AS TIPO
	, (SELECT 'B' FROM ZS_VISTA_GENERAARTICOLI_MOV Z WHERE Z.CODART = X.CODART AND LEFT(Z.CODART, 1) <> '2' GROUP BY Z.CODART HAVING COUNT(Z.CODART) = 1 ) AS TIPO
	, (CASE WHEN X.CODICE <> 'XXX' THEN 0 ELSE 9999 END) AS ORDINAMENTO

FROM 
	 ZS_VISTA_GENERAARTICOLI_MOV x -- ON  x.ARTTIPOLOGIA = cte.arttipologia AND x.CODIMBALLO = cte.cod_imballo
UNION
SELECT 
	X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART, X.DESCRIZIONE, X.TIPO 
	, (CASE WHEN X.CODICE <> 'XXX' THEN 0 ELSE 9999 END) AS ORDINAMENTO
FROM 
	ZS_VISTA_GENERAARTICOLI_MODELLI X
GO

GRANT DELETE ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO

GRANT INSERT ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO

GRANT REFERENCES ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO

GRANT SELECT ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO

GRANT UPDATE ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO


IF OBJECT_ID ('dbo.ZS_GENERAARTICOLI') IS NOT NULL
	DROP TABLE dbo.ZS_GENERAARTICOLI
GO

CREATE TABLE dbo.ZS_GENERAARTICOLI
	(
	ARTTIPOLOGIA    VARCHAR (50) NULL,
	CODART          VARCHAR (50) NOT NULL,
	CODICE          VARCHAR (10) NOT NULL,
	DESCRIZIONE     VARCHAR (500) NULL,
	VARIANTEIMBALLO VARCHAR (25) NULL,
	NUOVOCODART     VARCHAR (50) NOT NULL,
	UtenteModifica  VARCHAR (25) NOT NULL,
	DataModifica    DATETIME NOT NULL,
	ORDINAMENTO     INT NULL,
	CONSTRAINT PK__ZS_GENER__74CEDBB85D859AAB PRIMARY KEY (NUOVOCODART,CODICE,CODART)
	)
GO

GRANT DELETE ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO

GRANT INSERT ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO

GRANT REFERENCES ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO

GRANT SELECT ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO

GRANT UPDATE ON dbo.ZS_GENERAARTICOLI TO Metodo98
GO



