IF OBJECT_ID ('dbo.VISTA_NOTIFICHEBSCCOA_ARTICOLI') IS NOT NULL
	DROP VIEW dbo.VISTA_NOTIFICHEBSCCOA_ARTICOLI
GO

CREATE view VISTA_NOTIFICHEBSCCOA_ARTICOLI as 

SELECT 
	RR.IDTESTA, RR.IDRIGA, RR.QTAGEST, RR.QTAGESTRES, RR.DATACONSEGNA,
	RR.CODART AS CODARTDOC, RR.DESCRIZIONEART
	, ISNULL((SELECT TOP 1 Z.CODART FROM ZS_GENERAARTICOLI_POST Z WITH (NOLOCK) WHERE Z.NUOVOCODART = RR.CODART), RR.CODART) AS CODART
FROM RIGHEDOCUMENTI RR WITH (NOLOCK)
WHERE RR.TIPODOC IN (SELECT codice FROM PARAMETRIDOC p WITH (NOLOCK) WHERE p.TIPO = 'b' AND p.CLIFOR = 'c')
AND RR.CODART <> ''
GO

GRANT DELETE ON dbo.VISTA_NOTIFICHEBSCCOA_ARTICOLI TO Metodo98
GO

GRANT INSERT ON dbo.VISTA_NOTIFICHEBSCCOA_ARTICOLI TO Metodo98
GO

GRANT REFERENCES ON dbo.VISTA_NOTIFICHEBSCCOA_ARTICOLI TO Metodo98
GO

GRANT SELECT ON dbo.VISTA_NOTIFICHEBSCCOA_ARTICOLI TO Metodo98
GO

GRANT UPDATE ON dbo.VISTA_NOTIFICHEBSCCOA_ARTICOLI TO Metodo98
GO



IF OBJECT_ID ('dbo.VISTA_NOTIFICHEBSCCOA') IS NOT NULL
	DROP VIEW dbo.VISTA_NOTIFICHEBSCCOA
GO

CREATE view VISTA_NOTIFICHEBSCCOA as 

SELECT 
	a.codconto AS CODCLIFOR
	, a.dscconto1 AS RAGIONESOCIALE
	, isnull(dbo.fn_GetEMAILCONTATTICLIENTECOA(a.codconto), '') + isnull((SELECT TOP 1 d.email FROM DESTINAZIONIDIVERSE d WHERE d.CODCONTO = a.codconto AND d.CODICE = t.NUMDESTDIVERSAMERCI), '') AS EMAIL_CLIENTE
	, '' AS EMAIL_AGENTE
	, t.TIPODOC + '/' + CAST(t.ESERCIZIO AS VARCHAR) + '/' + CAST(t.NUMERODOC AS VARCHAR) + '/' + t.BIS AS DOCUMENTO
	, isnull(RCFV.articolobsc, r.CODART) AS ARTICOLOBSC
	, r.DESCRIZIONEART AS DESCRIZIONEARTICOLO
	, e.DATAINVIOCOA
	, r.QTAGEST
	, r.QTAGESTRES
	, isnull(e.NRLOTTO, 'NESSUN LOTTO') AS Lotto
	, I.idpubblicazioneknos AS IDOBJECT_DOC
	, '' AS PATHCOA
	, ((CASE WHEN charindex('#', isnull(RCFV.articolobsc, r.CODART)) > 0 THEN LEFT(isnull(RCFV.articolobsc, r.CODART), len(isnull(RCFV.articolobsc, r.CODART)) -3) ELSE r.CODART END) 
	+ '*_' + isnull(e.NRLOTTO, 'NESSUN LOTTO')
	) AS filenamecoacalc1
	, ((CASE WHEN charindex('#', isnull(RCFV.articolobsc, r.CODART)) > 0 THEN LEFT(isnull(RCFV.articolobsc, r.CODART), len(isnull(RCFV.articolobsc, r.CODART)) -3) ELSE r.CODART END) 
	+ ltrim(substring(a.CODCONTO, 2, 6))
	+ '*_' + isnull(e.NRLOTTO, 'NESSUN LOTTO')
	) AS filenamecoacalc2
	, R.IDTESTA, R.IDRIGA
	, t.TIPODOC
	, t.ESERCIZIO
	, t.NUMERODOC
	, t.BIS
	, t.DATADOC
	, r.DATACONSEGNA
	, r.CODART 
	, ic.IdPubblicazioneKnos AS IDOBJECT_CLI
	, isnull(RCFV.articolobsc, '') AS articolobscrel
	, t.NUMDESTDIVERSAMERCI
FROM VISTA_NOTIFICHEBSCCOA_ARTICOLI r WITH (NOLOCK) JOIN EXTRARIGHEDOC e WITH (NOLOCK) ON e.IDTESTA = r.IDTESTA AND e.IDRIGA = r.IDRIGA
	JOIN TESTEDOCUMENTI t WITH (NOLOCK) ON t.PROGRESSIVO = r.IDTESTA 
	JOIN ANAGRAFICACF a WITH (NOLOCK) ON a.CODCONTO = t.CODCFFATT
	JOIN ita_archivio_documenti I WITH (NOLOCK) ON I.progressivo = t.PROGRESSIVO
	JOIN ita_archivio_clifor IC WITH (NOLOCK) ON IC.CodConto = t.CODCLIFOR
	LEFT OUTER JOIN VistaRelazioniCFV RCFV WITH (NOLOCK) on RCFV.CODCLIFOR = t.CODCLIFOR AND r.CODART = 
          (CASE PATINDEX('%#%', r.CODART) WHEN 0 THEN RCFV.ARTICOLO ELSE (RCFV.ARTICOLO + '#' + RCFV.VARIANTI) END)
WHERE t.TIPODOC IN (SELECT codice FROM PARAMETRIDOC p WITH (NOLOCK) WHERE p.TIPO = 'b' AND p.CLIFOR = 'c') 
--AND isnull(e.nrLotto, '') <> ''
--AND r.QTAGESTRES > 0
AND r.CODART <> ''
GO

GRANT DELETE ON dbo.VISTA_NOTIFICHEBSCCOA TO Metodo98
GO

GRANT INSERT ON dbo.VISTA_NOTIFICHEBSCCOA TO Metodo98
GO

GRANT REFERENCES ON dbo.VISTA_NOTIFICHEBSCCOA TO Metodo98
GO

GRANT SELECT ON dbo.VISTA_NOTIFICHEBSCCOA TO Metodo98
GO

GRANT UPDATE ON dbo.VISTA_NOTIFICHEBSCCOA TO Metodo98
GO



IF OBJECT_ID ('dbo.VistaRelazioniCFVdaDocZSI') IS NOT NULL
	DROP VIEW dbo.VistaRelazioniCFVdaDocZSI
GO

CREATE VIEW VistaRelazioniCFVdaDocZSI AS 
SELECT
     TD.PROGRESSIVO,
     RD.IDRIGA,
     RCFV.CODCLIFOR,RCFV.RIFERIMENTO,RCFV.ARTICOLO,RCFV.VARIANTI,RCFV.DESCRIZIONE,RCFV.TIPOREL,RCFV.MOSTRAVARIANTI,RCFV.CAPITOLATO,RCFV.SPECIFICAACQ,
     RCFV.NOTE,RCFV.CODBONUS
     , RD.CODART, RD.DESCRIZIONEART
     , dbo.ITA_GetDscVariante(rd.CODART, 62) AS DSCVARIMB
     , replace(rd.descrizioneart, dbo.ITA_GetDscVariante(rd.CODART, 62), '') AS DESCRIZIONERIGA
     --, (CASE WHEN CHARINDEX('#', RD.CODART) > 0 THEN LEFT(RD.CODART, LEN(RD.CODART) -3) ELSE RD.CODART END) AS CODARTRIGA
     , (CASE WHEN TD.ESERCIZIO < 2018 THEN ISNULL((SELECT TOP 1 Z.CODART FROM ZS_GENERAARTICOLI_POST Z WHERE Z.NUOVOCODART = RD.CODART), RD.CODART)
     	ELSE (CASE 
     			WHEN TD.TIPODOC IN ('OCG', 'OCC', 'OCE') AND CHARINDEX('#', RD.CODART) > 0 THEN LEFT(RD.CODART, LEN(RD.CODART) -3) 
     			WHEN TD.TIPODOC IN ('OCG', 'OCC', 'OCE') AND CHARINDEX('#', RD.CODART) = 0 THEN RD.CODART
     			WHEN TD.TIPODOC NOT IN ('OCG', 'OCC', 'OCE') THEN RD.CODART
     		ELSE
     			RD.CODART 
     		END)
     	END) AS CODARTRIGA
     , TD.TIPODOC
 FROM
     TESTEDOCUMENTI TD INNER JOIN RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA
     LEFT OUTER JOIN RELAZIONICFV RCFV ON RD.CODART = 
          (CASE PATINDEX('%#%', RD.CODART) WHEN 0 THEN RCFV.ARTICOLO ELSE (RCFV.ARTICOLO + '#' + RCFV.VARIANTI) END) 
 AND TD.CODCLIFOR = RCFV.CODCLIFOR

GO

GRANT SELECT ON dbo.VistaRelazioniCFVdaDocZSI TO Metodo98
GO


/* correzione condizioni di prezzo ???
SELECT g.CODART, g.CODCLIFOR, r.* 
--UPDATE g SET  g.codart = g.codart + '???'
FROM GESTIONEPREZZI g JOIN GESTIONEPREZZIRIGHE r ON r.RIFPROGRESSIVO = g.PROGRESSIVO
WHERE RIGHT(g.CODART, 7) = '#??????'
*/

/*

SELECT e.codart, e.macro_art, LEFT(e.CODART, 12) + 'XXX' AS NEWMACROART
--UPDATE E SET E.MACRO_ART = LEFT(e.CODART, 12) + 'XXX' 
FROM EXTRAMAG e
WHERE LEN(E.CODART) > 12 AND charindex('#', e.codart) > 0 AND isnull(e.macro_art, '') <> ''

*/

IF OBJECT_ID ('dbo.ZS_GENERAARTICOLI_GESTIONEPREZZI') IS NOT NULL
	DROP PROCEDURE dbo.ZS_GENERAARTICOLI_GESTIONEPREZZI
GO

CREATE PROCEDURE ZS_GENERAARTICOLI_GESTIONEPREZZI(@CODART VARCHAR(50), @OLDCODART VARCHAR(50)) AS

--	DECLARE @CODART VARCHAR(50)
--	DECLARE @OLDCODART VARCHAR(50)
	
--	SELECT @OLDCODART = '20505#013XXX'
--	SELECT @CODART = '20505#013000004'
	DECLARE @CSQL AS VARCHAR(5000)
	DECLARE @N AS SMALLINT
	DECLARE @NOMECAMPO AS VARCHAR(80)
	DECLARE @NOMETABELLA AS VARCHAR(80)
	
	DECLARE @PROGRESSIVO AS DECIMAL(10)
	DECLARE @IDRIGA DECIMAL(10)
	DECLARE @PPROG DECIMAL (10)
	DECLARE @PIDRIGA DECIMAL (10)
	DECLARE @IMBALLO AS VARCHAR(10)
	DECLARE @CODCLIFOR AS VARCHAR(7)
	
--	DELETE FROM GESTIONEPREZZI WHERE CODART = @CODART AND CODCLIFOR = 'C' AND INIZIOVALIDITA = FINEVALIDITA

	PRINT @CODART
	PRINT @OLDCODART
	PRINT RIGHT(@CODART, 3)


	DECLARE rSqlA CURSOR LOCAL KEYSET FOR 
	SELECT G.PROGRESSIVO, R.IDRIGA, r.COD_IMBALLO, g.CODCLIFOR
	FROM GESTIONEPREZZI g JOIN GESTIONEPREZZIRIGHE r ON g.PROGRESSIVO = r.RIFPROGRESSIVO
	JOIN TABIMBALLI T ON T.CODICE = R.COD_IMBALLO
	WHERE g.CODART = @OLDCODART AND T.VARIANTEIMBALLO = RIGHT(@CODART, 3)
	--AND charindex('?', g.codart) = 0
	--AND g.INIZIOVALIDITA = g.FINEVALIDITA  
	
	OPEN rSqlA

	FETCH NEXT from rSqlA INTO @PROGRESSIVO, @IDRIGA, @IMBALLO, @CODCLIFOR
	WHILE (@@FETCH_STATUS <> -1)
		BEGIN
		
			PRINT @PROGRESSIVO
			PRINT @IDRIGA
			PRINT '@IMBALLO: ' +  CAST(@IMBALLO AS VARCHAR)
			PRINT @CODCLIFOR
			
			SELECT @PPROG = 0

			SELECT TOP 1 @PPROG = X.PROGRESSIVO 
			FROM GESTIONEPREZZI X WHERE X.CODART = @CODART AND X.CODCLIFOR = @CODCLIFOR
			
			PRINT @PPROG
			
			IF (@PPROG = 0)
			BEGIN

				PRINT ' CREO LA CONDIZIONE DI PREZZO ' +  @CODART + ' CLIENTE ' + @CODCLIFOR
				EXECUTE dbo.NUOVOPROGRESSIVO 'GESTIONEPREZZI', 1, @PPROG OUT
				SELECT "@PPROG" = @PPROG
	
				INSERT INTO dbo.GESTIONEPREZZI (PROGRESSIVO, CODGRUPPOPREZZICF, CODCLIFOR, CODART, CODGRUPPOPREZZIMAG, INIZIOVALIDITA, FINEVALIDITA, USANRLISTINO, TIPOARROT, ARROTALIRE, ARROTAEURO, CODARTRIC, UTENTEMODIFICA, DATAMODIFICA, PROGRESSIVOCTR)
				SELECT @PPROG, CODGRUPPOPREZZICF, @CODCLIFOR, @CODART, CODGRUPPOPREZZIMAG, INIZIOVALIDITA, FINEVALIDITA, USANRLISTINO, TIPOARROT, ARROTALIRE, ARROTAEURO, @CODART, 'TRM', GETDATE(), PROGRESSIVOCTR
				FROM GESTIONEPREZZI 
				WHERE PROGRESSIVO = @PROGRESSIVO 
				--AND NOT EXISTS(SELECT 1 FROM GESTIONEPREZZI X WHERE X.CODART = @CODART) 
				
				--SET @PROGRESSIVO = @PPROG
	 		
			END
			
	 			   
	 		IF NOT EXISTS(SELECT 1 FROM GESTIONEPREZZIRIGHE X JOIN GESTIONEPREZZI XT ON XT.PROGRESSIVO = X.RIFPROGRESSIVO 
			WHERE XT.CODART = @CODART AND XT.CODCLIFOR = @CODCLIFOR AND X.COD_IMBALLO = @IMBALLO AND XT.PROGRESSIVO = @PPROG)
			
			BEGIN
				
				PRINT ' CREO LA CONDIZIONE NUOVA A PARTIRE DA @PROGRESSIVO ' + CAST(@PROGRESSIVO AS VARCHAR) + ' E @IDRIGA ' + CAST(@IDRIGA AS VARCHAR)
				
				SELECT IDRIGA, RIFPROGRESSIVO, NRLISTINO, UM, QTAMINIMA, PREZZO_MAGG, PREZZO_MAGGEURO, SCONTO_UNICO, SCONTO_AGGIUNTIVO, TIPO, UTENTEMODIFICA, DATAMODIFICA, TP_QTASCONTO, TP_QTACOEFF, COD_IMBALLO, QTA_COLLI
				FROM GESTIONEPREZZIRIGHE 
				WHERE RIFPROGRESSIVO = @PROGRESSIVO AND IDRIGA = @IDRIGA				
				
				EXECUTE dbo.NUOVOPROGRESSIVO 'GESTIONEPREZZIRIGHE', 1, @PIDRIGA OUT
				SELECT "@PIDRIGA" = @PIDRIGA  
						
				INSERT INTO dbo.GESTIONEPREZZIRIGHE (IDRIGA, RIFPROGRESSIVO, NRLISTINO, UM, QTAMINIMA, PREZZO_MAGG, PREZZO_MAGGEURO, SCONTO_UNICO, SCONTO_AGGIUNTIVO, TIPO, UTENTEMODIFICA, DATAMODIFICA, TP_QTASCONTO, TP_QTACOEFF, COD_IMBALLO, QTA_COLLI)
				SELECT @PIDRIGA, @PPROG, NRLISTINO, UM, QTAMINIMA, PREZZO_MAGG, PREZZO_MAGGEURO, SCONTO_UNICO, SCONTO_AGGIUNTIVO, TIPO, UTENTEMODIFICA, DATAMODIFICA, TP_QTASCONTO, TP_QTACOEFF, COD_IMBALLO, QTA_COLLI
				FROM GESTIONEPREZZIRIGHE 
				WHERE RIFPROGRESSIVO = @PROGRESSIVO AND IDRIGA = @IDRIGA 
				
				PRINT ' ------------------------------------- '
			END		  	
			ELSE
			BEGIN 
				PRINT ' ------------- CONDIZIONE GIA'' PRESENTE ------------------------ '
			END
			
			
			FETCH NEXT from rSqlA INTO @PROGRESSIVO, @IDRIGA, @IMBALLO, @CODCLIFOR
		END

	CLOSE rSqlA
	DEALLOCATE rSqlA
GO

GRANT EXECUTE ON dbo.ZS_GENERAARTICOLI_GESTIONEPREZZI TO Metodo98
GO


--SELECT distinct 'EXECUTE dbo.ZS_GENERAARTICOLI_GESTIONEPREZZI ''' + NUOVOCODART +  ''', ''' + CODART +  '''' AS SQL FROM ZS_GENERAARTICOLI_POST
--WHERE NUOVOCODART LIKE '20249%'


IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.columns WHERE TABLE_NAME = 'EXTRAPARDOC' AND COLUMN_NAME = 'ESCLUDIXXX')
	ALTER TABLE EXTRAPARDOC ADD ESCLUDIXXX VARCHAR(1)
GO

UPDATE EXTRAPARDOC SET ESCLUDIXXX = 'S' --WHERE CODICE IN (SELECT PARAMETRIDOC.CODICE FROM PARAMETRIDOC WHERE PARAMETRIDOC.TIPO IN  ('O', 'B'))
GO



IF OBJECT_ID ('dbo.ZS_GENERAARTICOLI_GESTIONENOTEART') IS NOT NULL
	DROP PROCEDURE dbo.ZS_GENERAARTICOLI_GESTIONENOTEART
GO

CREATE PROCEDURE ZS_GENERAARTICOLI_GESTIONENOTEART(@CODCLI AS VARCHAR(7), @coddestdiv AS DECIMAL(5), @codart AS VARCHAR(50), @noteart AS VARCHAR(3000), @codartrif AS VARCHAR(50)) AS
	DECLARE @esistenota SMALLINT	
	
	INSERT INTO dbo.ZSI_NOTEART (CODCLI, CODDEST, CODART, NOTE, UTENTEMODIFICA, DATAMODIFICA)
	SELECT @codcli, @coddestdiv, @codart, NOTE, 'trm', getdate()
	FROM ZSI_NOTEART WHERE CODCLI = @codcli AND CODDEST = @coddestdiv AND codart = @codartrif
	
	SELECT @esistenota = count(*) FROM ZSI_NOTEART
	WHERE CODART = @codart AND CODCLI = @codcli AND CODDEST = @coddestdiv
	
	IF (@esistenota = 0)
	BEGIN
		PRINT ' inserisco la nota '
		INSERT INTO dbo.ZSI_NOTEART (CODCLI, CODDEST, CODART, NOTE, UTENTEMODIFICA, DATAMODIFICA)
		VALUES (@codcli, @coddestdiv, @codart, @noteart, 'trm', getdate())
	END

	UPDATE ZSI_NOTEART
	SET NOTE = @noteart
	WHERE CODART = @codart AND CODCLI = @codcli AND CODDEST = @coddestdiv
	and @noteart <> ''
GO

GRANT EXECUTE ON dbo.ZS_GENERAARTICOLI_GESTIONENOTEART TO Metodo98
GO



EXECUTE dbo.ZS_GENERAARTICOLI_GESTIONENOTEART 	'C  1003', 2, '20247#000000004', '', '20247#000000XXX'

SELECT a.DSCCONTO1, aa.DESCRIZIONE
, (SELECT D.RAGIONESOCIALE + ' ' + D.INDIRIZZO + ' ' + D.LOCALITA FROM DESTINAZIONIDIVERSE D WHERE D.CODCONTO = Z.CODCLI AND D.CODICE = Z.CODDEST) AS RAGIONESOCIALEDESTDIV
, z.* FROM ZSI_NOTEART z 
JOIN ANAGRAFICACF a ON a.CODCONTO = z.CODCLI
JOIN ANAGRAFICAARTICOLI aa ON aa.CODICE = z.CODART 
WHERE CODART like '20247#000000%'