UPDATE E1
SET E1.MACRO_ART = replace(e2.macro_art, 'XXX', '000XXX')
FROM ZS_GENERAARTICOLI_POST z JOIN extramag e1 ON e1.CODART = z.NUOVOCODART
JOIN extramag e2 ON e2.CODART = z.CODART
WHERE e2.MACRO_ART <> ''
AND e1.MACRO_ART <> replace(e2.macro_art, 'XXX', '000XXX')
AND LEFT(E1.CODART, 1) IN ('2')


SELECT DISTINCT e1.CODART, e1.MACRO_ART, e2.CODART, e2.MACRO_ART, replace(e2.macro_art, 'XXX', '000XXX')
FROM ZS_GENERAARTICOLI_POST z JOIN extramag e1 ON e1.CODART = z.NUOVOCODART
JOIN extramag e2 ON e2.CODART = z.CODART
WHERE e2.MACRO_ART <> ''
AND e1.MACRO_ART <> replace(e2.macro_art, 'XXX', '000XXX')
AND LEFT(E1.CODART, 1) IN ('2')
AND replace(e2.macro_art, 'XXX', '000XXX') IN (SELECT ITA_TAB_DEFPROV.MACROARTICOLO FROM ITA_TAB_DEFPROV)



SELECT DISTINCT e1.CODART, e1.MACRO_ART, e2.CODART, e2.MACRO_ART, e2.macro_art + '#000000XXX'
--UPDATE E1 SET E1.MACRO_ART = e2.macro_art + '#000000XXX'
FROM ZS_GENERAARTICOLI_POST z JOIN extramag e1 ON e1.CODART = z.NUOVOCODART
JOIN extramag e2 ON e2.CODART = z.CODART
WHERE e2.MACRO_ART <> ''
AND e1.MACRO_ART <> e2.macro_art + '#000000XXX'
AND LEFT(E1.CODART, 1) IN ('3', '4')
AND e2.macro_art + '#000000XXX' IN (SELECT ITA_TAB_DEFPROV.MACROARTICOLO FROM ITA_TAB_DEFPROV)



SELECT CODART, MACRO_ART FROM EXTRAMAG WHERE LEFT(MACRO_ART, 1) <> LEFT(CODART, 1) AND MACRO_ART <> ''
AND LEFT(CODART, 1) IN ('2', '3', '4')
AND (LEN(CODART) = 5 OR LEN(CODART) > 12)


IF OBJECT_ID ('dbo.ZS_IMPORT_INV00') IS NOT NULL
	DROP TABLE dbo.ZS_IMPORT_INV00
GO

CREATE TABLE dbo.ZS_IMPORT_INV00
	(
	CODICE            VARCHAR (50) NOT NULL
	)
GO


INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30014')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30020')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30021')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30038')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30047')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30053')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30067')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30193')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30235')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30236')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30246')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30247')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30258')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30266')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30275')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30300')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30301')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30355')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30365')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30367')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30385')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30386')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30389')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30395')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30420')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30493')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30494')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30497')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30498')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30500')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30501')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30503')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30505')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30507')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30508')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30509')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30510')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30512')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30513')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30514')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30520')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30522')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30547')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30550')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30552')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30553')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('30554')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('31002')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('31003')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('31004')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('31005')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('31007')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('31008')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('31011')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('31012')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('31106')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('31108')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('31109')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32005')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32010')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32012')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32020')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32035')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32125')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32250')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32259')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32260')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32262')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32263')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32266')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32268')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32307')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32309')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32310')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32314')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32331')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32332')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32336')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32410')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32418')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32421')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32422')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32435')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32436')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32439')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32442')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32445')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32451')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32462')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32463')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32466')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32467')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32468')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32504')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32506')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32560')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32561')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32562')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32650')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32662')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32668')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32669')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32670')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32675')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32678')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32680')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('32685')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('35102')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('35104')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('35355')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43000')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43001')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43003')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43004')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43006')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43007')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43009')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43013')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43017')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43018')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43019')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43021')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43022')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43024')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43029')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43035')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43041')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43047')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43048')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43049')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43052')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43053')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43056')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43058')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43065')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43067')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43069')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43070')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43072')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43073')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43074')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43075')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43076')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43077')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43078')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43079')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43082')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43083')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43084')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43085')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43086')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43088')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43090')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43091')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43092')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43094')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43100')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43105')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43121')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43122')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43125')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43126')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43127')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43130')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43131')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43135')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43141')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43142')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43144')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43147')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43149')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43151')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43158')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43160')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43165')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43167')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43168')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43169')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43170')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43171')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43172')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43175')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43178')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43180')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43185')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43192')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43193')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43194')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43201')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43207')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43218')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43220')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43223')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43225')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43230')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43240')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43242')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43255')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43260')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43372')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43381')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43390')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43395')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43397')
INSERT INTO ZS_IMPORT_INV00 (CODICE) VALUES ('43411')


SELECT * FROM ANAGRAFICAARTICOLI WHERE ARTTIPOLOGIA = 1 AND CODICE IN (SELECT CODICE FROM ZS_IMPORT_INV00)
AND NOT EXISTS(SELECT 1 FROM ANAGRAFICAARTICOLI X WHERE ANAGRAFICAARTICOLI.CODICE =  X.CODICE + '#000000XXX')
AND LEFT(ANAGRAFICAARTICOLI.CODICE, 2) >= '32'

SELECT * FROM ANAGRAFICAARTICOLI WHERE ARTTIPOLOGIA = 0 AND EXISTS (SELECT CODICE FROM ZS_IMPORT_INV00 WHERE LEFT(ANAGRAFICAARTICOLI.CODICE, 5) = CODICE)
AND LEFT(ANAGRAFICAARTICOLI.CODICE, 2) >= '32'



IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI
GO

CREATE VIEW ZS_VISTA_GENERAARTICOLI
AS
SELECT * FROM (
SELECT X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART
	, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WITH (NOLOCK) WHERE A.CODICE = X.CODART OR A.CODICE = X.ARTTIPOLOGIA) AS DESCRIZIONE --, '' AS TIPO
	, (SELECT 'B' FROM ZS_VISTA_GENERAARTICOLI_MOV Z WHERE Z.CODART = X.CODART AND LEFT(Z.CODART, 1) <> '2' GROUP BY Z.CODART HAVING COUNT(Z.CODART) = 1 ) AS TIPO
	, (CASE WHEN X.CODICE <> 'XXX' THEN 0 ELSE 9999 END) AS ORDINAMENTO

FROM 
	 ZS_VISTA_GENERAARTICOLI_MOV x -- ON  x.ARTTIPOLOGIA = cte.arttipologia AND x.CODIMBALLO = cte.cod_imballo
WHERE
	NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.CODART = X.CODART AND XX.NUOVOCODART = X.NUOVOCODART)
UNION
SELECT 
	X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART, X.DESCRIZIONE, X.TIPO 
	, (CASE WHEN X.CODICE <> 'XXX' THEN 0 ELSE 9999 END) AS ORDINAMENTO
FROM 
	ZS_VISTA_GENERAARTICOLI_MODELLI X
WHERE 
	NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.CODART = X.CODART AND XX.NUOVOCODART = X.NUOVOCODART)

UNION

SELECT LEFT(A.CODICE, 5) AS ARTTIPOLOGIA
	, a.CODICE AS CODART
	, 'XXX' AS CODICE
	, '' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO
	, '' AS DESCRVARIANTE
	, A.CODICE + '#000000XXX' AS NUOVOCODART
	, ''
	, 'X' AS TIPO
	, 999	
	--, * 
FROM ANAGRAFICAARTICOLI A
WHERE 
	ARTTIPOLOGIA = 1 AND CODICE IN (SELECT CODICE FROM ZS_IMPORT_INV00)
	AND NOT EXISTS(SELECT 1 FROM ANAGRAFICAARTICOLI X WHERE A.CODICE =  X.CODICE + '#000000XXX')
	AND LEFT(A.CODICE, 2) >= '32'

UNION 





SELECT DISTINCT  LEFT(A.CODICE, 5) AS ARTTIPOLOGIA
	, a.CODICE AS CODART
	, 'XXX' AS CODICE
	, '' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO
	, '' AS DESCRVARIANTE
	, A.CODICE + '#000000XXX' AS NUOVOCODART
	, ''
	, 'X' AS TIPO
	, 999	
	--, * 
FROM ANAGRAFICAARTICOLI A
WHERE 
	ARTTIPOLOGIA = 1 --AND CODICE NOT IN (SELECT CODICE FROM ZS_IMPORT_INV00)
	AND LEFT(A.CODICE, 2) >= '32' and A.CODICE <> '62'
	AND (EXISTS(SELECT TOP 1 1 FROM STORICOMAG XX  WHERE XX.CODART = A.CODICE)
	OR NOT EXISTS(SELECT 1 FROM ANAGRAFICAARTICOLI X WHERE x.CODICE =  a.CODICE + '#000000XXX'))

	
	
UNION

SELECT LEFT(A.CODICE, 5) AS ARTTIPOLOGIA
	, a.CODICE AS CODART
	, I.CODICE
	, I.DESCRIZIONE AS DESCRIMBALLO
	, I.VARIANTEIMBALLO
	, V.DESCRIZIONE AS DESCRVARIANTE
	, REPLACE(A.CODICE, 'XXX', V.VARIANTE) AS NUOVOCODART
	, A.DESCRIZIONE + ' ' + V.DESCRIZIONE
	, 'X' AS TIPO
	, 999	
	--, * 
FROM ANAGRAFICAARTICOLI a, TABIMBALLI I, TABVARIANTI V 
WHERE 
	ARTTIPOLOGIA = 0 AND LEN(A.CODICE) > 12 AND patindex('%K#%', a.codice) = 0 
	AND (LEFT(a.CODICE, 2) = '21' OR LEFT(a.CODICE, 5) = '25102' OR LEFT(a.CODICE, 5) = '25104' OR LEFT(a.CODICE, 5) = '20067')
	AND RIGHT(a.CODICE, 3) = 'XXX' 
	AND V.VARIANTE = I.VARIANTEIMBALLO AND V.TIPOLOGIA = '62'
	AND I.VARIANTEIMBALLO = '396'
	

UNION

SELECT LEFT(A.CODICE, 5) AS ARTTIPOLOGIA
	, a.CODICE AS CODART
	, I.CODICE
	, I.DESCRIZIONE AS DESCRIMBALLO
	, I.VARIANTEIMBALLO
	, V.DESCRIZIONE AS DESCRVARIANTE
	, REPLACE(A.CODICE, 'XXX', V.VARIANTE) AS NUOVOCODART
	, A.DESCRIZIONE + ' ' + V.DESCRIZIONE
	, 'X' AS TIPO
	, 999	
	--, * 
FROM ANAGRAFICAARTICOLI a, TABIMBALLI I, TABVARIANTI V 
WHERE 
	ARTTIPOLOGIA = 0 AND LEN(A.CODICE) > 12 AND patindex('%K#%', a.codice) = 0 
	AND (LEFT(a.CODICE, 2) <> '21' OR LEFT(a.CODICE, 1) IN ('2', '3', '4'))
	AND RIGHT(a.CODICE, 3) = 'XXX' 
	AND V.VARIANTE = I.VARIANTEIMBALLO AND V.TIPOLOGIA = '62'
	AND I.VARIANTEIMBALLO IN ('394', '392', '390')
	AND A.CODICE IN (SELECT DISTINCT RD.CODART FROM RIGHEDOCUMENTI RD WHERE RD.TIPODOC IN ('OCC', 'OCE', 'OCG') AND ESERCIZIO >= 2016)
	
) CTE
--WHERE NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.NUOVOCODART = CTE.NUOVOCODART)
GO

GRANT DELETE ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT INSERT ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT REFERENCES ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT SELECT ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT UPDATE ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO




IF OBJECT_ID ('dbo.ITA_UPDATECODICISOST') IS NOT NULL
	DROP PROCEDURE dbo.ITA_UPDATECODICISOST
GO

CREATE PROCEDURE ITA_UPDATECODICISOST  (@OLDCODART VARCHAR(50), @CODIMBALLO VARCHAR(10), @NEWCODART VARCHAR(50) ) AS
	DECLARE @CSQL_S AS VARCHAR(5000)
	DECLARE @CSQL_U AS VARCHAR(5000)
	DECLARE @CSQL_U0 AS VARCHAR(5000)
	DECLARE @CSQL_U1 AS VARCHAR(5000)
	DECLARE @CSQL_U2 AS VARCHAR(5000)
	DECLARE @TABELLA AS VARCHAR(500)
	
	PRINT @OLDCODART
	PRINT @CODIMBALLO
	PRINT @NEWCODART

	SET @CSQL_U0 = 'UPDATE R SET R.CODART = ''' + @NEWCODART + ''' ' +
	' FROM RIGHEDOCUMENTI R ' +  
	' WHERE R.TIPODOC IN (''OCC'', ''OCE'', ''OCG'') AND R.CODART = ''' + @OLDCODART + ''' AND ((R.RIGACHIUSA = 1 AND R.QTAGESTRES = 0) OR (R.CODIMBALLO  NOT IN (SELECT X.CODICE FROM ZS_GENERAARTICOLI_POST X WHERE X.CODART =  ''' + @OLDCODART + ''')))'
	
	SET @CSQL_U1 = 'UPDATE S SET S.CODART = ''' + @NEWCODART + '''  ' +
	' FROM RIGHEDOCUMENTI R JOIN STORICOMAG S ON S.IDTESTA = R.IDTESTA AND S.RIGADOC = R.IDRIGA' +  
	' WHERE R.TIPODOC IN (''OCC'', ''OCE'', ''OCG'') AND R.CODART = ''' + @OLDCODART + ''' AND ((R.RIGACHIUSA = 1 AND R.QTAGESTRES = 0) OR (R.CODIMBALLO  NOT IN (SELECT X.CODICE FROM ZS_GENERAARTICOLI_POST X WHERE X.CODART =  ''' + @OLDCODART + ''')))'

	
	SET @CSQL_U2 = 'UPDATE P SET P.CODARTICOLO = ''' + @NEWCODART + '''  ' + 
	' FROM RIGHEDOCUMENTI R JOIN STORICOMAG S ON S.IDTESTA = R.IDTESTA AND S.RIGADOC = R.IDRIGA ' +
	' JOIN STORICOPREZZIARTICOLO P ON P.RIFSTORICOMAG = S.PROGRESSIVO' +
	' WHERE R.TIPODOC IN (''OCC'', ''OCE'', ''OCG'') AND R.CODART = ''' + @OLDCODART + ''' AND ((R.RIGACHIUSA = 1 AND R.QTAGESTRES = 0) OR (R.CODIMBALLO  NOT IN (SELECT X.CODICE FROM ZS_GENERAARTICOLI_POST X WHERE X.CODART =  ''' + @OLDCODART + ''')))'
	

	IF LEFT(@oldcodart, 1) IN ('3', '4') AND 
		(
			SELECT count(*) FROM ANAGRAFICAARTICOLI X WHERE X.CODICE = @NEWCODART -- AND TIPO IN ('A', 'B')
		) = 1
	BEGIN
	
		PRINT 'SERIE 30000, 40000aaaaa'
	
		DECLARE rSqlA CURSOR LOCAL KEYSET FOR 
	
		SELECT TABELLA
		, 'SELECT ' + '*' + ' FROM ' + TABELLA + ' WHERE '+ CAMPO + ' = ''' + @OLDCODART + ''''  AS STRSQL_S
		, 'UPDATE ' + TABELLA + ' SET ' + CAMPO + ' = ''' + @NEWCODART + ''' WHERE '+ CAMPO + ' = ''' + @OLDCODART + '''' AS STRSQL
		--, * 
		--, 'UPDATE ITA_CODICISOST SET SEL = 0 WHERE TABELLA = ''' + TABELLA + ''' AND (SELECT COUNT(*) FROM ' + TABELLA + ' WHERE ' + CAMPO + ' IN (SELECT Z.CODART FROM ZS_GENERAARTICOLI z)) = 0' AS STRSQL
		FROM ITA_CODICISOST i 
		WHERE i.SEL = 1
		
	
	--	ORDER BY C.COLUMN_NAME
		OPEN rSqlA
	
		FETCH NEXT from rSqlA INTO @TABELLA,  @CSQL_S, @CSQL_U
		WHILE (@@FETCH_STATUS <> -1)
			BEGIN
				
				--PRINT @TABELLA
				IF @TABELLA = 'DESCRARTICOLI'
				BEGIN
					PRINT 'NON PROCESSATA - ' + @TABELLA + @CSQL_U
					SET @CSQL_U = ''
				END
				
				
				IF @TABELLA = 'TABLOTTIRIORDINO'
				BEGIN
					DELETE FROM TABLOTTIRIORDINO WHERE CODART = @NEWCODART AND EXISTS(SELECT TOP 1 1 FROM TABLOTTIRIORDINO X WHERE X.CODART = @OLDCODART)
				END
				
				PRINT @CSQL_U
				IF (@CSQL_U <> '')
				BEGIN
					EXEC (@CSQL_U)
				END	
	
				
	
			
				--PRINT @@ROWCOUNT
		
				FETCH NEXT from rSqlA INTO @TABELLA, @CSQL_S, @CSQL_U
			END
	
		CLOSE rSqlA
		DEALLOCATE rSqlA
			
	END



	IF LEFT(@oldcodart, 1) = '2'
	BEGIN
	

		DECLARE rSqlA CURSOR LOCAL KEYSET FOR 
	
		SELECT TABELLA
		, 'SELECT ' + '*' + ' FROM ' + TABELLA + ' WHERE '+ CAMPO + ' = ''' + @OLDCODART + ''''  AS STRSQL_S
		, (CASE 
			--WHEN TABELLA = 'GESTIONEPREZZI' THEN
			--	'UPDATE ' + TABELLA + ' SET CODART = ''' + @OLDCODART + '#??????'', CODARTRIC = ''' + @OLDCODART + '#___%'' WHERE INIZIOVALIDITA = FINEVALIDITA AND '+ CAMPO + ' = ''' + @OLDCODART + ''''
			WHEN TABELLA = 'RELAZIONICFV' AND CAMPO = 'VARIANTI' THEN
				'UPDATE ' + TABELLA + ' SET VARIANTI = ''' + SUBSTRING(@NEWCODART, CHARINDEX('#', @NEWCODART) + 1, LEN(@NEWCODART) - CHARINDEX('#', @NEWCODART)) + ''' WHERE ARTICOLO  + ''#'' + ' + CAMPO + ' = ''' + @OLDCODART + ''''
			ELSE
				'UPDATE ' + TABELLA + ' SET ' + CAMPO + ' = ''' + @NEWCODART + ''' WHERE '+ CAMPO + ' = ''' + @OLDCODART + ''''
			END)  
			AS STRSQL
		--, * 
		--, 'UPDATE ITA_CODICISOST SET SEL = 0 WHERE TABELLA = ''' + TABELLA + ''' AND (SELECT COUNT(*) FROM ' + TABELLA + ' WHERE ' + CAMPO + ' IN (SELECT Z.CODART FROM ZS_GENERAARTICOLI z)) = 0' AS STRSQL
		FROM ITA_CODICISOST i 
		WHERE I.SEL = 1
	
	--	ORDER BY C.COLUMN_NAME
		OPEN rSqlA
	
		FETCH NEXT from rSqlA INTO @TABELLA,  @CSQL_S, @CSQL_U
		WHILE (@@FETCH_STATUS <> -1)
			BEGIN
				
				--PRINT @TABELLA
				
				/*
				IF @TABELLA = 'RIGHEDOCUMENTI'
				BEGIN
	
	
	
					PRINT @CSQL_U2
					EXEC (@CSQL_U2)
		
					PRINT @CSQL_U1

					EXEC (@CSQL_U1)
					
					PRINT @CSQL_U0
					EXEC (@CSQL_U0)					
					
				END
				*/
				
				--PRINT @CSQL_U
				EXEC (@CSQL_U)
	
	
				
	
				
				--PRINT @@ROWCOUNT
		
				FETCH NEXT from rSqlA INTO @TABELLA, @CSQL_S, @CSQL_U
			END
	
		CLOSE rSqlA
		DEALLOCATE rSqlA
		
		RETURN
		
	END
GO

GRANT EXECUTE ON dbo.ITA_UPDATECODICISOST TO Metodo98
GO





IF OBJECT_ID ('dbo.ZS_GENERAARTICOLO_POST') IS NOT NULL
	DROP PROCEDURE dbo.ZS_GENERAARTICOLO_POST
GO

create PROCEDURE ZS_GENERAARTICOLO_POST(@CODART VARCHAR(50), @OLDCODART VARCHAR(50), @CODIMBALLO VARCHAR(50), @REDO SMALLINT = 0) AS
BEGIN
 
	DECLARE @ARTPADRE VARCHAR(50)
	DECLARE @ARTMODELLO VARCHAR(50)
	
	SET @ARTPADRE = LEFT(@CODART, CHARINDEX('#' , @CODART) -1)
	SET @ARTMODELLO = @OLDCODART --LEFT(@CODART, LEN(@CODART) -3) + 'XXX'
	

	

	
	IF (NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST WHERE CODART = @OLDCODART AND NUOVOCODART = @CODART AND CODICE = @CODIMBALLO ) OR @REDO = 1)
	BEGIN
	
		PRINT @ARTPADRE
		PRINT @ARTMODELLO
		PRINT @CODIMBALLO
		
	   		
		INSERT INTO dbo.ZS_GENERAARTICOLI_POST (CODART, NUOVOCODART, UtenteModifica, DataModifica, CODICE)
		SELECT @OLDCODART, @CODART, 'TRM', GETDATE(), @CODIMBALLO
		FROM TABDITTE
		WHERE NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST X 
		WHERE -- X.CODART = @OLDCODART AND 
		X.NUOVOCODART = @CODART AND X.CODICE = @CODIMBALLO)
		
		--EXEC ZS_GENERAARTICOLI_GESTIONEPREZZI @CODART, @OLDCODART
		
		
		
		DECLARE @NRPEZZIIMBALLO INT
		

		SELECT @NRPEZZIIMBALLO = G1.QTA_COLLI 
		FROM ITA_VIS_PRZPART_IMBLIST  G1
		WHERE G1.PRIORITA > 1 AND
			(G1.CODART = @CODART OR
			G1.CODART = LEFT(@CODART, LEN(@CODART) -3) + '???' OR
			G1.CODART LIKE @ARTPADRE + '%') --'#??????')
		AND G1.COD_IMBALLO = @CODIMBALLO

		PRINT '-- DATI ANAGRAFICASTANDARD'
 		UPDATE a1
		SET 
			a1.DESCRIZIONE = RTRIM(LEFT(a2.descrizione + ' ' + (SELECT TOP 1 TABVARIANTI.DESCRIZIONE FROM TABVARIANTI WHERE TABVARIANTI.VARIANTE = RIGHT(a1.CODICE, 3) AND TIPOLOGIA = '62'), 80))
			, a1.GRUPPO = a2.GRUPPO
			, a1.CATEGORIA = a2.CATEGORIA
			, a1.CODCATEGORIASTAT = a2.CODCATEGORIASTAT
			, a1.PESONETTO = a2.PESONETTO
			, a1.SUPERFICIE = a2.SUPERFICIE
			, a1.CUBATURA = a2.CUBATURA
			, a1.NOMENCLCOMBINATA1 = a2.NOMENCLCOMBINATA1
			, a1.NOMENCLCOMBINATA2 = a2.NOMENCLCOMBINATA2
			, a1.ORIGINEINTRA = a2.ORIGINEINTRA 
			, a1.CODICEARTIMBALLO = a1.CODICEARTIMBALLO
			, a1.NRPEZZIIMBALLO = @NRPEZZIIMBALLO --a2.NRPEZZIIMBALLO
			, a1.RIFERIMIMBALLO = @CODIMBALLO --(SELECT TOP 1 tabimballi.CODICE FROM TABIMBALLI WHERE tabimballi.VARIANTEIMBALLO = RIGHT(a1.CODICE, 3))
			, a1.AGGIORNAMAG = a2.AGGIORNAMAG
			, a1.MOVIMENTAPARTITE = a2.MOVIMENTAPARTITE
			, a1.MOVIMENTAMATRICOLE = a2.MOVIMENTAMATRICOLE
			, a1.CODDEPOSITO = a2.CODDEPOSITO
			, a1.NRTIPRAGGRUPPATE = a2.NRTIPRAGGRUPPATE
			, a1.ARTCONFIGURATO = a2.ARTCONFIGURATO
		--SELECT rtrim(a2.descrizione + substring(a1.descrizione, (SELECT len(a3.DESCRIZIONE) FROM ANAGRAFICAARTICOLI a3 WHERE ARTTIPOLOGIA = 1 AND CODICE = a1.CODICEPRIMARIO)+1, 80)), *
		FROM ANAGRAFICAARTICOLI a1, ANAGRAFICAARTICOLI a2
		WHERE 
			a1.CODICE = @CODART
			AND a2.CODICE = @ARTMODELLO
			AND LEFT(a1.CODICE , 1) = '2'
			
			
		
				
		UPDATE a1
		SET 
			a1.CODIVA = a2.CODIVA
			, SCONTO1 = a2.SCONTO1
			, a1.SCONTO2 = a2.SCONTO2
			, a1.SCONTO3 = a2.SCONTO3
			, a1.GRUPPOPRZPART = a2.GRUPPOPRZPART
			, a1.GRUPPOPRVPART = a2.GRUPPOPRVPART
			, a1.PROVV = a2.PROVV
			, a1.CODICEALT1 = a2.CODICEALT1
			, a1.CODICEALT2 = a2.CODICEALT2
			, a1.SCGENVENDITEITA = a2.SCGENVENDITEITA
			, a1.SCGENVENDITEEST = a2.SCGENVENDITEEST
			, a1.SCGENACQUISTIITA = a2.SCGENACQUISTIITA
			, a1.SCGENACQUISTIEST = a2.SCGENACQUISTIEST
			, a1.INESAURIMENTO = a2.INESAURIMENTO
			, a1.ESAURITO = a2.ESAURITO
			, a1.QTAMINCONS = a2.QTAMINCONS
			, a1.USAPREZZIPART = a2.USAPREZZIPART
			, a1.FlagCauzioni = a2.FlagCauzioni
			, a1.FLGBARCODEGENDAPROCAUTOMSTD = a2.FLGBARCODEGENDAPROCAUTOMSTD
			, a1.EXPORTECOMMERCE = a2.EXPORTECOMMERCE
			, a1.CODIVAINTRA = a2.CODIVAINTRA
		--SELECT *
		FROM ANAGRAFICAARTICOLIcomm a1, ANAGRAFICAARTICOLIcomm a2
		WHERE 
			a1.CODICEART = @CODART
			AND a2.CODICEART = @ARTMODELLO
			AND LEFT(a1.CODICEART , 1) = '2'
			AND a1.ESERCIZIO = a2.esercizio
			AND LEFT(a1.CODICEART , 1) = '2'
		
		
		UPDATE a1
		SET a1.SCORTAMIN = a2.scortamin
			, a1.SCORTAMAX = a2.SCORTAMAX
			, a1.LIVPRODUZIONE = a2.LIVPRODUZIONE
			, a1.RAGGRPRODUZIONE =  a1.RAGGRPRODUZIONE
			, a1.LIVPRODPREC = a2.LIVPRODPREC
			, a1.TIPOGESTIONE = a2.TIPOGESTIONE
			, a1.LIVRIORDINO = a2.LIVRIORDINO
			, a1.PROVENIENZA = A2.PROVENIENZA
			, a1.ARTALTERNATIVO =a1.ARTALTERNATIVO
			, a1.QMINRIORDACQ = a2.QMINRIORDACQ
			, a1.QMAXRIORDACQ = a2.QMAXRIORDACQ
			, a1.QDELTARIORDACQ = a2.QDELTARIORDACQ
			, a1.TAPPRONTACQ = a2.TAPPRONTACQ
			, a1.TAPPROVVACQ = a2.TAPPROVVACQ
			, a1.LOTTORIFACQ = a2.LOTTORIFACQ
			, a1.ARROTLOTTOACQ = a2.ARROTLOTTOACQ
			, a1.FORNPREFACQ = a2.FORNPREFACQ
			, a1.QMINRIORDPROD = a2.QMINRIORDPROD
			, a1.QMAXRIORDPROD = a2.QMAXRIORDPROD
			, a1.QDELTARIORDPROD = a2.QDELTARIORDPROD
			, a1.TAPPRONTPROD = a2.TAPPRONTPROD 
			, a1.TAPPROVVPROD = a2.TAPPROVVPROD
			, a1.LOTTORIFPROD = a2.LOTTORIFPROD
			, a1.ARROTLOTTOPROD = a2.ARROTLOTTOPROD
			, a1.QMINRIORDLAV = a2.QMINRIORDLAV
			, a1.QMAXRIORDLAV = a2.QMAXRIORDLAV
			, a1.QDELTARIORDLAV = a2.QDELTARIORDLAV
			, a1.TAPPRONTLAV = a2.TAPPRONTLAV
			, a1.TAPPROVVLAV = a2.TAPPROVVLAV
			, a1.LOTTORIFLAV = a2.LOTTORIFLAV
			, a1.ARROTLOTTOLAV = a2.ARROTLOTTOLAV 
			, a1.FORNPREFLAV = a2.FORNPREFLAV
			, a1.LOTTORIORDINO = a2.LOTTORIORDINO
			, a1.TIPOPRODUZIONE = a2.TIPOPRODUZIONE
			, a1.FLOORSTOCK = a2.FLOORSTOCK
			, a1.GRUPPOAPPROV = a2.GRUPPOAPPROV
			, a1.COSTOORDINEACQ = a2.COSTOORDINEACQ
			, a1.COSTOORDINELAV = a2.COSTOORDINELAV
			, a1.COSTOORDINEPROD = a2.COSTOORDINEPROD
			, a1.FATTORESCOSTAMENTO = a2.FATTORESCOSTAMENTO
			, a1.TEMPOCOPERTURA = a2.TEMPOCOPERTURA
			, a1.CONSUMOPREVISTO = a2.CONSUMOPREVISTO
			, a1.MADPREVISTO = a2.MADPREVISTO
			, a1.FATTORESICUREZZA = a2.TIPOPRODOTTO
			, a1.TIPOPRODOTTO = a2.TIPOPRODOTTO
			, a1.GESTIONEMATERIALI = a2.GESTIONEMATERIALI
			, a1.FATTORECOMPRESSIONE = a2.FATTORECOMPRESSIONE
			, a1.GRUPPOPREVISIONE = a2.GRUPPOPREVISIONE
			, a1.FORMULAFRONTIERA = a2.FORMULAFRONTIERA
			, a1.LIVELLOSERVIZIO = a2.LIVELLOSERVIZIO
			, a1.FLAGMPS = a2.FLAGMPS
			, a1.FLAGNETTIFICAMPS = a2.FLAGNETTIFICAMPS
			, a1.CODICEMPS = a2.CODICEMPS
			, a1.LOTTOFABBRICAZIONE = a2.LOTTOFABBRICAZIONE
			, a1.UMLOTTOFABBRICAZIONE = a2.UMLOTTOFABBRICAZIONE
			, a1.KS_GGScadenza = a2.KS_GGScadenza
			, a1.INTERVALLOPIANIF = a2.INTERVALLOPIANIF
			, a1.DATAULTANALISI = a2.DATAULTANALISI
			, a1.GGORIZZONTEDISP = a2.GGORIZZONTEDISP
		--SELECT *
		FROM ANAGRAFICAARTICOLIPROD a1, ANAGRAFICAARTICOLIPROD a2
		WHERE 
			a1.CODICEART = @CODART
			AND a2.CODICEART = @ARTMODELLO
			AND LEFT(a1.CODICEART , 1) = '2'
			AND a1.ESERCIZIO = a2.esercizio
			AND LEFT(a1.CODICEART , 1) = '2'

		
		
		
		UPDATE a1
		SET A1.ScontiPremi = A2.ScontiPremi 
			, A1.SpTrasp = a2.SpTrasp
			, a1.Provvi = a2.Provvi
			, a1.Imballi = a2.Imballi
			, a1.Amministrazione = a2.Amministrazione
			, a1.SpVendita = a2.SpVendita
			, a1.SpMagazzino = a2.SpMagazzino
			, a1.SpeseProd = a2.SpeseProd
			, a1.CostoAggiunto = a2.CostoAggiunto
			, a1.Preleva = a2.Preleva
			, a1.TestMateriePrime = a2.TestMateriePrime
			, a1.TOL = a2.TOL
			, a1.FLAG_BOLLETTINO = a2.FLAG_BOLLETTINO
			, a1.SCOSTAMENTO_PRZ = a2.SCOSTAMENTO_PRZ
			, a1.XLS_CHEMDES = a2.XLS_CHEMDES
			, a1.XLS_CASNR = a2.XLS_CASNR
			, a1.XLS_ORGGOODS = a2.XLS_ORGGOODS
			, a1.XLS_ORGFORMULA = a2.XLS_ORGFORMULA
			, a1.XLS_VARORGFORMULA = a2.XLS_VARORGFORMULA 
			, a1.XLS_OPDIVISION = a2.XLS_OPDIVISION
			, a1.XLS_COSTDIRWAGES = a2.XLS_COSTDIRWAGES
			, a1.XLS_COSTPRODOVERHEAD = a2.XLS_COSTPRODOVERHEAD
			, a1.XLS_COSTRAWMAT = a2.XLS_COSTRAWMAT
			, a1.XLS_COSTRAWMAT_VEN = a2.XLS_COSTRAWMAT_VEN
			, a1.FLAG_ADR = a2.FLAG_ADR
			, a1.PATH_SCHEDASICUREZZA_ITA = a2.PATH_SCHEDASICUREZZA_ITA
			, a1.PATH_SCHEDASICUREZZA_EST = a2.PATH_SCHEDASICUREZZA_EST
			, a1.MACRO_ART = a2.MACRO_ART
			, a1.PRV_VAR = a2.PRV_VAR
			, a1.BSCKNOS = a2.BSCKNOS
			, a1.FLAG_RSPO = a2.FLAG_RSPO
			, a1.NRPEZZIIMBALLO = @NRPEZZIIMBALLO
		--SELECT *
		FROM EXTRAMAG a1, EXTRAMAG a2
		WHERE 
			a1.CODART = @CODART
			AND a2.CODART = @ARTMODELLO
			AND LEFT(a1.CODART , 1) = '2'
		
		-- LISTINI
		DELETE A1 
		FROM LISTINIARTICOLI A1 
		WHERE a1.CODART = @CODART 
			AND LEFT(@CODART , 1) = '2'
			
		
		-- articoli originali con imballo qualificato
		IF (LEFT(@CODART , 1) = '2' AND RIGHT(@OLDCODART, 3) <> 'XXX')
		BEGIN
			PRINT '- listini ' + @codart + ' - ' + @ARTMODELLO
			INSERT INTO dbo.LISTINIARTICOLI (CODART, NRLISTINO, UM, PREZZO, PREZZOEURO, UTENTEMODIFICA, DATAMODIFICA, DeltaIncremento, TP_CodConto, TP_ConsPP, TP_PrezzoPart, TP_PrezzoPartEuro, TP_Scorporo, TP_Sconti, TP_QTASCONTO, TP_QTACOEFF, TP_QTAMO, TP_Abbuono, TP_DataCambio, TP_ValoreCambio, DATAVALIDITA, TP_FormulaSct, PREZZOCALC, TP_ABBUONOEURO)
			SELECT @CODART, T.NRLISTINO, UM, PREZZO, PREZZOEURO, 'TRM', GETDATE(), DeltaIncremento, TP_CodConto, TP_ConsPP, TP_PrezzoPart, TP_PrezzoPartEuro, TP_Scorporo, TP_Sconti, TP_QTASCONTO, TP_QTACOEFF, TP_QTAMO, TP_Abbuono, TP_DataCambio, TP_ValoreCambio, DATAVALIDITA, TP_FormulaSct, PREZZOCALC, TP_ABBUONOEURO
			FROM LISTINIARTICOLI t 
			WHERE T.CODART = @OLDCODART
				AND LEFT(@CODART , 1) = '2'
				AND NOT EXISTS (SELECT 1 FROM LISTINIARTICOLI x WHERE @CODART = X.CODART AND x.NRLISTINO = T.NRLISTINO)
		END
		ELSE
		BEGIN		
			PRINT '- listini ' + @codart + ' - ' + @ARTMODELLO
			INSERT INTO dbo.LISTINIARTICOLI (CODART, NRLISTINO, UM, PREZZO, PREZZOEURO, UTENTEMODIFICA, DATAMODIFICA, DeltaIncremento, TP_CodConto, TP_ConsPP, TP_PrezzoPart, TP_PrezzoPartEuro, TP_Scorporo, TP_Sconti, TP_QTASCONTO, TP_QTACOEFF, TP_QTAMO, TP_Abbuono, TP_DataCambio, TP_ValoreCambio, DATAVALIDITA, TP_FormulaSct, PREZZOCALC, TP_ABBUONOEURO)
			SELECT @CODART, T.NRLISTINO, UM, PREZZO, PREZZOEURO, 'TRM', GETDATE(), DeltaIncremento, TP_CodConto, TP_ConsPP, TP_PrezzoPart, TP_PrezzoPartEuro, TP_Scorporo, TP_Sconti, TP_QTASCONTO, TP_QTACOEFF, TP_QTAMO, TP_Abbuono, TP_DataCambio, TP_ValoreCambio, DATAVALIDITA, TP_FormulaSct, PREZZOCALC, TP_ABBUONOEURO
			FROM LISTINIARTICOLI t 
			WHERE T.CODART = @ARTMODELLO
				AND LEFT(@CODART , 1) = '2'
				AND NOT EXISTS (SELECT 1 FROM LISTINIARTICOLI x WHERE @CODART = X.CODART AND x.NRLISTINO = T.NRLISTINO)
		END	
			
		
		DELETE A1 
		FROM CONTROPARTARTICOLI A1 
		WHERE a1.CODART = @CODART 
		
		INSERT INTO dbo.CONTROPARTARTICOLI (CODART, ESERCIZIO, NUMERO, SCGEN, UTENTEMODIFICA, DATAMODIFICA)
		SELECT @CODART, T.ESERCIZIO, T.NUMERO, T.SCGEN, 'TRM', GETDATE()
		FROM CONTROPARTARTICOLI t 
		WHERE T.CODART = @ARTMODELLO
			AND LEFT(@CODART , 1) = '2'



		IF LEFT(@CODART , 1) IN ('2', '3', '4') AND RIGHT(@CODART, 3) = 'XXX'
		BEGIN
			
			PRINT '-- AGGIORNO CODICI STANDARD ' + @CODART
		
			EXEC ITA_UPDATECODICISOST  @OLDCODART, @CODIMBALLO, @CODART    
			
			
			UPDATE a1
			SET 
				a1.NRPEZZIIMBALLO = @NRPEZZIIMBALLO --a2.NRPEZZIIMBALLO
				, a1.RIFERIMIMBALLO = LEFT(@CODIMBALLO, 3) --(SELECT TOP 1 tabimballi.CODICE FROM TABIMBALLI WHERE tabimballi.VARIANTEIMBALLO = RIGHT(a1.CODICE, 3))
			FROM ANAGRAFICAARTICOLI a1
			WHERE 
				a1.CODICE = @CODART
				AND LEFT(a1.CODICE , 1) IN ('2', '3', '4')	 
			
			UPDATE EXTRAMAG
			SET NRPEZZIIMBALLO = @NRPEZZIIMBALLO	
			WHERE CODART = @CODART
				
		END
						
		-- inserimento in tabella articoli adr
		INSERT INTO dbo.TAB_ARTICOLIADR (CODART, CLASSEADR, NUMORD, NUMONU, NUMPER, GI, UTENTEMODIFICA, DATAMODIFICA, DESIGN_TRASP, COD_GALLERIE, ESENZIONE_QTA)
		SELECT @CODART, CLASSEADR, NUMORD, NUMONU, NUMPER, GI, 'trm', getdate(), DESIGN_TRASP, COD_GALLERIE, ESENZIONE_QTA
		FROM TAB_ARTICOLIADR t 
		WHERE (t.CODART = @ARTMODELLO OR t.CODART = @OLDCODART)
		AND @CODART NOT IN (SELECT x.codart FROM TAB_ARTICOLIADR x)	  
		

		-- AGGIORNAMENTO STORICOMAG
		--SELECT S.CODART, S.RIFERIMENTI, t.DESCRIZIONE, a.DESCRIZIONE, r.IDTESTA, r.IDRIGA
		
		UPDATE s SET s.CODART = @CODART
		
		FROM RIGHEDOCUMENTI r JOIN STORICOMAG S ON S.IDTESTA = R.IDTESTA AND S.RIGADOC = R.IDRIGA
		JOIN tabimballi t ON t.CODICE = r.CODIMBALLO
		WHERE r.RIGACHIUSA = 0 AND r.QTAGESTRES > 0 AND r.TIPODOC IN ('OCG', 'OCC', 'OCE')
		AND r.CODART = @OLDCODART AND r.CODIMBALLO = @CODIMBALLO

		-- AGGIORNAMENTO RIGHEDOCUMENTI
		--SELECT r.CODART, r.CODIMBALLO, e.NUOVOCODART, t.DESCRIZIONE, a.DESCRIZIONE, r.IDTESTA, r.IDRIGA		
		
		UPDATE r
		SET r.CODART = @CODART
		FROM RIGHEDOCUMENTI r 
		JOIN tabimballi t ON t.CODICE = r.CODIMBALLO
		WHERE r.RIGACHIUSA = 0 AND r.QTAGESTRES > 0 AND r.TIPODOC IN ('OCG', 'OCC', 'OCE')
		AND r.CODART = @OLDCODART AND r.CODIMBALLO = @CODIMBALLO
		
		
		
		
	END
END
GO

GRANT EXECUTE ON dbo.ZS_GENERAARTICOLO_POST TO Metodo98
GO

/*
DECLARE @A AS VARCHAR(50)
SET @A = '43410'

DECLARE @B AS VARCHAR(50)
SET @B =  @A + '#000000XXX'

PRINT @a 
PRINT @B

SELECT * FROM zsi..STORICOMAG WHERE codart like @a + '%'

EXEC ZS_GENERAARTICOLO_POST @B, @A, 'XXX', 1
*/


UPDATE x
SET x.esaurito = aa.esaurito
FROM tst_zsi..anagraficaarticolicomm aa JOIN ZS_GENERAARTICOLI_POST z ON z.CODART = aa.codiceart
JOIN anagraficaarticolicomm x ON x.CODICEART = z.NUOVOCODART
WHERE  aa.ESAURITO = 1 AND aa.esercizio = x.ESERCIZIO






-- trigger per impedire geenrazione di articoli senza codice

IF OBJECT_ID ('dbo.TI_ANAGRAFICAARTICOLI') IS NOT NULL
	DROP TRIGGER dbo.TI_ANAGRAFICAARTICOLI
GO

/*  INSERT TRIGGER "TI_ANAGRAFICAARTICOLI" FOR TABLE "ANAGRAFICAARTICOLI"  */
CREATE TRIGGER TI_ANAGRAFICAARTICOLI ON ANAGRAFICAARTICOLI FOR INSERT AS
BEGIN
    DECLARE
       @MAXCARD  INT,
       @NUMROWS  INT,
       @NUMNULL  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)
    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN
    
    /*  PARENT "ANAGRAFICADEPOSITI" MUST EXIST WHEN INSERTING A CHILD IN "ANAGRAFICAARTICOLI"  */
    IF UPDATE(CODDEPOSITO)
    BEGIN
       IF (SELECT COUNT(*)
           FROM   ANAGRAFICADEPOSITI T1, INSERTED T2
           WHERE  T1.CODICE = T2.CODDEPOSITO) != @NUMROWS
          BEGIN
             SELECT @ERRNO  = 30002,
                    @ERRMSG = 'Parent does not exist in "ANAGRAFICADEPOSITI". Cannot create child in "ANAGRAFICAARTICOLI".'
             GOTO ERROR
          END
    END
    RETURN
/*  ERRORS HANDLING  */
ERROR:
    RAISERROR (@ERRMSG, 1, 1)
    ROLLBACK  TRANSACTION
END
GO

