/*
IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI
GO

CREATE VIEW ZS_VISTA_GENERAARTICOLI
AS
SELECT * FROM (
SELECT X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART
	, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WITH (NOLOCK) WHERE A.CODICE = X.CODART OR A.CODICE = X.ARTTIPOLOGIA) AS DESCRIZIONE --, '' AS TIPO
	, (SELECT 'B' FROM ZS_VISTA_GENERAARTICOLI_MOV Z WHERE Z.CODART = X.CODART AND LEFT(Z.CODART, 1) <> '2' GROUP BY Z.CODART HAVING COUNT(Z.CODART) = 1 ) AS TIPO
	, (CASE WHEN X.CODICE <> 'XXX' THEN 0 ELSE 9999 END) AS ORDINAMENTO

FROM 
	 ZS_VISTA_GENERAARTICOLI_MOV x -- ON  x.ARTTIPOLOGIA = cte.arttipologia AND x.CODIMBALLO = cte.cod_imballo
WHERE
	NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.CODART = X.CODART AND XX.NUOVOCODART = X.NUOVOCODART)
UNION
SELECT 
	X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART, X.DESCRIZIONE, X.TIPO 
	, (CASE WHEN X.CODICE <> 'XXX' THEN 0 ELSE 9999 END) AS ORDINAMENTO
FROM 
	ZS_VISTA_GENERAARTICOLI_MODELLI X
WHERE 
	NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.CODART = X.CODART AND XX.NUOVOCODART = X.NUOVOCODART)

UNION

SELECT LEFT(A.CODICE, 5) AS ARTTIPOLOGIA
	, a.CODICE AS CODART
	, 'XXX' AS CODICE
	, '' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO
	, '' AS DESCRVARIANTE
	, A.CODICE + '#000000XXX' AS NUOVOCODART
	, ''
	, 'X' AS TIPO
	, 999	
	--, * 
FROM ANAGRAFICAARTICOLI A
WHERE 
	ARTTIPOLOGIA = 1 AND CODICE IN (SELECT CODICE FROM ZS_IMPORT_INV00)
	AND NOT EXISTS(SELECT 1 FROM ANAGRAFICAARTICOLI X WHERE A.CODICE =  X.CODICE + '#000000XXX')
	AND LEFT(A.CODICE, 2) >= '32'

UNION 





SELECT DISTINCT  LEFT(A.CODICE, 5) AS ARTTIPOLOGIA
	, a.CODICE AS CODART
	, 'XXX' AS CODICE
	, '' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO
	, '' AS DESCRVARIANTE
	, A.CODICE + '#000000XXX' AS NUOVOCODART
	, ''
	, 'X' AS TIPO
	, 999	
	--, * 
FROM ANAGRAFICAARTICOLI A
WHERE 
	ARTTIPOLOGIA = 1 --AND CODICE NOT IN (SELECT CODICE FROM ZS_IMPORT_INV00)
	AND LEFT(A.CODICE, 2) >= '32' and A.CODICE <> '62'
	AND (EXISTS(SELECT TOP 1 1 FROM STORICOMAG XX  WHERE XX.CODART = A.CODICE)
	OR NOT EXISTS(SELECT 1 FROM ANAGRAFICAARTICOLI X WHERE x.CODICE =  a.CODICE + '#000000XXX'))

	
	
UNION

SELECT LEFT(A.CODICE, 5) AS ARTTIPOLOGIA
	, a.CODICE AS CODART
	, I.CODICE
	, I.DESCRIZIONE AS DESCRIMBALLO
	, I.VARIANTEIMBALLO
	, V.DESCRIZIONE AS DESCRVARIANTE
	, REPLACE(A.CODICE, 'XXX', V.VARIANTE) AS NUOVOCODART
	, A.DESCRIZIONE + ' ' + V.DESCRIZIONE
	, 'X' AS TIPO
	, 999	
	--, * 
FROM ANAGRAFICAARTICOLI a, TABIMBALLI I, TABVARIANTI V 
WHERE 
	ARTTIPOLOGIA = 0 AND LEN(A.CODICE) > 12 AND patindex('%K#%', a.codice) = 0 
	AND (LEFT(a.CODICE, 2) = '21' OR LEFT(a.CODICE, 5) = '25102' OR LEFT(a.CODICE, 5) = '25104' OR LEFT(a.CODICE, 5) = '20067')
	AND RIGHT(a.CODICE, 3) = 'XXX' 
	AND V.VARIANTE = I.VARIANTEIMBALLO AND V.TIPOLOGIA = '62'
	AND I.VARIANTEIMBALLO = '396'
	

UNION

SELECT LEFT(A.CODICE, 5) AS ARTTIPOLOGIA
	, a.CODICE AS CODART
	, I.CODICE
	, I.DESCRIZIONE AS DESCRIMBALLO
	, I.VARIANTEIMBALLO
	, V.DESCRIZIONE AS DESCRVARIANTE
	, REPLACE(A.CODICE, 'XXX', V.VARIANTE) AS NUOVOCODART
	, A.DESCRIZIONE + ' ' + V.DESCRIZIONE
	, 'X' AS TIPO
	, 999	
	--, * 
FROM ANAGRAFICAARTICOLI a, TABIMBALLI I, TABVARIANTI V 
WHERE 
	ARTTIPOLOGIA = 0 AND LEN(A.CODICE) > 12 AND patindex('%K#%', a.codice) = 0 
	AND (LEFT(a.CODICE, 2) <> '21' OR LEFT(a.CODICE, 1) IN ('2', '3', '4'))
	AND RIGHT(a.CODICE, 3) = 'XXX' 
	AND V.VARIANTE = I.VARIANTEIMBALLO AND V.TIPOLOGIA = '62'
	AND I.VARIANTEIMBALLO IN ('394', '392', '390')
	AND A.CODICE IN (SELECT DISTINCT RD.CODART FROM RIGHEDOCUMENTI RD WHERE RD.TIPODOC IN ('OCC', 'OCE', 'OCG') AND ESERCIZIO >= 2016)
	
) CTE
WHERE NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.NUOVOCODART = CTE.NUOVOCODART)
GO

GRANT DELETE ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO

GRANT INSERT ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO

GRANT REFERENCES ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO

GRANT SELECT ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO

GRANT UPDATE ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO


*/

IF OBJECT_ID ('dbo.ZS_GENERAARTICOLI_EXTRA') IS NOT NULL
	DROP TABLE dbo.ZS_GENERAARTICOLI_EXTRA
GO

CREATE TABLE dbo.ZS_GENERAARTICOLI_EXTRA
	(
	ARTTIPOLOGIA    VARCHAR (50),
	CODART          VARCHAR (50) NOT NULL,
	CODICE          VARCHAR (10) NOT NULL,
	DESCRIZIONE     VARCHAR (500),
	VARIANTEIMBALLO VARCHAR (25),
	DESCRVARIANTE     VARCHAR (500),
	NUOVOCODART     VARCHAR (50) NOT NULL,
	UtenteModifica  VARCHAR (25) NOT NULL,
	DataModifica    DATETIME NOT NULL,
	TIPO VARCHAR(5),
	ORDINAMENTO     INT,
	CONSTRAINT PK__ZS_GENERAARTICOLI_EXTRA PRIMARY KEY (NUOVOCODART, CODICE, CODART)
	)
GO

GRANT DELETE ON dbo.ZS_GENERAARTICOLI_EXTRA TO Metodo98
GO
GRANT INSERT ON dbo.ZS_GENERAARTICOLI_EXTRA TO Metodo98
GO
GRANT REFERENCES ON dbo.ZS_GENERAARTICOLI_EXTRA TO Metodo98
GO
GRANT SELECT ON dbo.ZS_GENERAARTICOLI_EXTRA TO Metodo98
GO
GRANT UPDATE ON dbo.ZS_GENERAARTICOLI_EXTRA TO Metodo98
GO


INSERT INTO dbo.ZS_GENERAARTICOLI_EXTRA (ARTTIPOLOGIA, CODART, CODICE, DESCRIZIONE, VARIANTEIMBALLO, NUOVOCODART, UtenteModifica, DataModifica, ORDINAMENTO, TIPO, DESCRVARIANTE)
SELECT ARTTIPOLOGIA, CODART, CODICE, DESCRIZIONE, VARIANTEIMBALLO, NUOVOCODART, 'TRMXXX', GETDATE(), ORDINAMENTO, TIPO, DESCRVARIANTE FROM (
SELECT DISTINCT 
	LEFT(r.CODART, 5) AS ARTTIPOLOGIA
	, r.CODART AS CODART
	, 'XXX' AS CODICE
	, '' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO
	, '' AS DESCRVARIANTE
	, LEFT(r.CODART, 5) + '#000000' + I.VARIANTEIMBALLO AS NUOVOCODART
	, '' AS DESCRIZIONE
	, '3' AS TIPO
	, 999 AS ORDINAMENTO	
FROM RIGHEDOCUMENTI r , TABIMBALLI I
WHERE r.CODART <>'' 
AND I.VARIANTEIMBALLO = '370'
AND r.CODIMBALLO IN ('9', '300', '301', '302')
AND esercizio >= 2016 
AND LEFT(r.CODART, 1) IN ('2', '3', '4')
AND NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST z WHERE z.NUOVOCODART = LEFT(r.CODART, 5) + '#000000' + I.VARIANTEIMBALLO)

UNION

SELECT DISTINCT 
	LEFT(r.CODART, 5) AS ARTTIPOLOGIA
	, r.CODART AS CODART
	, 'XXX' AS CODICE
	, '' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO
	, '' AS DESCRVARIANTE
	, LEFT(r.CODART, 5) + '#000000XXX' AS NUOVOCODART
	, ''  AS DESCRIZIONE
	, '3' AS TIPO
	, 1 AS ORDINAMENTO
FROM RIGHEDOCUMENTI r , TABIMBALLI I
WHERE r.CODART <>'' 
AND I.VARIANTEIMBALLO = '370'
AND r.CODIMBALLO IN ('9', '300', '301', '302')
AND esercizio >= 2016 
AND LEFT(r.CODART, 1) IN ('2', '3', '4')
AND NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST z WHERE z.NUOVOCODART = LEFT(r.CODART, 5) + '#000000XXX')

UNION

SELECT DISTINCT 
	LEFT(r.CODART, 5) AS ARTTIPOLOGIA
	, r.CODART AS CODART
	, 'XXX' AS CODICE
	, '' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO
	, '' AS DESCRVARIANTE
	, LEFT(r.CODART, 5) + '#000000' + I.VARIANTEIMBALLOF AS NUOVOCODART
	, '' AS DESCRIZIONE
	, '4' AS TIPO
	, 999 AS ORDINAMENTO
FROM RIGHEDOCUMENTI r , TABIMBALLI I
WHERE r.CODART <>'' 
AND I.VARIANTEIMBALLOF IN ('986', '987', '988')
AND r.CODIMBALLO NOT IN ('9', '300', '301', '302')
AND esercizio >= 2016 
AND LEFT(r.CODART, 2) ='32'
AND NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST z WHERE z.NUOVOCODART = LEFT(r.CODART, 5) + '#000000' + I.VARIANTEIMBALLOF)

UNION

SELECT DISTINCT 
	LEFT(r.CODART, 5) AS ARTTIPOLOGIA
	, r.CODART AS CODART
	, 'XXX' AS CODICE
	, '' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO
	, '' AS DESCRVARIANTE
	, LEFT(r.CODART, 5) + '#000000XXX' AS NUOVOCODART
	, '' AS DESCRIZIONE
	, '4' AS TIPO
	, 1 AS ORDINAMENTO	
FROM RIGHEDOCUMENTI r , TABIMBALLI I
WHERE r.CODART <>'' 
AND I.VARIANTEIMBALLOF IN ('986', '987', '988')
AND r.CODIMBALLO NOT IN ('9', '300', '301', '302')
AND esercizio >= 2016 
AND LEFT(r.CODART, 2) ='32'
AND NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST z WHERE z.NUOVOCODART = LEFT(r.CODART, 5) + '#000000XXX')

UNION

SELECT LEFT(A.CODICE, 5) AS ARTTIPOLOGIA
	, a.CODICE AS CODART
	, I.CODICE
	, I.DESCRIZIONE AS DESCRIMBALLO
	, I.VARIANTEIMBALLO
	, V.DESCRIZIONE AS DESCRVARIANTE
	, REPLACE(A.CODICE, 'XXX', V.VARIANTE) AS NUOVOCODART
	, A.DESCRIZIONE + ' ' + V.DESCRIZIONE
	, '2' AS TIPO
	, 999	
	--, * 
FROM ANAGRAFICAARTICOLI a, TABIMBALLI I, TABVARIANTI V 
WHERE 
	ARTTIPOLOGIA = 0 AND LEN(A.CODICE) > 12 AND patindex('%K#%', a.codice) = 0 
	AND (LEFT(a.CODICE, 2) = '21' OR LEFT(a.CODICE, 5) = '25102' OR LEFT(a.CODICE, 5) = '25104' OR LEFT(a.CODICE, 5) = '20067')
	AND RIGHT(a.CODICE, 3) = 'XXX' 
	AND V.VARIANTE = I.VARIANTEIMBALLO AND V.TIPOLOGIA = '62'
	AND I.VARIANTEIMBALLO = '396'
	

	
) CTE


INSERT INTO dbo.ZS_GENERAARTICOLI_EXTRA (ARTTIPOLOGIA, CODART, CODICE, DESCRIZIONE, VARIANTEIMBALLO, NUOVOCODART, UtenteModifica, DataModifica, ORDINAMENTO, TIPO, DESCRVARIANTE)
SELECT LEFT(A.CODICE, 5) AS ARTTIPOLOGIA
	, a.CODICE AS CODART
	, I.CODICE
	, I.DESCRIZIONE AS DESCRIMBALLO
	, I.VARIANTEIMBALLO
	
	, LEFT(a.CODICE, 5) + '#000000' + I.VARIANTEIMBALLO AS NUOVOCODART
	--, A.DESCRIZIONE + ' ' + V.DESCRIZIONE
	
	, 'TRMXXX' AS UTENTEMODIFICA, GETDATE() AS DATAMODIFICA
	, 999	AS ORDINAMENTO
	, '1' AS TIPO
	, V.DESCRIZIONE AS DESCRVARIANTE
	--, * 
FROM ANAGRAFICAARTICOLI a, TABIMBALLI I, TABVARIANTI V 
WHERE LEFT(A.CODICE, 2) <> '21' AND (LEFT(A.CODICE, 1) IN ('2') OR LEFT(A.CODICE, 2) IN ('32', '42')) AND PATINDEX('%k%', A.CODICE) = 0 AND LEN(A.CODICE) = 5 
AND V.VARIANTE = I.VARIANTEIMBALLO AND V.TIPOLOGIA = '62'
AND I.VARIANTEIMBALLO IN ('394', '392', '390')
AND A.CODICE NOT IN (SELECT ZS_GENERAARTICOLI_EXTRA.CODART FROM  ZS_GENERAARTICOLI_EXTRA)

UNION


SELECT DISTINCT 
	LEFT(r.CODART, 5) AS ARTTIPOLOGIA
	, r.CODART AS CODART
	, 'XXX' AS CODICE
	, '' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO
	
	, LEFT(r.CODART, 5) + '#000000XXX' AS NUOVOCODART
	
	, 'TRMXXX' AS UTENTEMODIFICA, GETDATE() AS DATAMODIFICA
	, 999	AS ORDINAMENTO
	, '1' AS TIPO
	, '' AS DESCRVARIANTE
FROM RIGHEDOCUMENTI r , TABIMBALLI I
WHERE r.CODART = '43082' 
AND I.VARIANTEIMBALLO IN ( 'XXX')

AND NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST z WHERE z.NUOVOCODART = LEFT(r.CODART, 5) + '#000000XXX')
	







IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI
GO

CREATE VIEW ZS_VISTA_GENERAARTICOLI
AS
SELECT * FROM (
SELECT X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART
	, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WITH (NOLOCK) WHERE A.CODICE = X.CODART OR A.CODICE = X.ARTTIPOLOGIA) AS DESCRIZIONE --, '' AS TIPO
	, (SELECT 'B' FROM ZS_VISTA_GENERAARTICOLI_MOV Z WHERE Z.CODART = X.CODART AND LEFT(Z.CODART, 1) <> '2' GROUP BY Z.CODART HAVING COUNT(Z.CODART) = 1 ) AS TIPO
	, (CASE WHEN X.CODICE <> 'XXX' THEN 0 ELSE 9999 END) AS ORDINAMENTO

FROM 
	 ZS_VISTA_GENERAARTICOLI_MOV x -- ON  x.ARTTIPOLOGIA = cte.arttipologia AND x.CODIMBALLO = cte.cod_imballo
WHERE
	NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.CODART = X.CODART AND XX.NUOVOCODART = X.NUOVOCODART)
UNION
SELECT 
	X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART, X.DESCRIZIONE, X.TIPO 
	, (CASE WHEN X.CODICE <> 'XXX' THEN 0 ELSE 9999 END) AS ORDINAMENTO
FROM 
	ZS_VISTA_GENERAARTICOLI_MODELLI X
WHERE 
	NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.CODART = X.CODART AND XX.NUOVOCODART = X.NUOVOCODART)

UNION

SELECT 
	X.ARTTIPOLOGIA, X.CODART, X.CODICE, '' AS DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART
	, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WITH (NOLOCK) WHERE A.CODICE = X.CODART OR A.CODICE = X.ARTTIPOLOGIA) AS DESCRIZIONE
	, X.TIPO 
	, ORDINAMENTO
FROM 
	ZS_GENERAARTICOLI_EXTRA X
WHERE 
	NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.CODART = X.CODART AND XX.NUOVOCODART = X.NUOVOCODART)

	
) CTE
WHERE NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.NUOVOCODART = CTE.NUOVOCODART)
GO

GRANT DELETE ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT INSERT ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT REFERENCES ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT SELECT ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO
GRANT UPDATE ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO




SELECT * FROM RIGHEDOCUMENTI WITH (NOLOCK) WHERE CODART = '43082'


SELECT * FROM RELAZIONICFV WHERE codclifor = 'F  2102'


IF OBJECT_ID ('dbo.VISTARELAZIONICFV') IS NOT NULL
	DROP VIEW dbo.VISTARELAZIONICFV
GO

CREATE VIEW [dbo].[VISTARELAZIONICFV]
AS
SELECT     CODCLIFOR, RIFERIMENTO, ARTICOLO, VARIANTI, DESCRIZIONE, TIPOREL, MOSTRAVARIANTI, UTENTEMODIFICA, DATAMODIFICA, 
NOTE,
CODBONUS,
DSCART_ALT,
                      (CASE WHEN VARIANTI = '' OR
                      VARIANTI IS NULL OR
                      CHARINDEX('?', VARIANTI) > 0 THEN
                          (SELECT     DESCRIZIONE
                            FROM          ANAGRAFICAARTICOLI
                            WHERE      CODICE = ARTICOLO) ELSE
                          (SELECT     DESCRIZIONE
                            FROM          ANAGRAFICAARTICOLI
                            WHERE      CODICE = ARTICOLO + '#' + VARIANTI) END) AS DSCART, (CASE WHEN VARIANTI = '' OR
                      VARIANTI IS NULL OR
                      CHARINDEX('?', VARIANTI) > 0 THEN
                          (SELECT     ARTTIPOLOGIA
                            FROM          ANAGRAFICAARTICOLI
                            WHERE      CODICE = ARTICOLO) ELSE
                          (SELECT     ARTTIPOLOGIA
                            FROM          ANAGRAFICAARTICOLI
                            WHERE      CODICE = ARTICOLO + '#' + VARIANTI) END) AS ARTTIPOLOGIA, (CASE WHEN VARIANTI = '' OR
                      VARIANTI IS NULL OR
                      CHARINDEX('?', VARIANTI) > 0 THEN
                          (SELECT     CODICE
                            FROM          ANAGRAFICAARTICOLI
                            WHERE      CODICE = ARTICOLO) ELSE
                          (SELECT     CODICEPRIMARIO
                            FROM          ANAGRAFICAARTICOLI
                            WHERE      CODICE = ARTICOLO + '#' + VARIANTI) END) AS CODICEPRIMARIO, (CASE WHEN TIPOREL = 1 THEN ARTICOLO ELSE RIFERIMENTO END) 
                      AS CODICERIF, (CASE WHEN Varianti = '' OR
                      VARIANTI IS NULL THEN Articolo ELSE (Articolo + '#' + replace(Varianti, '?', '%')) END) CodArticolo, escludiperperiodo
, RELAZIONICFV.ARTICOLOBSC
, SPECIFICAACQ
FROM         RELAZIONICFV
GO

GRANT SELECT ON dbo.VISTARELAZIONICFV TO Metodo98
GO


