/*





-- ELENCO DOCUMENTI DAL 2016 ORDINI APERTI CON ARTICOLI NON CORRISPONDENTI ALLA COMBINAZIONE IMBALLO VARIANTE IMBALLO
SELECT r.IDTESTA, R.IDRIGA, r.TIPODOC, r.ESERCIZIO, r.NUMERODOC
, r.CODART, r.DESCRIZIONEART, r.CODIMBALLO, R.RIGACHIUSA, R.QTAGESTRES
, X.VARIANTEIMBALLO, V.DESCRIZIONE, X.VARIANTEIMBALLOF
--, X.*
, 'ELENCO DOCUMENTI DAL 2016 ORDINI APERTI CON ARTICOLI NON CORRISPONDENTI ALLA COMBINAZIONE IMBALLO VARIANTE IMBALLO' AS DSCR
 FROM RIGHEDOCUMENTI r JOIN TABIMBALLI x ON x.codice = r.CODIMBALLO
JOIN TABVARIANTI V ON V.VARIANTE = X.VARIANTEIMBALLO
WHERE V.TIPOLOGIA = '62' AND
r.TIPODOC IN ('OCC', 'OCE') AND 
r.ESERCIZIO >= 2016 AND len(r.CODART) > 5 --AND RIGHT(R.CODART, 3) = 'XXX'
AND R.RIGACHIUSA = 0
AND RIGHT(R.CODART, 3) <> (CASE WHEN LEFT(R.CODART, 2) IN ('32', '43') THEN X.VARIANTEIMBALLOF ELSE X.VARIANTEIMBALLO END)

UNION

-- ELENCO DOCUMENTI DEL 2018 CON ARTICOLI NON CORRISPONDENTI ALLA COMBINAZIONE IMBALLO VARIANTE IMBALLO
SELECT r.IDTESTA, R.IDRIGA, r.TIPODOC, r.ESERCIZIO, r.NUMERODOC
, r.CODART, r.DESCRIZIONEART, r.CODIMBALLO, R.RIGACHIUSA, R.QTAGESTRES
, X.VARIANTEIMBALLO, V.DESCRIZIONE, X.VARIANTEIMBALLOF
--, X.*
, 'ELENCO DOCUMENTI DEL 2018 CON ARTICOLI NON CORRISPONDENTI ALLA COMBINAZIONE IMBALLO VARIANTE IMBALLO' AS DSCR
 FROM RIGHEDOCUMENTI r JOIN TABIMBALLI x ON x.codice = r.CODIMBALLO
JOIN TABVARIANTI V ON V.VARIANTE = X.VARIANTEIMBALLO
WHERE V.TIPOLOGIA = '62' AND
r.TIPODOC NOT IN ('OCG', 'DCG',  'OCC', 'OCE') AND 
r.ESERCIZIO = 2018 
AND len(r.CODART) > 5 --AND RIGHT(R.CODART, 3) = 'XXX'
AND R.RIGACHIUSA = 0
AND RIGHT(R.CODART, 3) <> (CASE WHEN LEFT(R.CODART, 2) IN ('32', '43') THEN X.VARIANTEIMBALLOF ELSE X.VARIANTEIMBALLO END)



-- ELENCO DOCUMENTI DEL 2018 CON ARTICOLI NON CORRISPONDENTI ALLA COMBINAZIONE IMBALLO VARIANTE IMBALLO
SELECT r.IDTESTA, R.IDRIGA, r.TIPODOC, r.ESERCIZIO, r.NUMERODOC
, r.CODART, r.DESCRIZIONEART, r.CODIMBALLO, R.RIGACHIUSA, R.QTAGESTRES
, X.VARIANTEIMBALLO, V.DESCRIZIONE, X.VARIANTEIMBALLOF
--, X.*
, 'ELENCO DOCUMENTI DEL 2018 CON ARTICOLI NON CORRISPONDENTI ALLA COMBINAZIONE IMBALLO VARIANTE IMBALLO' AS DSCR
 FROM RIGHEDOCUMENTI r JOIN TABIMBALLI x ON x.codice = r.CODIMBALLO
JOIN TABVARIANTI V ON V.VARIANTE = X.VARIANTEIMBALLO
WHERE V.TIPOLOGIA = '62' AND
r.TIPODOC IN ('OFO', 'OFE',  'DTF', 'DTE') AND 
r.ESERCIZIO = 2018 
AND len(r.CODART) > 5 --AND RIGHT(R.CODART, 3) = 'XXX'
--AND R.RIGACHIUSA = 0
AND RIGHT(R.CODART, 3) <> (CASE WHEN LEFT(R.CODART, 2) IN ('32', '43') THEN X.VARIANTEIMBALLOF ELSE X.VARIANTEIMBALLO END)






-- ELENCO DOCUMENTI DEL 2018 CON ARTICOLI NON CORRISPONDENTI ALLA COMBINAZIONE IMBALLO VARIANTE IMBALLO
SELECT r.IDTESTA, R.IDRIGA, r.TIPODOC, r.ESERCIZIO, r.NUMERODOC
, r.CODART, r.DESCRIZIONEART, r.CODIMBALLO, R.RIGACHIUSA, R.QTAGESTRES
, X.VARIANTEIMBALLO, V.DESCRIZIONE, X.VARIANTEIMBALLOF
--, X.*
, 'ELENCO DOCUMENTI DEL 2018 CON ARTICOLI NON CORRISPONDENTI ALLA COMBINAZIONE IMBALLO VARIANTE IMBALLO' AS DSCR
 FROM RIGHEDOCUMENTI r JOIN TABIMBALLI x ON x.codice = r.CODIMBALLO
JOIN TABVARIANTI V ON V.VARIANTE = X.VARIANTEIMBALLO
WHERE V.TIPOLOGIA = '62' AND RIGHT(CODART, 3) = 'XXX' AND LEFT(R.CODART, 1) IN ('3', '4') AND 
--r.TIPODOC IN ('OCC', 'OCE') AND 
r.ESERCIZIO = 2018 
--AND R.RIGACHIUSA = 0
AND RIGHT(R.CODART, 3) <> (CASE WHEN LEFT(R.CODART, 2) IN ('32', '43') THEN X.VARIANTEIMBALLOF ELSE X.VARIANTEIMBALLO END)




-- ELENCO DOCUMENTI DEL 2018 CON ARTICOLI XXX NON CORRISPONDENTI ALLA COMBINAZIONE IMBALLO VARIANTE IMBALLO
SELECT r.IDTESTA, R.IDRIGA, r.TIPODOC, r.ESERCIZIO, r.NUMERODOC
, r.CODART, r.DESCRIZIONEART, r.CODIMBALLO, R.RIGACHIUSA, R.QTAGESTRES
, r.idtestarp, r.idrigarp
, X.VARIANTEIMBALLO, X.VARIANTEIMBALLOF
, LEFT(R.CODART, 2) AS TIPOART
, REPLACE(R.CODART, 'XXX', (CASE WHEN LEFT(R.CODART, 2) IN ('32', '43') THEN X.VARIANTEIMBALLOF ELSE X.VARIANTEIMBALLO END)) AS NUOVOCODART
--, V.DESCRIZIONE, X.VARIANTEIMBALLOF
--, X.*
, 'ELENCO DOCUMENTI DEL 2018 CON ARTICOLI XXX NON CORRISPONDENTI ALLA COMBINAZIONE IMBALLO VARIANTE IMBALLO' AS DSCR
INTO _DOC0000011
 FROM RIGHEDOCUMENTI r LEFT OUTER JOIN TABIMBALLI x ON x.codice = r.CODIMBALLO
--LEFT OUTER JOIN TABVARIANTI V ON V.VARIANTE = X.VARIANTEIMBALLO
WHERE 
--V.TIPOLOGIA = '62' AND 
RIGHT(CODART, 3) = 'XXX' AND 
r.TIPODOC NOT IN ('OCG', 'DCG') AND 
r.ESERCIZIO = 2018 
--AND R.RIGACHIUSA = 0
AND RIGHT(R.CODART, 3) <> (CASE WHEN ISNULL(X.VARIANTEIMBALLO, '') = '' THEN X.VARIANTEIMBALLOF ELSE X.VARIANTEIMBALLO END)








-- ELENCO DOCUMENTI DEL 2018 CON ARTICOLI XXX NON CORRISPONDENTI ALLA COMBINAZIONE IMBALLO VARIANTE IMBALLO
SELECT r.IDTESTA, R.IDRIGA, r.TIPODOC, r.ESERCIZIO, r.NUMERODOC
, r.CODART, r.DESCRIZIONEART, r.CODIMBALLO, R.RIGACHIUSA, R.QTAGESTRES
, r.idtestarp, r.idrigarp
, X.VARIANTEIMBALLO, X.VARIANTEIMBALLOF
, LEFT(R.CODART, 2) AS TIPOART
, REPLACE(R.CODART, 'XXX', (CASE WHEN LEFT(R.CODART, 2) IN ('32', '43') THEN X.VARIANTEIMBALLOF ELSE X.VARIANTEIMBALLO END)) AS NUOVOCODART
--, V.DESCRIZIONE, X.VARIANTEIMBALLOF
--, X.*
, 'ELENCO DOCUMENTI DEL 2018 CON ARTICOLI XXX NON CORRISPONDENTI ALLA COMBINAZIONE IMBALLO VARIANTE IMBALLO' AS DSCR
INTO _DOC0000012
 FROM RIGHEDOCUMENTI r LEFT OUTER JOIN TABIMBALLI x ON x.codice = r.CODIMBALLO
--LEFT OUTER JOIN TABVARIANTI V ON V.VARIANTE = X.VARIANTEIMBALLO
WHERE 
--V.TIPOLOGIA = '62' AND 
RIGHT(CODART, 3) = 'XXX' AND 
r.TIPODOC IN ('OFO', 'OFE', 'OCC', 'OCE') AND 
r.ESERCIZIO >= 2016
AND R.RIGACHIUSA = 0
AND RIGHT(R.CODART, 3) <> (CASE WHEN ISNULL(X.VARIANTEIMBALLO, '') = '' THEN X.VARIANTEIMBALLOF ELSE X.VARIANTEIMBALLO END)





*/




UPDATE RELAZIONICFV 
SET ARTICOLO = LEFT(ARTICOLO, 5)
, VARIANTI = SUBSTRING(ARTICOLO, CHARINDEX('#', ARTICOLO)+1, LEN(ARTICOLO) - CHARINDEX('#', ARTICOLO))
FROM RELAZIONICFV WHERE CHARINDEX('#', ARTICOLO) > 0

UPDATE RELAZIONICFV 
SET VARIANTI = REPLACE(VARIANTI, 'XXX', '???')
WHERE RIGHT(VARIANTI, 3) = 'XXX' --AND LEFT(CODCLIFOR, 1) = 'C'


UPDATE EXTRAMAG
SET ESAURITO = 'S'
 WHERE RIGHT(codart, 3) = 'XXX' AND ISNULL(ESAURITO, '') <> 'S'




IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI_MODELLI_ALL') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI_MODELLI_ALL
GO

CREATE view ZS_VISTA_GENERAARTICOLI_MODELLI_ALL as 


SELECT R.CODART AS ARTTIPOLOGIA
	, R.CODART, '' AS CODICE
	, 'XXX' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO, 'XXX' AS DESCRVARIANTE
	, (R.CODART + '#000000XXX') AS NUOVOCODART 
	, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WITH (NOLOCK) WHERE A.CODICE = R.CODART) AS DESCRIZIONE
	, 'A' AS TIPO
	FROM (
SELECT X.CODICE AS CODART FROM ANAGRAFICAARTICOLI X 
WHERE X.ARTTIPOLOGIA = 0 AND LEFT(X.CODICE, 2) IN ('32', '43') AND LEN(X.CODICE) = 5) R
GO

GRANT SELECT ON dbo.ZS_VISTA_GENERAARTICOLI_MODELLI_ALL TO Metodo98
GO


IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI_MOV') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI_MOV
GO

CREATE VIEW ZS_VISTA_GENERAARTICOLI_MOV
AS

SELECT * FROM (
	SELECT DISTINCT 
	(CASE WHEN charindex('#', R.CODART) > 1 THEN LEFT(R.CODART, charindex('#', R.CODART) - 1) ELSE R.CODART END) AS ARTTIPOLOGIA
	, R.CODART, R.CODIMBALLO AS CODICE, I.DESCRIZIONE AS DESCRIMBALLO, I.VARIANTEIMBALLO, V.DESCRIZIONE AS DESCRVARIANTE
	, (CASE WHEN LEFT(R.CODART, 1) IN ('3', '4') THEN
		 (CASE 
		WHEN RIGHT(R.CODART, 3) = 'XXX' THEN REPLACE(R.CODART, 'XXX',  '000' + I.VARIANTEIMBALLO)
		--WHEN RIGHT(R.CODART, 3) <> 'XXX' AND I.VARIANTEIMBALLO = 'XXX' THEN REPLACE(R.CODART, RIGHT(R.CODART, 3),  '000' + RIGHT(R.CODART, 3))
		ELSE R.CODART + '#000' + '000' + I.VARIANTEIMBALLO
		END) 
	ELSE	
	 --(CASE WHEN RIGHT(R.CODART, 3) = 'XXX' THEN LEFT(R.CODART, LEN(R.CODART) - 3) +  '000' + RIGHT(R.CODART, 3)
		--ELSE 
		LEFT(R.CODART, LEN(R.CODART) - 3) +  '000' + I.VARIANTEIMBALLO
		--END) 
	END) AS NUOVOCODART
	
FROM RIGHEDOCUMENTI R WITH (NOLOCK) 
JOIN TABIMBALLI I WITH (NOLOCK) ON I.CODICE = R.CODIMBALLO
JOIN TABVARIANTI v WITH (NOLOCK) ON v.VARIANTE = I.varianteimballo
AND R.ESERCIZIO = 2018
WHERE R.CODART <> '' 
AND V.TIPOLOGIA = '62'
 --AND r.TIPODOC IN ('oce', 'occ', 'ocg')  --AND r.RIGACHIUSA = 0 AND r.QTAGESTRES > 0
AND I.VARIANTEIMBALLO <> ''
AND len(r.CODART) <= 12
	) CTE
WHERE LEN(ARTTIPOLOGIA) = 5
	AND ARTTIPOLOGIA BETWEEN '20000' AND '49999' 
	
	AND charindex('#', substring(nuovocodart, charindex('#', nuovocodart) + 1, 10) ) = 0
	--AND NUOVOCODART NOT IN (SELECT CODICE FROM ANAGRAFICAARTICOLI)
	
	/*
UNION
	
SELECT 
	LEFT(A.CODICE, 5) AS ARTTIPOLOGIA
	, a.CODICE AS CODART
	, 'XXX' AS CODICE
	, '' AS DESCRIMBALLO
	, 'XXX' AS VARIANTEIMBALLO
	, '' AS DESCRVARIANTE
	, (CASE WHEN RIGHT(A.CODICE, 3) <> 'XXX' THEN LEFT(A.CODICE, LEN(A.CODICE) - 3) +  '000' + RIGHT(A.CODICE, 3)
	ELSE 	REPLACE(A.CODICE, 'XXX',  '000XXX')
	END) AS NUOVOCODART 
FROM 
	ANAGRAFICAARTICOLI a WITH (nolock)
WHERE 
	a.CODICEPRIMARIO in
	(SELECT CODICE FROM ANAGRAFICAARTICOLI  WITH (nolock)
	WHERE ARTTIPOLOGIA = 1
	AND isnumeric(codice) = 1
	AND CODICE BETWEEN '20000' AND '49999')
	AND len(A.CODICE) <= 12
	AND patindex('%#k%', CODICE) = 0
	*/
GO

GRANT DELETE ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO

GRANT INSERT ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO

GRANT REFERENCES ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO

GRANT SELECT ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO

GRANT UPDATE ON dbo.ZS_VISTA_GENERAARTICOLI_MOV TO Metodo98
GO





IF OBJECT_ID ('dbo.ZS_VISTA_GENERAARTICOLI') IS NOT NULL
	DROP VIEW dbo.ZS_VISTA_GENERAARTICOLI
GO

CREATE VIEW ZS_VISTA_GENERAARTICOLI
AS
SELECT * FROM (

SELECT X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART
	, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WITH (NOLOCK) WHERE A.CODICE = X.CODART OR A.CODICE = X.ARTTIPOLOGIA) AS DESCRIZIONE --, '' AS TIPO
	, (SELECT 'B' FROM ZS_VISTA_GENERAARTICOLI_MOV Z WHERE Z.CODART = X.CODART AND LEFT(Z.CODART, 1) <> '2' GROUP BY Z.CODART HAVING COUNT(Z.CODART) = 1 ) AS TIPO
	, (CASE WHEN X.CODICE <> 'XXX' THEN 0 ELSE 9999 END) AS ORDINAMENTO

FROM 
	 ZS_VISTA_GENERAARTICOLI_MOV x -- ON  x.ARTTIPOLOGIA = cte.arttipologia AND x.CODIMBALLO = cte.cod_imballo
WHERE
	NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.CODART = X.CODART AND XX.NUOVOCODART = X.NUOVOCODART)
UNION
/*
SELECT 
	X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART, X.DESCRIZIONE, X.TIPO 
	, (CASE WHEN X.CODICE <> 'XXX' THEN 0 ELSE 9999 END) AS ORDINAMENTO
FROM 
	ZS_VISTA_GENERAARTICOLI_MODELLI X
WHERE 
	NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.CODART = X.CODART AND XX.NUOVOCODART = X.NUOVOCODART)
*/
SELECT 
	X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART, X.DESCRIZIONE, X.TIPO 
	, (CASE WHEN X.CODICE <> 'XXX' THEN 0 ELSE 9999 END) AS ORDINAMENTO
FROM 
	ZS_VISTA_GENERAARTICOLI_MODELLI_all X
WHERE 
	NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.CODART = X.CODART AND XX.NUOVOCODART = X.NUOVOCODART)
	
	
UNION

SELECT 
	X.ARTTIPOLOGIA, X.CODART, X.CODICE, '' AS DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART
	, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WITH (NOLOCK) WHERE A.CODICE = X.CODART OR A.CODICE = X.ARTTIPOLOGIA) + ' ' + x.DESCRVARIANTE AS DESCRIZIONE
	, X.TIPO 
	, ORDINAMENTO
FROM 
	ZS_GENERAARTICOLI_EXTRA X
WHERE 
	NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.CODART = X.CODART AND XX.NUOVOCODART = X.NUOVOCODART)

	
) CTE
WHERE NOT EXISTS(SELECT 1 FROM ZS_GENERAARTICOLI_POST XX WHERE XX.NUOVOCODART = CTE.NUOVOCODART)
UNION
SELECT X.ARTTIPOLOGIA, X.CODART, X.CODICE, X.DESCRIMBALLO, X.VARIANTEIMBALLO, X.DESCRVARIANTE, X.NUOVOCODART, X.DESCRIZIONE, X.TIPO, X.ORDINAMENTO 
FROM (
SELECT LEFT(z.codice, 5) AS ARTTIPOLOGIA , LEFT(z.codice, 5) AS CODART , '' AS CODICE, '' AS DESCRIMBALLO
, V.variante AS  VARIANTEIMBALLO
, V.DESCRIZIONE AS DESCRVARIANTE
, z.codice + '#000000' + V.VARIANTE AS NUOVOCODART
	, (SELECT TOP 1 A.DESCRIZIONE FROM ANAGRAFICAARTICOLI A WITH (NOLOCK) WHERE A.CODICE = LEFT(z.codice, 5) OR A.CODICE = LEFT(z.codice, 5)) + ' ' + V.DESCRIZIONE AS DESCRIZIONE
, 'x' AS TIPO
, 1000 AS ORDINAMENTO 
FROM ANAGRAFICAARTICOLI z, ZS_TABVARIANTI V Where V.SEL = 1 AND z.ARTTIPOLOGIA = 1 AND LEN(CODICE) = 5   
) X 
WHERE NOT EXISTS(SELECT 1 FROM ANAGRAFICAARTICOLI XX WHERE XX.CODICE = X.NUOVOCODART)

GO

GRANT DELETE ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO

GRANT INSERT ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO

GRANT REFERENCES ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO

GRANT SELECT ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO

GRANT UPDATE ON dbo.ZS_VISTA_GENERAARTICOLI TO Metodo98
GO








SELECT *, (SELECT count(CODICE) FROM ANAGRAFICAARTICOLI a WHERE a.CODICE = _DOC0000012.NUOVOCODART) AS ESISTE 
FROM _DOC0000012 WHERE NUOVOCODART NOT IN (SELECT CODICE FROM ANAGRAFICAARTICOLI)



-- aggiornamento movimenti di magazzino documenti 2018
SELECT S.CODART, S.RIFERIMENTI, t.DESCRIZIONE, R.NUOVOCODART
--UPDATE S SET S.CODART = R.NUOVOCODART
 FROM _DOC0000011 R JOIN STORICOMAG S ON S.IDTESTA = R.IDTESTA AND S.RIGADOC = R.IDRIGA
		JOIN tabimballi t ON t.CODICE = r.CODIMBALLO
	WHERE R.NUOVOCODART IN (SELECT CODICE FROM ANAGRAFICAARTICOLI)

	
	

SELECT S.CODART, S.RIFERIMENTI, t.DESCRIZIONE, R.NUOVOCODART, R.IDTESTArp, s.codcausale
--UPDATE S SET S.CODART = R.NUOVOCODART
 FROM _DOC0000011 R JOIN STORICOMAG S ON S.IDTESTA = R.IDTESTArp AND S.RIGADOC = R.IDRIGArp
		JOIN tabimballi t ON t.CODICE = r.CODIMBALLO
	WHERE R.IDTESTArp > 0 AND  R.NUOVOCODART IN (SELECT CODICE FROM ANAGRAFICAARTICOLI) AND S.CODART <> R.NUOVOCODART

SELECT 
	r.IDTESTA,
	r.IDRIGA,
	r.TIPODOC,
	r.ESERCIZIO,
	r.NUMERODOC,
	x.TIPODOC,
	x.ESERCIZIO,
	x.NUMERODOC,
	r.CODART,
	r.DESCRIZIONEART,
	r.CODIMBALLO,
	r.RIGACHIUSA,
	r.QTAGESTRES,
	x.VARIANTEIMBALLO,
	x.VARIANTEIMBALLOF,
	x.TIPOART,
	x.NUOVOCODART,
	x.DSCR
	--UPDATE r SET r.CODART = X.NUOVOCODART
FROM righedocumenti r JOIN  dbo._DOC0000011 x ON x.idtestarp = r.idtesta AND x.idrigarp = r.idriga


SELECT 

	r.IDTESTA,
	r.IDRIGA,
	r.TIPODOC,
	r.ESERCIZIO,
	r.NUMERODOC,
	x.TIPODOC,
	x.ESERCIZIO,
	x.NUMERODOC,
	r.CODART,
	r.DESCRIZIONEART,
	r.CODIMBALLO,
	r.RIGACHIUSA,
	r.QTAGESTRES,
	x.VARIANTEIMBALLO,
	x.VARIANTEIMBALLOF,
	x.TIPOART,
	x.NUOVOCODART,
	x.DSCR
	--UPDATE r SET r.CODART = X.NUOVOCODART
 FROM righedocumenti r JOIN  dbo._DOC0000011 x ON x.idtesta = r.idtesta AND x.idriga = r.idriga  
		JOIN tabimballi t ON t.CODICE = r.CODIMBALLO
	WHERE x.NUOVOCODART IN (SELECT CODICE FROM ANAGRAFICAARTICOLI)
	
	
	
	




SELECT 

	r.IDTESTA,
	r.IDRIGA,
	r.TIPODOC,
	r.ESERCIZIO,
	r.NUMERODOC,
	x.TIPODOC,
	x.ESERCIZIO,
	x.NUMERODOC,
	r.CODART,
	r.DESCRIZIONEART,
	r.CODIMBALLO,
	r.RIGACHIUSA,
	r.QTAGESTRES,
	x.VARIANTEIMBALLO,
	x.VARIANTEIMBALLOF,
	x.TIPOART,
	x.NUOVOCODART,
	x.DSCR
	--UPDATE r SET r.CODART = X.NUOVOCODART
 FROM righedocumenti r JOIN  dbo._DOC0000012 x ON x.idtesta = r.idtesta AND x.idriga = r.idriga  
		JOIN tabimballi t ON t.CODICE = r.CODIMBALLO
	WHERE x.NUOVOCODART IN (SELECT CODICE FROM ANAGRAFICAARTICOLI)





-- aggiornamento movimenti di magazzino documenti 2018
SELECT S.CODART, S.RIFERIMENTI, t.DESCRIZIONE, R.NUOVOCODART
--UPDATE S SET S.CODART = R.NUOVOCODART
 FROM _DOC0000012 R JOIN STORICOMAG S ON S.IDTESTA = R.IDTESTA AND S.RIGADOC = R.IDRIGA
		JOIN tabimballi t ON t.CODICE = r.CODIMBALLO
	WHERE R.NUOVOCODART IN (SELECT CODICE FROM ANAGRAFICAARTICOLI)



-- macroarticoli
SELECT * 
FROM ITA_TAB_DEFPROV
WHERE LEFT(MACROARTICOLO, 1) NOT IN ('1', '8') AND LEN(MACROARTICOLO) < 13


UPDATE dbo.ITA_TAB_DEFPROV
SET MACROARTICOLO = '32260#000000XXX'
WHERE MACROARTICOLO = '32260'
GO


SELECT E.CODART, E.MACRO_ART, E.MACRO_ART + '#000000XXX' 
FROM EXTRAMAG E
WHERE E.MACRO_ART  IN (SELECT A.CODICE FROM ANAGRAFICAARTICOLI A WHERE A.ARTTIPOLOGIA = 1)
AND LEN(E.CODART) IN (5, 15)
AND E.MACRO_ART + '#000000XXX' IN (SELECT XX.MACROARTICOLO FROM ITA_TAB_DEFPROV XX)



UPDATE E
SET E.MACRO_ART = E.MACRO_ART + '#000000XXX' 
FROM EXTRAMAG E
WHERE E.MACRO_ART  IN (SELECT A.CODICE FROM ANAGRAFICAARTICOLI A WHERE A.ARTTIPOLOGIA = 1)
AND LEN(E.CODART) IN (5, 15)
AND E.MACRO_ART + '#000000XXX' IN (SELECT XX.MACROARTICOLO FROM ITA_TAB_DEFPROV XX)


