//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoNotificheBSC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=srv2k8;Initial Catalog=ZSI;Persist Security Info=True;User ID=sa;Pass" +
            "word=sash17ne")]
        public string MetodoConnectionString {
            get {
                return ((string)(this["MetodoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM VISTA_NOTIFICHECLIENTICONTATTI")]
        public string MetodoCommand {
            get {
                return ((string)(this["MetodoCommand"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SMTPServerName=smtp.gmail.com</string>
  <string>SMTPAUTHPassword=serverBI2017</string>
  <string>SMTPAUTHUser=knosmail@gmail.com</string>
  <string>SMTPAUTHUserEmail=knosmail@gmail.com</string>
  <string>SMTPPort=465</string>
  <string>SMTPUseSSL=1</string>
  <string>SMTPAlwaysSendAs=</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CdoConfig {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CdoConfig"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseCdo {
            get {
                return ((bool)(this["UseCdo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string sendMailPopUp {
            get {
                return ((string)(this["sendMailPopUp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<html>
<body>
    <div>
        <p>
            <br />
            Gent.mo Cliente,<br />
            in allegato l'aggiornamento di:<br />
            <b>{0}</b><br />
            <b>{1}</b><br />
            {2}<br /><br />
            Si prega di non rispondere a questo indirizzo email.<br />
            <br />
            Dear Customer,<br />
            please find the attached revised document:<br />
            <b>{0}</b><br />
            <b>{1}</b><br />
            {2}<br /><br />
            Please do not reply to this email address.<br />
        </p>
    </div>
    <div>
        <hr />
        <p>
            <span><b>ZSCHIMMER & SCHWARZ ITALIANA S.p.A.</b></span>
        <br />
        Via A. Ariotto 1/C<br />
        I - 13038 Tricerro, Italia<br />
        <br />
        Tel: +39 0161 808111<br />
        Fax: +39 0161 807335<br />
        Ufficio Commerciale/Sales Office:<br />
        Fax: +39 0161 801002<br />
    </div>
</body>
</html>")]
        public string sendMailSchede {
            get {
                return ((string)(this["sendMailSchede"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EmailImages")]
        public string sendMailEmbeddedImagesPath {
            get {
                return ((string)(this["sendMailEmbeddedImagesPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KnoS_IdObject {
            get {
                return ((int)(this["KnoS_IdObject"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("administrator")]
        public string KnoS_User {
            get {
                return ((string)(this["KnoS_User"]));
            }
            set {
                this["KnoS_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KnoS_PWD {
            get {
                return ((string)(this["KnoS_PWD"]));
            }
            set {
                this["KnoS_PWD"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<html>
<body>
    <div>
        <p>
            <br />
            Gent.mo Cliente,<br />
            Vi preghiamo di prendere visione del file allegato<br />

	    Non rispondere a questo indirizzo mail<br />
            <br />
            Dear Customer,<br />
            please find the attached document:<br />

            Please do not reply to this email address.<br />
        </p>
    </div>
    <div>
        <hr />
        <p>
            <span><b>ZSCHIMMER &amp; SCHWARZ ITALIANA S.p.A.</b></span>
        <br />
        Via A. Ariotto 1/C<br />
        I - 13038 Tricerro, Italia<br />
        <br />
        Tel: +39 0161 808111<br />
        Fax: +39 0161 807335<br />
        Ufficio Commerciale/Sales Office:<br />
        Fax: +39 0161 801002<br />
</p>
    </div>
</body>
</html>")]
        public string sendMailComunicazioni {
            get {
                return ((string)(this["sendMailComunicazioni"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W:\\")]
        public string PathPDF {
            get {
                return ((string)(this["PathPDF"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zsi-websrv:81")]
        public string KnoS_URL {
            get {
                return ((string)(this["KnoS_URL"]));
            }
            set {
                this["KnoS_URL"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invio SCHEDE TECNICHE/MSDS - Cliente/Customer: {0}")]
        public string sendMailSchedeTecnicheSubject {
            get {
                return ((string)(this["sendMailSchedeTecnicheSubject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invio BOLLETTINI - Cliente/Customer {0}")]
        public string sendMailBollettiniSubject {
            get {
                return ((string)(this["sendMailBollettiniSubject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("knosmail@gmail.com;m.michieletti@zschimmer-schwarz.com;msds.zsi@zschimmer-schwarz" +
            ".com;")]
        public string sendMailBCC {
            get {
                return ((string)(this["sendMailBCC"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-05-01")]
        public global::System.DateTime DataAggiornamento {
            get {
                return ((global::System.DateTime)(this["DataAggiornamento"]));
            }
            set {
                this["DataAggiornamento"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXECUTE dbo.ITA_SP_UPDATE_REGISTRONOTIFICHEBSC ")]
        public string SqlUpdateBSC {
            get {
                return ((string)(this["SqlUpdateBSC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5018")]
        public int KnoS_IdActionUpdateSchede {
            get {
                return ((int)(this["KnoS_IdActionUpdateSchede"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5016")]
        public int KnoS_IdActionUpdateSchedeRedazione {
            get {
                return ((int)(this["KnoS_IdActionUpdateSchedeRedazione"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H:\\LETTERATURE PRODOTTI FINITI\\SCHEDE DI SICUREZZA")]
        public string PathPDF_H {
            get {
                return ((string)(this["PathPDF_H"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("knosmail@gmail.com;m.michieletti@zschimmer-schwarz.com")]
        public string sendMailBCCSimulazione {
            get {
                return ((string)(this["sendMailBCCSimulazione"]));
            }
            set {
                this["sendMailBCCSimulazione"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\_SVILUPPO\\ZSI\\")]
        public string PathCOA {
            get {
                return ((string)(this["PathCOA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invio COA - Cliente/Customer: {0}")]
        public string sendMailCOASubject {
            get {
                return ((string)(this["sendMailCOASubject"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-01-01")]
        public global::System.DateTime DataInvioSchede {
            get {
                return ((global::System.DateTime)(this["DataInvioSchede"]));
            }
            set {
                this["DataInvioSchede"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<html>
<body>
    <div>
        <p>
            <br />
            Gent.mo Cliente,<br />
            in allegato il certificato di analisi di:<br />
            {0}<br />
            Si prega di non rispondere a questo indirizzo email.<br />
            <hr />
            Dear Customer,<br />
            please find the attached revised document:<br />
            {0}<br />
            Please do not reply to this email address.<br />
        </p>
    </div>
    <div>
        <hr />
        <p>
            <span><b>ZSCHIMMER & SCHWARZ ITALIANA S.p.A.</b></span>
        <br />
        Via A. Ariotto 1/C<br />
        I - 13038 Tricerro, Italia<br />
        <br />
        Tel: +39 0161 808111<br />
        Fax: +39 0161 807335<br />
        Ufficio Commerciale/Sales Office:<br />
        Fax: +39 0161 801002<br />
    </div>
</body>
</html>")]
        public string sendMailCOA {
            get {
                return ((string)(this["sendMailCOA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM ZS_VISTA_ALLEGATISCHEDESICUREZZA")]
        public string MetodoCommandAllegati {
            get {
                return ((string)(this["MetodoCommandAllegati"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseVbs {
            get {
                return ((bool)(this["UseVbs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"""Gent.mo Cliente,"" & vbcrlf & ""Vi preghiamo di prendere visione del file allegato"" & vbcrlf & ""{0}"" & vbcrlf & ""Si prega di non rispondere a questo indirizzo email."" & vbcrlf & ""Dear Customer,"" & vbcrlf & ""please find the attached document:"" & vbcrlf & ""{0}"" & vbcrlf & ""Please do not reply to this email address."" & vbcrlf & ""ZSCHIMMER & SCHWARZ"" & vbcrlf & ""Italiana S.p.A."" & vbcrlf & ""Via A. Ariotto 1/C"" & vbcrlf & ""I - 13038 Tricerro, Italia"" & vbcrlf & ""Tel: +39 0161 808111"" & vbcrlf & ""Fax: +39 0161 807335"" & vbcrlf & ""Ufficio Commerciale:"" & vbcrlf & ""Fax: +39 0161 801002"" ")]
        public string sendMailComunicazioniVbsLotus {
            get {
                return ((string)(this["sendMailComunicazioniVbsLotus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ORDINI CISTERNA|SELECT * FROM VISTA_KNOS_INVIOCONFERMAORDINIMAIL WHERE CISTERNA = 1|1</string>
  <string>ORDINI IMBALLATO|SELECT * FROM VISTA_KNOS_INVIOCONFERMAORDINIMAIL WHERE CISTERNA = 0|1</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MetodoCommandDocs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MetodoCommandDocs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"""Gent.mo Cliente,"" & vbcrlf & ""Vi preghiamo di prendere visione del file allegato"" & vbcrlf & ""{0}"" & vbcrlf & ""Si prega di non rispondere a questo indirizzo email."" & vbcrlf & ""Dear Customer,"" & vbcrlf & ""please find the attached document:"" & vbcrlf & ""{0}"" & vbcrlf & ""Please do not reply to this email address."" & vbcrlf & ""ZSCHIMMER & SCHWARZ"" & vbcrlf & ""Italiana S.p.A."" & vbcrlf & ""Via A. Ariotto 1/C"" & vbcrlf & ""I - 13038 Tricerro, Italia"" & vbcrlf & ""Tel: +39 0161 808111"" & vbcrlf & ""Fax: +39 0161 807335"" & vbcrlf & ""Ufficio Commerciale:"" & vbcrlf & ""Fax: +39 0161 801002"" ")]
        public string sendMailDocMetodo {
            get {
                return ((string)(this["sendMailDocMetodo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invio Doc {0} {1}")]
        public string sendMailDocSubject {
            get {
                return ((string)(this["sendMailDocSubject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I:\\Italcom\\ItalcomMailing")]
        public string pathServerApp {
            get {
                return ((string)(this["pathServerApp"]));
            }
        }
    }
}
