//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34014
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignRTFPDF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>4096</string>
  <string>150</string>
  <string>30</string>
  <string>2133</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection firmatecnico {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["firmatecnico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>4096</string>
  <string>150</string>
  <string>30</string>
  <string>2759</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection firmaresptecnico {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["firmaresptecnico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>4096</string>
  <string>150</string>
  <string>30</string>
  <string>3151</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection firmacapocommessa {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["firmacapocommessa"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string startXML {
            get {
                return ((string)(this["startXML"]));
            }
            set {
                this["startXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("159")]
        public string KnoS_IdStatoIniziale {
            get {
                return ((string)(this["KnoS_IdStatoIniziale"]));
            }
            set {
                this["KnoS_IdStatoIniziale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public string KnoS_IdStato1F {
            get {
                return ((string)(this["KnoS_IdStato1F"]));
            }
            set {
                this["KnoS_IdStato1F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("161")]
        public string KnoS_IdStato2F {
            get {
                return ((string)(this["KnoS_IdStato2F"]));
            }
            set {
                this["KnoS_IdStato2F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("147")]
        public string KnoS_IdStatoPDLFirmato {
            get {
                return ((string)(this["KnoS_IdStatoPDLFirmato"]));
            }
            set {
                this["KnoS_IdStatoPDLFirmato"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("237")]
        public string KnoS_IdAction1F {
            get {
                return ((string)(this["KnoS_IdAction1F"]));
            }
            set {
                this["KnoS_IdAction1F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238")]
        public string KnoS_IdAction2F {
            get {
                return ((string)(this["KnoS_IdAction2F"]));
            }
            set {
                this["KnoS_IdAction2F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("208")]
        public string KnoS_IdActionPDFFirmato {
            get {
                return ((string)(this["KnoS_IdActionPDFFirmato"]));
            }
            set {
                this["KnoS_IdActionPDFFirmato"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("datetime_08")]
        public string KnoS_AttrNameData1F {
            get {
                return ((string)(this["KnoS_AttrNameData1F"]));
            }
            set {
                this["KnoS_AttrNameData1F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("datetime_09")]
        public string KnoS_AttrNameData2F {
            get {
                return ((string)(this["KnoS_AttrNameData2F"]));
            }
            set {
                this["KnoS_AttrNameData2F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("varchar_51")]
        public string KnoS_AttrNameUtenteTecnico {
            get {
                return ((string)(this["KnoS_AttrNameUtenteTecnico"]));
            }
            set {
                this["KnoS_AttrNameUtenteTecnico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("varchar_52")]
        public string KnoS_AttrNameUtenteResponsabileTecnico {
            get {
                return ((string)(this["KnoS_AttrNameUtenteResponsabileTecnico"]));
            }
            set {
                this["KnoS_AttrNameUtenteResponsabileTecnico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("varchar_53")]
        public string KnoS_AttrNameUtenteCapocCommessa {
            get {
                return ((string)(this["KnoS_AttrNameUtenteCapocCommessa"]));
            }
            set {
                this["KnoS_AttrNameUtenteCapocCommessa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("datetime_02")]
        public string KnoS_AttrNameDataFirmaPDL {
            get {
                return ((string)(this["KnoS_AttrNameDataFirmaPDL"]));
            }
            set {
                this["KnoS_AttrNameDataFirmaPDL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public string KnoS_IdStatoPDLDaFirmare {
            get {
                return ((string)(this["KnoS_IdStatoPDLDaFirmare"]));
            }
            set {
                this["KnoS_IdStatoPDLDaFirmare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string sendMailPopUp {
            get {
                return ((string)(this["sendMailPopUp"]));
            }
            set {
                this["sendMailPopUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("241")]
        public string KnoS_IdActionPDLDaFirmare {
            get {
                return ((string)(this["KnoS_IdActionPDLDaFirmare"]));
            }
            set {
                this["KnoS_IdActionPDLDaFirmare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Avviso al tecnico responsabile del lavoro nr {0}
I certificati risultano terminati dai tecnici dei quali lei risulta responsabile, viene richiesta la sua firma per procedere con il processo di richiesta firma digitale al tecnico capo commessa 
Prema questo link per procedere {1}
")]
        public string sendMailResponsabileMessage {
            get {
                return ((string)(this["sendMailResponsabileMessage"]));
            }
            set {
                this["sendMailResponsabileMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Avviso al tecnico capo commessa del lavoro nr {0}
I certificati risultano terminati dai tecnici e firmati dai responsabili, viene richiesta la sua firma digitale per terminare il processo ed inviare il certificato al cliente finale.
Prema questo link per procedere {1}
Grazie
")]
        public string sendMailCapocommessaMessage {
            get {
                return ((string)(this["sendMailCapocommessaMessage"]));
            }
            set {
                this["sendMailCapocommessaMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("varchar_54")]
        public string KnoS_AttrNameUtenteResponsabileTecnicoSost {
            get {
                return ((string)(this["KnoS_AttrNameUtenteResponsabileTecnicoSost"]));
            }
            set {
                this["KnoS_AttrNameUtenteResponsabileTecnicoSost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("varchar_55")]
        public string KnoS_AttrNameUtenteCapocCommessaSost {
            get {
                return ((string)(this["KnoS_AttrNameUtenteCapocCommessaSost"]));
            }
            set {
                this["KnoS_AttrNameUtenteCapocCommessaSost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KnoS_SearchExpressionResponsabili {
            get {
                return ((string)(this["KnoS_SearchExpressionResponsabili"]));
            }
            set {
                this["KnoS_SearchExpressionResponsabili"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KnoS_SearchExpressionCapiCommessa {
            get {
                return ((string)(this["KnoS_SearchExpressionCapiCommessa"]));
            }
            set {
                this["KnoS_SearchExpressionCapiCommessa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KnoS_URL {
            get {
                return ((string)(this["KnoS_URL"]));
            }
            set {
                this["KnoS_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KnoS_IdObject {
            get {
                return ((int)(this["KnoS_IdObject"]));
            }
            set {
                this["KnoS_IdObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("133")]
        public string KnoS_IdClassSostituti {
            get {
                return ((string)(this["KnoS_IdClassSostituti"]));
            }
            set {
                this["KnoS_IdClassSostituti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("126")]
        public string KnoS_IdViewSostituti {
            get {
                return ((string)(this["KnoS_IdViewSostituti"]));
            }
            set {
                this["KnoS_IdViewSostituti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("245")]
        public string KnoS_IdActionPDLFirmatoCERT {
            get {
                return ((string)(this["KnoS_IdActionPDLFirmatoCERT"]));
            }
            set {
                this["KnoS_IdActionPDLFirmatoCERT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useMapiMail {
            get {
                return ((bool)(this["useMapiMail"]));
            }
            set {
                this["useMapiMail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("135")]
        public int KnoS_IdClassSurvey {
            get {
                return ((int)(this["KnoS_IdClassSurvey"]));
            }
            set {
                this["KnoS_IdClassSurvey"] = value;
            }
        }
    }
}
